/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type EncodedAccount,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const ARCIUM_SIGNER_ACCOUNT_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([214, 157, 122, 114, 117, 44, 214, 74]);

export function getArciumSignerAccountDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    ARCIUM_SIGNER_ACCOUNT_DISCRIMINATOR
  );
}

export type ArciumSignerAccount = {
  discriminator: ReadonlyUint8Array;
  bump: number;
};

export type ArciumSignerAccountArgs = { bump: number };

/** Gets the encoder for {@link ArciumSignerAccountArgs} account data. */
export function getArciumSignerAccountEncoder(): FixedSizeEncoder<ArciumSignerAccountArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: ARCIUM_SIGNER_ACCOUNT_DISCRIMINATOR,
    })
  );
}

/** Gets the decoder for {@link ArciumSignerAccount} account data. */
export function getArciumSignerAccountDecoder(): FixedSizeDecoder<ArciumSignerAccount> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link ArciumSignerAccount} account data. */
export function getArciumSignerAccountCodec(): FixedSizeCodec<
  ArciumSignerAccountArgs,
  ArciumSignerAccount
> {
  return combineCodec(
    getArciumSignerAccountEncoder(),
    getArciumSignerAccountDecoder()
  );
}

export function decodeArciumSignerAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<ArciumSignerAccount, TAddress>;
export function decodeArciumSignerAccount<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<ArciumSignerAccount, TAddress>;
export function decodeArciumSignerAccount<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
):
  | Account<ArciumSignerAccount, TAddress>
  | MaybeAccount<ArciumSignerAccount, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getArciumSignerAccountDecoder()
  );
}

export async function fetchArciumSignerAccount<
  TAddress extends string = string
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<ArciumSignerAccount, TAddress>> {
  const maybeAccount = await fetchMaybeArciumSignerAccount(
    rpc,
    address,
    config
  );
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeArciumSignerAccount<
  TAddress extends string = string
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<ArciumSignerAccount, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeArciumSignerAccount(maybeAccount);
}

export async function fetchAllArciumSignerAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<ArciumSignerAccount>[]> {
  const maybeAccounts = await fetchAllMaybeArciumSignerAccount(
    rpc,
    addresses,
    config
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeArciumSignerAccount(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<ArciumSignerAccount>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeArciumSignerAccount(maybeAccount)
  );
}

export function getArciumSignerAccountSize(): number {
  return 9;
}
