/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
} from "@solana/kit";

export const STOCKPILE_SECRET_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([255, 124, 28, 6, 165, 72, 14, 187]);

export function getStockpileSecretDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    STOCKPILE_SECRET_DISCRIMINATOR,
  );
}

export type StockpileSecret = {
  discriminator: ReadonlyUint8Array;
  /** Stockpile this encrypted value belongs to. */
  stockpileId: bigint;
  /** True once this PDA has been initialized for a concrete stockpile id. */
  initialized: boolean;
  /** Rescue CTR nonce used by the encrypted payload. */
  nonce: Option<bigint>;
  /** Ciphertext limbs holding the encrypted stockpile random value. */
  ciphertexts: Option<Array<ReadonlyUint8Array>>;
  /** PDA bump seed. */
  bump: number;
};

export type StockpileSecretArgs = {
  /** Stockpile this encrypted value belongs to. */
  stockpileId: number | bigint;
  /** True once this PDA has been initialized for a concrete stockpile id. */
  initialized: boolean;
  /** Rescue CTR nonce used by the encrypted payload. */
  nonce: OptionOrNullable<number | bigint>;
  /** Ciphertext limbs holding the encrypted stockpile random value. */
  ciphertexts: OptionOrNullable<Array<ReadonlyUint8Array>>;
  /** PDA bump seed. */
  bump: number;
};

/** Gets the encoder for {@link StockpileSecretArgs} account data. */
export function getStockpileSecretEncoder(): Encoder<StockpileSecretArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["stockpileId", getU64Encoder()],
      ["initialized", getBooleanEncoder()],
      ["nonce", getOptionEncoder(getU128Encoder())],
      [
        "ciphertexts",
        getOptionEncoder(
          getArrayEncoder(fixEncoderSize(getBytesEncoder(), 32), { size: 1 }),
        ),
      ],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: STOCKPILE_SECRET_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link StockpileSecret} account data. */
export function getStockpileSecretDecoder(): Decoder<StockpileSecret> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["stockpileId", getU64Decoder()],
    ["initialized", getBooleanDecoder()],
    ["nonce", getOptionDecoder(getU128Decoder())],
    [
      "ciphertexts",
      getOptionDecoder(
        getArrayDecoder(fixDecoderSize(getBytesDecoder(), 32), { size: 1 }),
      ),
    ],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link StockpileSecret} account data. */
export function getStockpileSecretCodec(): Codec<
  StockpileSecretArgs,
  StockpileSecret
> {
  return combineCodec(getStockpileSecretEncoder(), getStockpileSecretDecoder());
}

export function decodeStockpileSecret<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<StockpileSecret, TAddress>;
export function decodeStockpileSecret<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<StockpileSecret, TAddress>;
export function decodeStockpileSecret<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
):
  | Account<StockpileSecret, TAddress>
  | MaybeAccount<StockpileSecret, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getStockpileSecretDecoder(),
  );
}

export async function fetchStockpileSecret<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<StockpileSecret, TAddress>> {
  const maybeAccount = await fetchMaybeStockpileSecret(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeStockpileSecret<
  TAddress extends string = string,
>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<StockpileSecret, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeStockpileSecret(maybeAccount);
}

export async function fetchAllStockpileSecret(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<StockpileSecret>[]> {
  const maybeAccounts = await fetchAllMaybeStockpileSecret(
    rpc,
    addresses,
    config,
  );
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeStockpileSecret(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<StockpileSecret>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) =>
    decodeStockpileSecret(maybeAccount),
  );
}
