/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";
import {
  getOutputDecoder,
  getOutputEncoder,
  getParameterDecoder,
  getParameterEncoder,
  type Output,
  type OutputArgs,
  type Parameter,
  type ParameterArgs,
} from ".";

/** The signature of a computation defined in a [ComputationDefinition]. */
export type ComputationSignature = {
  parameters: Array<Parameter>;
  outputs: Array<Output>;
};

export type ComputationSignatureArgs = {
  parameters: Array<ParameterArgs>;
  outputs: Array<OutputArgs>;
};

export function getComputationSignatureEncoder(): Encoder<ComputationSignatureArgs> {
  return getStructEncoder([
    ["parameters", getArrayEncoder(getParameterEncoder())],
    ["outputs", getArrayEncoder(getOutputEncoder())],
  ]);
}

export function getComputationSignatureDecoder(): Decoder<ComputationSignature> {
  return getStructDecoder([
    ["parameters", getArrayDecoder(getParameterDecoder())],
    ["outputs", getArrayDecoder(getOutputDecoder())],
  ]);
}

export function getComputationSignatureCodec(): Codec<
  ComputationSignatureArgs,
  ComputationSignature
> {
  return combineCodec(
    getComputationSignatureEncoder(),
    getComputationSignatureDecoder(),
  );
}
