/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";
import {
  getComputationSignatureDecoder,
  getComputationSignatureEncoder,
  type ComputationSignature,
  type ComputationSignatureArgs,
} from ".";

/** A computation definition for execution in a MXE. */
export type ComputationDefinitionMeta = {
  circuitLen: number;
  signature: ComputationSignature;
};

export type ComputationDefinitionMetaArgs = {
  circuitLen: number;
  signature: ComputationSignatureArgs;
};

export function getComputationDefinitionMetaEncoder(): Encoder<ComputationDefinitionMetaArgs> {
  return getStructEncoder([
    ["circuitLen", getU32Encoder()],
    ["signature", getComputationSignatureEncoder()],
  ]);
}

export function getComputationDefinitionMetaDecoder(): Decoder<ComputationDefinitionMeta> {
  return getStructDecoder([
    ["circuitLen", getU32Decoder()],
    ["signature", getComputationSignatureDecoder()],
  ]);
}

export function getComputationDefinitionMetaCodec(): Codec<
  ComputationDefinitionMetaArgs,
  ComputationDefinitionMeta
> {
  return combineCodec(
    getComputationDefinitionMetaEncoder(),
    getComputationDefinitionMetaDecoder(),
  );
}
