/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from "@solana/kit";

export type InitCompDefArgs = { source: string };

export type InitCompDefArgsArgs = InitCompDefArgs;

export function getInitCompDefArgsEncoder(): Encoder<InitCompDefArgsArgs> {
  return getStructEncoder([
    ["source", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
  ]);
}

export function getInitCompDefArgsDecoder(): Decoder<InitCompDefArgs> {
  return getStructDecoder([
    ["source", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getInitCompDefArgsCodec(): Codec<
  InitCompDefArgsArgs,
  InitCompDefArgs
> {
  return combineCodec(getInitCompDefArgsEncoder(), getInitCompDefArgsDecoder());
}
