/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/** The status of an MXE. */
export enum MxeStatus {
  Active,
  Migration,
}

export type MxeStatusArgs = MxeStatus;

export function getMxeStatusEncoder(): FixedSizeEncoder<MxeStatusArgs> {
  return getEnumEncoder(MxeStatus);
}

export function getMxeStatusDecoder(): FixedSizeDecoder<MxeStatus> {
  return getEnumDecoder(MxeStatus);
}

export function getMxeStatusCodec(): FixedSizeCodec<MxeStatusArgs, MxeStatus> {
  return combineCodec(getMxeStatusEncoder(), getMxeStatusDecoder());
}
