/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from "@solana/kit";

export type OffChainCircuitSource = {
  source: string;
  hash: ReadonlyUint8Array;
};

export type OffChainCircuitSourceArgs = OffChainCircuitSource;

export function getOffChainCircuitSourceEncoder(): Encoder<OffChainCircuitSourceArgs> {
  return getStructEncoder([
    ["source", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ["hash", fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

export function getOffChainCircuitSourceDecoder(): Decoder<OffChainCircuitSource> {
  return getStructDecoder([
    ["source", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["hash", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getOffChainCircuitSourceCodec(): Codec<
  OffChainCircuitSourceArgs,
  OffChainCircuitSource
> {
  return combineCodec(
    getOffChainCircuitSourceEncoder(),
    getOffChainCircuitSourceDecoder(),
  );
}
