/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/**
 * An output of a computation.
 * We currently don't support encrypted outputs yet since encrypted values are passed via
 * data objects.
 */
export enum Output {
  PlaintextBool,
  PlaintextU8,
  PlaintextU16,
  PlaintextU32,
  PlaintextU64,
  PlaintextU128,
  Ciphertext,
  ArcisX25519Pubkey,
  PlaintextFloat,
  PlaintextPoint,
  PlaintextI8,
  PlaintextI16,
  PlaintextI32,
  PlaintextI64,
  PlaintextI128,
}

export type OutputArgs = Output;

export function getOutputEncoder(): FixedSizeEncoder<OutputArgs> {
  return getEnumEncoder(Output);
}

export function getOutputDecoder(): FixedSizeDecoder<Output> {
  return getEnumDecoder(Output);
}

export function getOutputCodec(): FixedSizeCodec<OutputArgs, Output> {
  return combineCodec(getOutputEncoder(), getOutputDecoder());
}
