/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

/** One compact sidecar entry for a Wildcat-eligible round winner. */
export type RoundWildcatEntry = {
  /** Player wallet that owns the miner. */
  player: Address;
  /** Net deploy amount used to keep the bounded Wildcat candidate set deterministic. */
  deployAmount: bigint;
  /** Hidden-bonus-brick Wildcat ticket weight for this winner. */
  weight: bigint;
};

export type RoundWildcatEntryArgs = {
  /** Player wallet that owns the miner. */
  player: Address;
  /** Net deploy amount used to keep the bounded Wildcat candidate set deterministic. */
  deployAmount: number | bigint;
  /** Hidden-bonus-brick Wildcat ticket weight for this winner. */
  weight: number | bigint;
};

export function getRoundWildcatEntryEncoder(): FixedSizeEncoder<RoundWildcatEntryArgs> {
  return getStructEncoder([
    ["player", getAddressEncoder()],
    ["deployAmount", getU64Encoder()],
    ["weight", getU64Encoder()],
  ]);
}

export function getRoundWildcatEntryDecoder(): FixedSizeDecoder<RoundWildcatEntry> {
  return getStructDecoder([
    ["player", getAddressDecoder()],
    ["deployAmount", getU64Decoder()],
    ["weight", getU64Decoder()],
  ]);
}

export function getRoundWildcatEntryCodec(): FixedSizeCodec<
  RoundWildcatEntryArgs,
  RoundWildcatEntry
> {
  return combineCodec(
    getRoundWildcatEntryEncoder(),
    getRoundWildcatEntryDecoder(),
  );
}
