/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export async function findBoardPda(
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "zincUFpnqYwdYMc1KfH6rKcBvbcdVtHKckKhvrHLDsV" as Address<"zincUFpnqYwdYMc1KfH6rKcBvbcdVtHKckKhvrHLDsV">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [getBytesEncoder().encode(new Uint8Array([98, 111, 97, 114, 100]))],
  });
}
