/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getBytesEncoder,
  getProgramDerivedAddress,
  getU64Encoder,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export type RoundSecretSeeds = {
  roundId: number | bigint;
};

export async function findRoundSecretPda(
  seeds: RoundSecretSeeds,
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "zincUFpnqYwdYMc1KfH6rKcBvbcdVtHKckKhvrHLDsV" as Address<"zincUFpnqYwdYMc1KfH6rKcBvbcdVtHKckKhvrHLDsV">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([
          114, 111, 117, 110, 100, 45, 115, 101, 99, 114, 101, 116,
        ]),
      ),
      getU64Encoder().encode(seeds.roundId),
    ],
  });
}
