/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export async function findStakingTokenAccountPda(
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "DhNsfwRced8Z5hWy6Db4BVWrhaF2VAzMXCmBoiHkYW8N" as Address<"DhNsfwRced8Z5hWy6Db4BVWrhaF2VAzMXCmBoiHkYW8N">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([116, 114, 101, 97, 115, 117, 114, 121]),
      ),
      getBytesEncoder().encode(
        new Uint8Array([
          115, 116, 97, 107, 105, 110, 103, 45, 116, 111, 107, 101, 110, 45, 97,
          99, 99, 111, 117, 110, 116,
        ]),
      ),
    ],
  });
}
