/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  getBytesEncoder,
  getProgramDerivedAddress,
  type Address,
  type ProgramDerivedAddress,
} from "@solana/kit";

export async function findStockpileSolVaultPda(
  config: { programAddress?: Address | undefined } = {},
): Promise<ProgramDerivedAddress> {
  const {
    programAddress = "5ACS5hVH1J5KaE5qTHQy49fWWrhTae17Mj5yM9VyY69f" as Address<"5ACS5hVH1J5KaE5qTHQy49fWWrhTae17Mj5yM9VyY69f">,
  } = config;
  return await getProgramDerivedAddress({
    programAddress,
    seeds: [
      getBytesEncoder().encode(
        new Uint8Array([
          115, 116, 111, 99, 107, 112, 105, 108, 101, 45, 115, 111, 108, 45,
          118, 97, 117, 108, 116,
        ]),
      ),
    ],
  });
}
