/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findBuybackPoolPda,
  findBuybackZincTokenAccountPda,
  findConfigPda,
  findStakingRewardTokenAccountPda,
  findTreasuryPda,
} from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const BUYBACK_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  106, 117, 64, 30, 56, 69, 7, 45,
]);

export function getBuybackDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(BUYBACK_DISCRIMINATOR);
}

export type BuybackInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountBuybackPool extends string | AccountMeta<string> = string,
  TAccountWsolMint extends
    | string
    | AccountMeta<string> = "So11111111111111111111111111111111111111112",
  TAccountZincMint extends string | AccountMeta<string> = string,
  TAccountTreasuryWsolTokenAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountBuybackZincTokenAccount extends string | AccountMeta<string> = string,
  TAccountStakingRewardTokenAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountPoolAuthority extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountTokenAVault extends string | AccountMeta<string> = string,
  TAccountTokenBVault extends string | AccountMeta<string> = string,
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountMeteoraProgram extends
    | string
    | AccountMeta<string> = "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG",
  TAccountInstructionsSysvar extends
    | string
    | AccountMeta<string> = "Sysvar1nstructions1111111111111111111111111",
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountBuybackPool extends string
        ? ReadonlyAccount<TAccountBuybackPool>
        : TAccountBuybackPool,
      TAccountWsolMint extends string
        ? ReadonlyAccount<TAccountWsolMint>
        : TAccountWsolMint,
      TAccountZincMint extends string
        ? WritableAccount<TAccountZincMint>
        : TAccountZincMint,
      TAccountTreasuryWsolTokenAccount extends string
        ? WritableAccount<TAccountTreasuryWsolTokenAccount>
        : TAccountTreasuryWsolTokenAccount,
      TAccountBuybackZincTokenAccount extends string
        ? WritableAccount<TAccountBuybackZincTokenAccount>
        : TAccountBuybackZincTokenAccount,
      TAccountStakingRewardTokenAccount extends string
        ? WritableAccount<TAccountStakingRewardTokenAccount>
        : TAccountStakingRewardTokenAccount,
      TAccountPoolAuthority extends string
        ? ReadonlyAccount<TAccountPoolAuthority>
        : TAccountPoolAuthority,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountTokenAVault extends string
        ? WritableAccount<TAccountTokenAVault>
        : TAccountTokenAVault,
      TAccountTokenBVault extends string
        ? WritableAccount<TAccountTokenBVault>
        : TAccountTokenBVault,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountMeteoraProgram extends string
        ? ReadonlyAccount<TAccountMeteoraProgram>
        : TAccountMeteoraProgram,
      TAccountInstructionsSysvar extends string
        ? ReadonlyAccount<TAccountInstructionsSysvar>
        : TAccountInstructionsSysvar,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts
    ]
  >;

export type BuybackInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Exact WSOL amount Meteora must spend from the treasury-owned source account. */
  amountIn: bigint;
  /** Minimum ZINC amount that must be received before the melt sink runs. */
  minZincOut: bigint;
};

export type BuybackInstructionDataArgs = {
  /** Exact WSOL amount Meteora must spend from the treasury-owned source account. */
  amountIn: number | bigint;
  /** Minimum ZINC amount that must be received before the melt sink runs. */
  minZincOut: number | bigint;
};

export function getBuybackInstructionDataEncoder(): FixedSizeEncoder<BuybackInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amountIn", getU64Encoder()],
      ["minZincOut", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: BUYBACK_DISCRIMINATOR })
  );
}

export function getBuybackInstructionDataDecoder(): FixedSizeDecoder<BuybackInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amountIn", getU64Decoder()],
    ["minZincOut", getU64Decoder()],
  ]);
}

export function getBuybackInstructionDataCodec(): FixedSizeCodec<
  BuybackInstructionDataArgs,
  BuybackInstructionData
> {
  return combineCodec(
    getBuybackInstructionDataEncoder(),
    getBuybackInstructionDataDecoder()
  );
}

export type BuybackAsyncInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountTreasury extends string = string,
  TAccountBuybackPool extends string = string,
  TAccountWsolMint extends string = string,
  TAccountZincMint extends string = string,
  TAccountTreasuryWsolTokenAccount extends string = string,
  TAccountBuybackZincTokenAccount extends string = string,
  TAccountStakingRewardTokenAccount extends string = string,
  TAccountPoolAuthority extends string = string,
  TAccountPool extends string = string,
  TAccountTokenAVault extends string = string,
  TAccountTokenBVault extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountMeteoraProgram extends string = string,
  TAccountInstructionsSysvar extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string
> = {
  /** Crank authority that runs the privileged buyback transaction. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing the crank authority and treasury address. */
  config?: Address<TAccountConfig>;
  /** Treasury PDA that owns WSOL input, ZINC output, and staking reward state. */
  treasury?: Address<TAccountTreasury>;
  /** Stored Meteora buyback pool manifest. */
  buybackPool?: Address<TAccountBuybackPool>;
  /** SPL native mint for treasury-owned wrapped SOL. */
  wsolMint?: Address<TAccountWsolMint>;
  /** Protocol ZINC mint received from Meteora and burned by the melt sink. */
  zincMint: Address<TAccountZincMint>;
  /** Treasury-owned WSOL account spent by Meteora. */
  treasuryWsolTokenAccount?: Address<TAccountTreasuryWsolTokenAccount>;
  /** Protocol-owned ZINC account that receives bought ZINC before sharing and burning. */
  buybackZincTokenAccount?: Address<TAccountBuybackZincTokenAccount>;
  /** Treasury-owned reward vault that receives the staker share of bought ZINC. */
  stakingRewardTokenAccount?: Address<TAccountStakingRewardTokenAccount>;
  poolAuthority: Address<TAccountPoolAuthority>;
  pool: Address<TAccountPool>;
  tokenAVault: Address<TAccountTokenAVault>;
  tokenBVault: Address<TAccountTokenBVault>;
  eventAuthority: Address<TAccountEventAuthority>;
  meteoraProgram?: Address<TAccountMeteoraProgram>;
  instructionsSysvar?: Address<TAccountInstructionsSysvar>;
  /** SPL Token Program that owns all buyback token accounts. */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** System Program used to initialize the protocol ZINC output account when missing. */
  systemProgram?: Address<TAccountSystemProgram>;
  amountIn: BuybackInstructionDataArgs["amountIn"];
  minZincOut: BuybackInstructionDataArgs["minZincOut"];
};

export async function getBuybackInstructionAsync<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountTreasury extends string,
  TAccountBuybackPool extends string,
  TAccountWsolMint extends string,
  TAccountZincMint extends string,
  TAccountTreasuryWsolTokenAccount extends string,
  TAccountBuybackZincTokenAccount extends string,
  TAccountStakingRewardTokenAccount extends string,
  TAccountPoolAuthority extends string,
  TAccountPool extends string,
  TAccountTokenAVault extends string,
  TAccountTokenBVault extends string,
  TAccountEventAuthority extends string,
  TAccountMeteoraProgram extends string,
  TAccountInstructionsSysvar extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: BuybackAsyncInput<
    TAccountSigner,
    TAccountConfig,
    TAccountTreasury,
    TAccountBuybackPool,
    TAccountWsolMint,
    TAccountZincMint,
    TAccountTreasuryWsolTokenAccount,
    TAccountBuybackZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountPoolAuthority,
    TAccountPool,
    TAccountTokenAVault,
    TAccountTokenBVault,
    TAccountEventAuthority,
    TAccountMeteoraProgram,
    TAccountInstructionsSysvar,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  BuybackInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountTreasury,
    TAccountBuybackPool,
    TAccountWsolMint,
    TAccountZincMint,
    TAccountTreasuryWsolTokenAccount,
    TAccountBuybackZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountPoolAuthority,
    TAccountPool,
    TAccountTokenAVault,
    TAccountTokenBVault,
    TAccountEventAuthority,
    TAccountMeteoraProgram,
    TAccountInstructionsSysvar,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: true },
    buybackPool: { value: input.buybackPool ?? null, isWritable: false },
    wsolMint: { value: input.wsolMint ?? null, isWritable: false },
    zincMint: { value: input.zincMint ?? null, isWritable: true },
    treasuryWsolTokenAccount: {
      value: input.treasuryWsolTokenAccount ?? null,
      isWritable: true,
    },
    buybackZincTokenAccount: {
      value: input.buybackZincTokenAccount ?? null,
      isWritable: true,
    },
    stakingRewardTokenAccount: {
      value: input.stakingRewardTokenAccount ?? null,
      isWritable: true,
    },
    poolAuthority: { value: input.poolAuthority ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    tokenAVault: { value: input.tokenAVault ?? null, isWritable: true },
    tokenBVault: { value: input.tokenBVault ?? null, isWritable: true },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    meteoraProgram: { value: input.meteoraProgram ?? null, isWritable: false },
    instructionsSysvar: {
      value: input.instructionsSysvar ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.buybackPool.value) {
    accounts.buybackPool.value = await findBuybackPoolPda();
  }
  if (!accounts.wsolMint.value) {
    accounts.wsolMint.value =
      "So11111111111111111111111111111111111111112" as Address<"So11111111111111111111111111111111111111112">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.treasuryWsolTokenAccount.value) {
    accounts.treasuryWsolTokenAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "treasury",
            accounts.treasury.value
          )
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "tokenProgram",
            accounts.tokenProgram.value
          )
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "wsolMint",
            accounts.wsolMint.value
          )
        ),
      ],
    });
  }
  if (!accounts.buybackZincTokenAccount.value) {
    accounts.buybackZincTokenAccount.value =
      await findBuybackZincTokenAccountPda();
  }
  if (!accounts.stakingRewardTokenAccount.value) {
    accounts.stakingRewardTokenAccount.value =
      await findStakingRewardTokenAccountPda();
  }
  if (!accounts.meteoraProgram.value) {
    accounts.meteoraProgram.value =
      "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG" as Address<"cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG">;
  }
  if (!accounts.instructionsSysvar.value) {
    accounts.instructionsSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("buybackPool", accounts.buybackPool),
      getAccountMeta("wsolMint", accounts.wsolMint),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta(
        "treasuryWsolTokenAccount",
        accounts.treasuryWsolTokenAccount
      ),
      getAccountMeta(
        "buybackZincTokenAccount",
        accounts.buybackZincTokenAccount
      ),
      getAccountMeta(
        "stakingRewardTokenAccount",
        accounts.stakingRewardTokenAccount
      ),
      getAccountMeta("poolAuthority", accounts.poolAuthority),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("tokenAVault", accounts.tokenAVault),
      getAccountMeta("tokenBVault", accounts.tokenBVault),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("meteoraProgram", accounts.meteoraProgram),
      getAccountMeta("instructionsSysvar", accounts.instructionsSysvar),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getBuybackInstructionDataEncoder().encode(
      args as BuybackInstructionDataArgs
    ),
    programAddress,
  } as BuybackInstruction<TProgramAddress, TAccountSigner, TAccountConfig, TAccountTreasury, TAccountBuybackPool, TAccountWsolMint, TAccountZincMint, TAccountTreasuryWsolTokenAccount, TAccountBuybackZincTokenAccount, TAccountStakingRewardTokenAccount, TAccountPoolAuthority, TAccountPool, TAccountTokenAVault, TAccountTokenBVault, TAccountEventAuthority, TAccountMeteoraProgram, TAccountInstructionsSysvar, TAccountTokenProgram, TAccountSystemProgram>);
}

export type BuybackInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountTreasury extends string = string,
  TAccountBuybackPool extends string = string,
  TAccountWsolMint extends string = string,
  TAccountZincMint extends string = string,
  TAccountTreasuryWsolTokenAccount extends string = string,
  TAccountBuybackZincTokenAccount extends string = string,
  TAccountStakingRewardTokenAccount extends string = string,
  TAccountPoolAuthority extends string = string,
  TAccountPool extends string = string,
  TAccountTokenAVault extends string = string,
  TAccountTokenBVault extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountMeteoraProgram extends string = string,
  TAccountInstructionsSysvar extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string
> = {
  /** Crank authority that runs the privileged buyback transaction. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing the crank authority and treasury address. */
  config: Address<TAccountConfig>;
  /** Treasury PDA that owns WSOL input, ZINC output, and staking reward state. */
  treasury: Address<TAccountTreasury>;
  /** Stored Meteora buyback pool manifest. */
  buybackPool: Address<TAccountBuybackPool>;
  /** SPL native mint for treasury-owned wrapped SOL. */
  wsolMint?: Address<TAccountWsolMint>;
  /** Protocol ZINC mint received from Meteora and burned by the melt sink. */
  zincMint: Address<TAccountZincMint>;
  /** Treasury-owned WSOL account spent by Meteora. */
  treasuryWsolTokenAccount: Address<TAccountTreasuryWsolTokenAccount>;
  /** Protocol-owned ZINC account that receives bought ZINC before sharing and burning. */
  buybackZincTokenAccount: Address<TAccountBuybackZincTokenAccount>;
  /** Treasury-owned reward vault that receives the staker share of bought ZINC. */
  stakingRewardTokenAccount: Address<TAccountStakingRewardTokenAccount>;
  poolAuthority: Address<TAccountPoolAuthority>;
  pool: Address<TAccountPool>;
  tokenAVault: Address<TAccountTokenAVault>;
  tokenBVault: Address<TAccountTokenBVault>;
  eventAuthority: Address<TAccountEventAuthority>;
  meteoraProgram?: Address<TAccountMeteoraProgram>;
  instructionsSysvar?: Address<TAccountInstructionsSysvar>;
  /** SPL Token Program that owns all buyback token accounts. */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** System Program used to initialize the protocol ZINC output account when missing. */
  systemProgram?: Address<TAccountSystemProgram>;
  amountIn: BuybackInstructionDataArgs["amountIn"];
  minZincOut: BuybackInstructionDataArgs["minZincOut"];
};

export function getBuybackInstruction<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountTreasury extends string,
  TAccountBuybackPool extends string,
  TAccountWsolMint extends string,
  TAccountZincMint extends string,
  TAccountTreasuryWsolTokenAccount extends string,
  TAccountBuybackZincTokenAccount extends string,
  TAccountStakingRewardTokenAccount extends string,
  TAccountPoolAuthority extends string,
  TAccountPool extends string,
  TAccountTokenAVault extends string,
  TAccountTokenBVault extends string,
  TAccountEventAuthority extends string,
  TAccountMeteoraProgram extends string,
  TAccountInstructionsSysvar extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: BuybackInput<
    TAccountSigner,
    TAccountConfig,
    TAccountTreasury,
    TAccountBuybackPool,
    TAccountWsolMint,
    TAccountZincMint,
    TAccountTreasuryWsolTokenAccount,
    TAccountBuybackZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountPoolAuthority,
    TAccountPool,
    TAccountTokenAVault,
    TAccountTokenBVault,
    TAccountEventAuthority,
    TAccountMeteoraProgram,
    TAccountInstructionsSysvar,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): BuybackInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountConfig,
  TAccountTreasury,
  TAccountBuybackPool,
  TAccountWsolMint,
  TAccountZincMint,
  TAccountTreasuryWsolTokenAccount,
  TAccountBuybackZincTokenAccount,
  TAccountStakingRewardTokenAccount,
  TAccountPoolAuthority,
  TAccountPool,
  TAccountTokenAVault,
  TAccountTokenBVault,
  TAccountEventAuthority,
  TAccountMeteoraProgram,
  TAccountInstructionsSysvar,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: true },
    buybackPool: { value: input.buybackPool ?? null, isWritable: false },
    wsolMint: { value: input.wsolMint ?? null, isWritable: false },
    zincMint: { value: input.zincMint ?? null, isWritable: true },
    treasuryWsolTokenAccount: {
      value: input.treasuryWsolTokenAccount ?? null,
      isWritable: true,
    },
    buybackZincTokenAccount: {
      value: input.buybackZincTokenAccount ?? null,
      isWritable: true,
    },
    stakingRewardTokenAccount: {
      value: input.stakingRewardTokenAccount ?? null,
      isWritable: true,
    },
    poolAuthority: { value: input.poolAuthority ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    tokenAVault: { value: input.tokenAVault ?? null, isWritable: true },
    tokenBVault: { value: input.tokenBVault ?? null, isWritable: true },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    meteoraProgram: { value: input.meteoraProgram ?? null, isWritable: false },
    instructionsSysvar: {
      value: input.instructionsSysvar ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.wsolMint.value) {
    accounts.wsolMint.value =
      "So11111111111111111111111111111111111111112" as Address<"So11111111111111111111111111111111111111112">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.meteoraProgram.value) {
    accounts.meteoraProgram.value =
      "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG" as Address<"cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG">;
  }
  if (!accounts.instructionsSysvar.value) {
    accounts.instructionsSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("buybackPool", accounts.buybackPool),
      getAccountMeta("wsolMint", accounts.wsolMint),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta(
        "treasuryWsolTokenAccount",
        accounts.treasuryWsolTokenAccount
      ),
      getAccountMeta(
        "buybackZincTokenAccount",
        accounts.buybackZincTokenAccount
      ),
      getAccountMeta(
        "stakingRewardTokenAccount",
        accounts.stakingRewardTokenAccount
      ),
      getAccountMeta("poolAuthority", accounts.poolAuthority),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("tokenAVault", accounts.tokenAVault),
      getAccountMeta("tokenBVault", accounts.tokenBVault),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("meteoraProgram", accounts.meteoraProgram),
      getAccountMeta("instructionsSysvar", accounts.instructionsSysvar),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getBuybackInstructionDataEncoder().encode(
      args as BuybackInstructionDataArgs
    ),
    programAddress,
  } as BuybackInstruction<TProgramAddress, TAccountSigner, TAccountConfig, TAccountTreasury, TAccountBuybackPool, TAccountWsolMint, TAccountZincMint, TAccountTreasuryWsolTokenAccount, TAccountBuybackZincTokenAccount, TAccountStakingRewardTokenAccount, TAccountPoolAuthority, TAccountPool, TAccountTokenAVault, TAccountTokenBVault, TAccountEventAuthority, TAccountMeteoraProgram, TAccountInstructionsSysvar, TAccountTokenProgram, TAccountSystemProgram>);
}

export type ParsedBuybackInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Crank authority that runs the privileged buyback transaction. */
    signer: TAccountMetas[0];
    /** Global config containing the crank authority and treasury address. */
    config: TAccountMetas[1];
    /** Treasury PDA that owns WSOL input, ZINC output, and staking reward state. */
    treasury: TAccountMetas[2];
    /** Stored Meteora buyback pool manifest. */
    buybackPool: TAccountMetas[3];
    /** SPL native mint for treasury-owned wrapped SOL. */
    wsolMint: TAccountMetas[4];
    /** Protocol ZINC mint received from Meteora and burned by the melt sink. */
    zincMint: TAccountMetas[5];
    /** Treasury-owned WSOL account spent by Meteora. */
    treasuryWsolTokenAccount: TAccountMetas[6];
    /** Protocol-owned ZINC account that receives bought ZINC before sharing and burning. */
    buybackZincTokenAccount: TAccountMetas[7];
    /** Treasury-owned reward vault that receives the staker share of bought ZINC. */
    stakingRewardTokenAccount: TAccountMetas[8];
    poolAuthority: TAccountMetas[9];
    pool: TAccountMetas[10];
    tokenAVault: TAccountMetas[11];
    tokenBVault: TAccountMetas[12];
    eventAuthority: TAccountMetas[13];
    meteoraProgram: TAccountMetas[14];
    instructionsSysvar: TAccountMetas[15];
    /** SPL Token Program that owns all buyback token accounts. */
    tokenProgram: TAccountMetas[16];
    /** System Program used to initialize the protocol ZINC output account when missing. */
    systemProgram: TAccountMetas[17];
  };
  data: BuybackInstructionData;
};

export function parseBuybackInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedBuybackInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 18) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 18,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      config: getNextAccount(),
      treasury: getNextAccount(),
      buybackPool: getNextAccount(),
      wsolMint: getNextAccount(),
      zincMint: getNextAccount(),
      treasuryWsolTokenAccount: getNextAccount(),
      buybackZincTokenAccount: getNextAccount(),
      stakingRewardTokenAccount: getNextAccount(),
      poolAuthority: getNextAccount(),
      pool: getNextAccount(),
      tokenAVault: getNextAccount(),
      tokenBVault: getNextAccount(),
      eventAuthority: getNextAccount(),
      meteoraProgram: getNextAccount(),
      instructionsSysvar: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getBuybackInstructionDataDecoder().decode(instruction.data),
  };
}
