/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findPlayerProfilePda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const CLAIM_PLAYER_SOL_REWARDS_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([252, 223, 200, 209, 252, 5, 243, 65]);

export function getClaimPlayerSolRewardsDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIM_PLAYER_SOL_REWARDS_DISCRIMINATOR,
  );
}

export type ClaimPlayerSolRewardsInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountPlayerProfile extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountPlayerProfile extends string
        ? WritableAccount<TAccountPlayerProfile>
        : TAccountPlayerProfile,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimPlayerSolRewardsInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type ClaimPlayerSolRewardsInstructionDataArgs = {};

export function getClaimPlayerSolRewardsInstructionDataEncoder(): FixedSizeEncoder<ClaimPlayerSolRewardsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: CLAIM_PLAYER_SOL_REWARDS_DISCRIMINATOR,
    }),
  );
}

export function getClaimPlayerSolRewardsInstructionDataDecoder(): FixedSizeDecoder<ClaimPlayerSolRewardsInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getClaimPlayerSolRewardsInstructionDataCodec(): FixedSizeCodec<
  ClaimPlayerSolRewardsInstructionDataArgs,
  ClaimPlayerSolRewardsInstructionData
> {
  return combineCodec(
    getClaimPlayerSolRewardsInstructionDataEncoder(),
    getClaimPlayerSolRewardsInstructionDataDecoder(),
  );
}

export type ClaimPlayerSolRewardsAsyncInput<
  TAccountSigner extends string = string,
  TAccountPlayerProfile extends string = string,
> = {
  /** Player signer that owns the profile reward ledger and receives SOL. */
  signer: TransactionSigner<TAccountSigner>;
  /** Player profile holding aggregate round SOL reward accounting and custody. */
  playerProfile?: Address<TAccountPlayerProfile>;
};

export async function getClaimPlayerSolRewardsInstructionAsync<
  TAccountSigner extends string,
  TAccountPlayerProfile extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: ClaimPlayerSolRewardsAsyncInput<TAccountSigner, TAccountPlayerProfile>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ClaimPlayerSolRewardsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountPlayerProfile
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    playerProfile: { value: input.playerProfile ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.playerProfile.value) {
    accounts.playerProfile.value = await findPlayerProfilePda({
      signer: getAddressFromResolvedInstructionAccount(
        "signer",
        accounts.signer.value,
      ),
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("playerProfile", accounts.playerProfile),
    ],
    data: getClaimPlayerSolRewardsInstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimPlayerSolRewardsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountPlayerProfile
  >);
}

export type ClaimPlayerSolRewardsInput<
  TAccountSigner extends string = string,
  TAccountPlayerProfile extends string = string,
> = {
  /** Player signer that owns the profile reward ledger and receives SOL. */
  signer: TransactionSigner<TAccountSigner>;
  /** Player profile holding aggregate round SOL reward accounting and custody. */
  playerProfile: Address<TAccountPlayerProfile>;
};

export function getClaimPlayerSolRewardsInstruction<
  TAccountSigner extends string,
  TAccountPlayerProfile extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: ClaimPlayerSolRewardsInput<TAccountSigner, TAccountPlayerProfile>,
  config?: { programAddress?: TProgramAddress },
): ClaimPlayerSolRewardsInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountPlayerProfile
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    playerProfile: { value: input.playerProfile ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("playerProfile", accounts.playerProfile),
    ],
    data: getClaimPlayerSolRewardsInstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimPlayerSolRewardsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountPlayerProfile
  >);
}

export type ParsedClaimPlayerSolRewardsInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Player signer that owns the profile reward ledger and receives SOL. */
    signer: TAccountMetas[0];
    /** Player profile holding aggregate round SOL reward accounting and custody. */
    playerProfile: TAccountMetas[1];
  };
  data: ClaimPlayerSolRewardsInstructionData;
};

export function parseClaimPlayerSolRewardsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedClaimPlayerSolRewardsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 2) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 2,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { signer: getNextAccount(), playerProfile: getNextAccount() },
    data: getClaimPlayerSolRewardsInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
