/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findConfigPda,
  findRoundZincRewardTokenAccountPda,
  findTreasuryPda,
} from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const CLAIM_WILDCAT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  181, 248, 215, 25, 160, 80, 48, 79,
]);

export function getClaimWildcatDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLAIM_WILDCAT_DISCRIMINATOR,
  );
}

export type ClaimWildcatInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRound extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountZincMint extends string | AccountMeta<string> = string,
  TAccountRoundZincPayoutTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountWinnerPlayerProfile extends string | AccountMeta<string> = string,
  TAccountRoundZincRewardTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRound extends string
        ? WritableAccount<TAccountRound>
        : TAccountRound,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountZincMint extends string
        ? ReadonlyAccount<TAccountZincMint>
        : TAccountZincMint,
      TAccountRoundZincPayoutTokenAccount extends string
        ? WritableAccount<TAccountRoundZincPayoutTokenAccount>
        : TAccountRoundZincPayoutTokenAccount,
      TAccountWinnerPlayerProfile extends string
        ? WritableAccount<TAccountWinnerPlayerProfile>
        : TAccountWinnerPlayerProfile,
      TAccountRoundZincRewardTokenAccount extends string
        ? WritableAccount<TAccountRoundZincRewardTokenAccount>
        : TAccountRoundZincRewardTokenAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type ClaimWildcatInstructionData = { discriminator: ReadonlyUint8Array };

export type ClaimWildcatInstructionDataArgs = {};

export function getClaimWildcatInstructionDataEncoder(): FixedSizeEncoder<ClaimWildcatInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLAIM_WILDCAT_DISCRIMINATOR }),
  );
}

export function getClaimWildcatInstructionDataDecoder(): FixedSizeDecoder<ClaimWildcatInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getClaimWildcatInstructionDataCodec(): FixedSizeCodec<
  ClaimWildcatInstructionDataArgs,
  ClaimWildcatInstructionData
> {
  return combineCodec(
    getClaimWildcatInstructionDataEncoder(),
    getClaimWildcatInstructionDataDecoder(),
  );
}

export type ClaimWildcatAsyncInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountRound extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountRoundZincPayoutTokenAccount extends string = string,
  TAccountWinnerPlayerProfile extends string = string,
  TAccountRoundZincRewardTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Crank signer authorized to auto-credit the selected Wildcat payout. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing the crank authority and treasury address. */
  config?: Address<TAccountConfig>;
  /** Round with a selected uncredited Wildcat winner. */
  round: Address<TAccountRound>;
  /** Treasury PDA that stores the canonical ZINC mint. */
  treasury?: Address<TAccountTreasury>;
  /** Protocol ZINC mint used for Wildcat payouts. */
  zincMint: Address<TAccountZincMint>;
  /** Round-owned ZINC vault holding the selected Wildcat credit. */
  roundZincPayoutTokenAccount: Address<TAccountRoundZincPayoutTokenAccount>;
  /** Selected winner's profile that receives claimable Wildcat ZINC credit. */
  winnerPlayerProfile: Address<TAccountWinnerPlayerProfile>;
  /** Treasury-owned reward vault that funds later profile ZINC claims. */
  roundZincRewardTokenAccount?: Address<TAccountRoundZincRewardTokenAccount>;
  /** SPL Token Program that owns the ZINC mint and token vaults. */
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getClaimWildcatInstructionAsync<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountRound extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountRoundZincPayoutTokenAccount extends string,
  TAccountWinnerPlayerProfile extends string,
  TAccountRoundZincRewardTokenAccount extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: ClaimWildcatAsyncInput<
    TAccountSigner,
    TAccountConfig,
    TAccountRound,
    TAccountTreasury,
    TAccountZincMint,
    TAccountRoundZincPayoutTokenAccount,
    TAccountWinnerPlayerProfile,
    TAccountRoundZincRewardTokenAccount,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  ClaimWildcatInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountRound,
    TAccountTreasury,
    TAccountZincMint,
    TAccountRoundZincPayoutTokenAccount,
    TAccountWinnerPlayerProfile,
    TAccountRoundZincRewardTokenAccount,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    round: { value: input.round ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: false },
    roundZincPayoutTokenAccount: {
      value: input.roundZincPayoutTokenAccount ?? null,
      isWritable: true,
    },
    winnerPlayerProfile: {
      value: input.winnerPlayerProfile ?? null,
      isWritable: true,
    },
    roundZincRewardTokenAccount: {
      value: input.roundZincRewardTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.roundZincRewardTokenAccount.value) {
    accounts.roundZincRewardTokenAccount.value =
      await findRoundZincRewardTokenAccountPda();
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("round", accounts.round),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta(
        "roundZincPayoutTokenAccount",
        accounts.roundZincPayoutTokenAccount,
      ),
      getAccountMeta("winnerPlayerProfile", accounts.winnerPlayerProfile),
      getAccountMeta(
        "roundZincRewardTokenAccount",
        accounts.roundZincRewardTokenAccount,
      ),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getClaimWildcatInstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimWildcatInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountRound,
    TAccountTreasury,
    TAccountZincMint,
    TAccountRoundZincPayoutTokenAccount,
    TAccountWinnerPlayerProfile,
    TAccountRoundZincRewardTokenAccount,
    TAccountTokenProgram
  >);
}

export type ClaimWildcatInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountRound extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountRoundZincPayoutTokenAccount extends string = string,
  TAccountWinnerPlayerProfile extends string = string,
  TAccountRoundZincRewardTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Crank signer authorized to auto-credit the selected Wildcat payout. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing the crank authority and treasury address. */
  config: Address<TAccountConfig>;
  /** Round with a selected uncredited Wildcat winner. */
  round: Address<TAccountRound>;
  /** Treasury PDA that stores the canonical ZINC mint. */
  treasury: Address<TAccountTreasury>;
  /** Protocol ZINC mint used for Wildcat payouts. */
  zincMint: Address<TAccountZincMint>;
  /** Round-owned ZINC vault holding the selected Wildcat credit. */
  roundZincPayoutTokenAccount: Address<TAccountRoundZincPayoutTokenAccount>;
  /** Selected winner's profile that receives claimable Wildcat ZINC credit. */
  winnerPlayerProfile: Address<TAccountWinnerPlayerProfile>;
  /** Treasury-owned reward vault that funds later profile ZINC claims. */
  roundZincRewardTokenAccount: Address<TAccountRoundZincRewardTokenAccount>;
  /** SPL Token Program that owns the ZINC mint and token vaults. */
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getClaimWildcatInstruction<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountRound extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountRoundZincPayoutTokenAccount extends string,
  TAccountWinnerPlayerProfile extends string,
  TAccountRoundZincRewardTokenAccount extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: ClaimWildcatInput<
    TAccountSigner,
    TAccountConfig,
    TAccountRound,
    TAccountTreasury,
    TAccountZincMint,
    TAccountRoundZincPayoutTokenAccount,
    TAccountWinnerPlayerProfile,
    TAccountRoundZincRewardTokenAccount,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): ClaimWildcatInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountConfig,
  TAccountRound,
  TAccountTreasury,
  TAccountZincMint,
  TAccountRoundZincPayoutTokenAccount,
  TAccountWinnerPlayerProfile,
  TAccountRoundZincRewardTokenAccount,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    round: { value: input.round ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: false },
    roundZincPayoutTokenAccount: {
      value: input.roundZincPayoutTokenAccount ?? null,
      isWritable: true,
    },
    winnerPlayerProfile: {
      value: input.winnerPlayerProfile ?? null,
      isWritable: true,
    },
    roundZincRewardTokenAccount: {
      value: input.roundZincRewardTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("round", accounts.round),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta(
        "roundZincPayoutTokenAccount",
        accounts.roundZincPayoutTokenAccount,
      ),
      getAccountMeta("winnerPlayerProfile", accounts.winnerPlayerProfile),
      getAccountMeta(
        "roundZincRewardTokenAccount",
        accounts.roundZincRewardTokenAccount,
      ),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getClaimWildcatInstructionDataEncoder().encode({}),
    programAddress,
  } as ClaimWildcatInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountRound,
    TAccountTreasury,
    TAccountZincMint,
    TAccountRoundZincPayoutTokenAccount,
    TAccountWinnerPlayerProfile,
    TAccountRoundZincRewardTokenAccount,
    TAccountTokenProgram
  >);
}

export type ParsedClaimWildcatInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Crank signer authorized to auto-credit the selected Wildcat payout. */
    signer: TAccountMetas[0];
    /** Global config containing the crank authority and treasury address. */
    config: TAccountMetas[1];
    /** Round with a selected uncredited Wildcat winner. */
    round: TAccountMetas[2];
    /** Treasury PDA that stores the canonical ZINC mint. */
    treasury: TAccountMetas[3];
    /** Protocol ZINC mint used for Wildcat payouts. */
    zincMint: TAccountMetas[4];
    /** Round-owned ZINC vault holding the selected Wildcat credit. */
    roundZincPayoutTokenAccount: TAccountMetas[5];
    /** Selected winner's profile that receives claimable Wildcat ZINC credit. */
    winnerPlayerProfile: TAccountMetas[6];
    /** Treasury-owned reward vault that funds later profile ZINC claims. */
    roundZincRewardTokenAccount: TAccountMetas[7];
    /** SPL Token Program that owns the ZINC mint and token vaults. */
    tokenProgram: TAccountMetas[8];
  };
  data: ClaimWildcatInstructionData;
};

export function parseClaimWildcatInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedClaimWildcatInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      config: getNextAccount(),
      round: getNextAccount(),
      treasury: getNextAccount(),
      zincMint: getNextAccount(),
      roundZincPayoutTokenAccount: getNextAccount(),
      winnerPlayerProfile: getNextAccount(),
      roundZincRewardTokenAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getClaimWildcatInstructionDataDecoder().decode(instruction.data),
  };
}
