/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findConfigPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const CLOSE_MINER_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  101, 10, 186, 29, 231, 198, 255, 67,
]);

export function getCloseMinerDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CLOSE_MINER_DISCRIMINATOR);
}

export type CloseMinerInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRound extends string | AccountMeta<string> = string,
  TAccountMiner extends string | AccountMeta<string> = string,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRound extends string
        ? WritableAccount<TAccountRound>
        : TAccountRound,
      TAccountMiner extends string
        ? WritableAccount<TAccountMiner>
        : TAccountMiner,
      TAccountPlayer extends string
        ? WritableAccount<TAccountPlayer>
        : TAccountPlayer,
      ...TRemainingAccounts
    ]
  >;

export type CloseMinerInstructionData = { discriminator: ReadonlyUint8Array };

export type CloseMinerInstructionDataArgs = {};

export function getCloseMinerInstructionDataEncoder(): FixedSizeEncoder<CloseMinerInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: CLOSE_MINER_DISCRIMINATOR })
  );
}

export function getCloseMinerInstructionDataDecoder(): FixedSizeDecoder<CloseMinerInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseMinerInstructionDataCodec(): FixedSizeCodec<
  CloseMinerInstructionDataArgs,
  CloseMinerInstructionData
> {
  return combineCodec(
    getCloseMinerInstructionDataEncoder(),
    getCloseMinerInstructionDataDecoder()
  );
}

export type CloseMinerAsyncInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountRound extends string = string,
  TAccountMiner extends string = string,
  TAccountPlayer extends string = string
> = {
  /** Crank signer authorized to submit cleanup transactions. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing the cleanup crank authority. */
  config?: Address<TAccountConfig>;
  /** Terminal round whose miner cleanup counter is advanced. */
  round: Address<TAccountRound>;
  /** Settled miner account being closed to its owning player. */
  miner: Address<TAccountMiner>;
  player: Address<TAccountPlayer>;
};

export async function getCloseMinerInstructionAsync<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountRound extends string,
  TAccountMiner extends string,
  TAccountPlayer extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: CloseMinerAsyncInput<
    TAccountSigner,
    TAccountConfig,
    TAccountRound,
    TAccountMiner,
    TAccountPlayer
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  CloseMinerInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountRound,
    TAccountMiner,
    TAccountPlayer
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    round: { value: input.round ?? null, isWritable: true },
    miner: { value: input.miner ?? null, isWritable: true },
    player: { value: input.player ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("round", accounts.round),
      getAccountMeta("miner", accounts.miner),
      getAccountMeta("player", accounts.player),
    ],
    data: getCloseMinerInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseMinerInstruction<TProgramAddress, TAccountSigner, TAccountConfig, TAccountRound, TAccountMiner, TAccountPlayer>);
}

export type CloseMinerInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountRound extends string = string,
  TAccountMiner extends string = string,
  TAccountPlayer extends string = string
> = {
  /** Crank signer authorized to submit cleanup transactions. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing the cleanup crank authority. */
  config: Address<TAccountConfig>;
  /** Terminal round whose miner cleanup counter is advanced. */
  round: Address<TAccountRound>;
  /** Settled miner account being closed to its owning player. */
  miner: Address<TAccountMiner>;
  player: Address<TAccountPlayer>;
};

export function getCloseMinerInstruction<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountRound extends string,
  TAccountMiner extends string,
  TAccountPlayer extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: CloseMinerInput<
    TAccountSigner,
    TAccountConfig,
    TAccountRound,
    TAccountMiner,
    TAccountPlayer
  >,
  config?: { programAddress?: TProgramAddress }
): CloseMinerInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountConfig,
  TAccountRound,
  TAccountMiner,
  TAccountPlayer
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    round: { value: input.round ?? null, isWritable: true },
    miner: { value: input.miner ?? null, isWritable: true },
    player: { value: input.player ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("round", accounts.round),
      getAccountMeta("miner", accounts.miner),
      getAccountMeta("player", accounts.player),
    ],
    data: getCloseMinerInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseMinerInstruction<TProgramAddress, TAccountSigner, TAccountConfig, TAccountRound, TAccountMiner, TAccountPlayer>);
}

export type ParsedCloseMinerInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Crank signer authorized to submit cleanup transactions. */
    signer: TAccountMetas[0];
    /** Global config containing the cleanup crank authority. */
    config: TAccountMetas[1];
    /** Terminal round whose miner cleanup counter is advanced. */
    round: TAccountMetas[2];
    /** Settled miner account being closed to its owning player. */
    miner: TAccountMetas[3];
    player: TAccountMetas[4];
  };
  data: CloseMinerInstructionData;
};

export function parseCloseMinerInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedCloseMinerInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      config: getNextAccount(),
      round: getNextAccount(),
      miner: getNextAccount(),
      player: getNextAccount(),
    },
    data: getCloseMinerInstructionDataDecoder().decode(instruction.data),
  };
}
