/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findBoardPda, findConfigPda, findTreasuryPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const CLOSE_ROUND_ACCOUNTS_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([158, 92, 241, 90, 112, 189, 63, 133]);

export function getCloseRoundAccountsDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CLOSE_ROUND_ACCOUNTS_DISCRIMINATOR,
  );
}

export type CloseRoundAccountsInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountBoard extends string | AccountMeta<string> = string,
  TAccountRound extends string | AccountMeta<string> = string,
  TAccountRoundWildcatEntries extends string | AccountMeta<string> = string,
  TAccountRoundSecret extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountZincMint extends string | AccountMeta<string> = string,
  TAccountRoundZincPayoutTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountCurveAdminTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBoard extends string
        ? ReadonlyAccount<TAccountBoard>
        : TAccountBoard,
      TAccountRound extends string
        ? WritableAccount<TAccountRound>
        : TAccountRound,
      TAccountRoundWildcatEntries extends string
        ? WritableAccount<TAccountRoundWildcatEntries>
        : TAccountRoundWildcatEntries,
      TAccountRoundSecret extends string
        ? WritableAccount<TAccountRoundSecret>
        : TAccountRoundSecret,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountZincMint extends string
        ? ReadonlyAccount<TAccountZincMint>
        : TAccountZincMint,
      TAccountRoundZincPayoutTokenAccount extends string
        ? WritableAccount<TAccountRoundZincPayoutTokenAccount>
        : TAccountRoundZincPayoutTokenAccount,
      TAccountCurveAdminTokenAccount extends string
        ? WritableAccount<TAccountCurveAdminTokenAccount>
        : TAccountCurveAdminTokenAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CloseRoundAccountsInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type CloseRoundAccountsInstructionDataArgs = {};

export function getCloseRoundAccountsInstructionDataEncoder(): FixedSizeEncoder<CloseRoundAccountsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({
      ...value,
      discriminator: CLOSE_ROUND_ACCOUNTS_DISCRIMINATOR,
    }),
  );
}

export function getCloseRoundAccountsInstructionDataDecoder(): FixedSizeDecoder<CloseRoundAccountsInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getCloseRoundAccountsInstructionDataCodec(): FixedSizeCodec<
  CloseRoundAccountsInstructionDataArgs,
  CloseRoundAccountsInstructionData
> {
  return combineCodec(
    getCloseRoundAccountsInstructionDataEncoder(),
    getCloseRoundAccountsInstructionDataDecoder(),
  );
}

export type CloseRoundAccountsAsyncInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
  TAccountRound extends string = string,
  TAccountRoundWildcatEntries extends string = string,
  TAccountRoundSecret extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountRoundZincPayoutTokenAccount extends string = string,
  TAccountCurveAdminTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Crank signer authorized to submit cleanup transactions. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing the crank authority and canonical treasury address. */
  config?: Address<TAccountConfig>;
  /** Board account used to ensure no live pointer references the round. */
  board?: Address<TAccountBoard>;
  /** Fully cleaned round account being closed to the crank signer. */
  round: Address<TAccountRound>;
  /** Optional Wildcat sidecar being closed with the round when present. */
  roundWildcatEntries?: Address<TAccountRoundWildcatEntries>;
  /** Matching round-secret account being closed to the crank signer. */
  roundSecret: Address<TAccountRoundSecret>;
  /** Canonical treasury PDA used to validate the payout sweep destination. */
  treasury?: Address<TAccountTreasury>;
  /** Protocol ZINC mint used by the round payout vault. */
  zincMint: Address<TAccountZincMint>;
  /** Round-owned ZINC vault being swept and closed. */
  roundZincPayoutTokenAccount: Address<TAccountRoundZincPayoutTokenAccount>;
  /** Treasury curve-admin vault that receives residual round ZINC dust. */
  curveAdminTokenAccount?: Address<TAccountCurveAdminTokenAccount>;
  /** SPL Token program used to sweep and close the round ZINC vault. */
  tokenProgram?: Address<TAccountTokenProgram>;
};

export async function getCloseRoundAccountsInstructionAsync<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TAccountRound extends string,
  TAccountRoundWildcatEntries extends string,
  TAccountRoundSecret extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountRoundZincPayoutTokenAccount extends string,
  TAccountCurveAdminTokenAccount extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: CloseRoundAccountsAsyncInput<
    TAccountSigner,
    TAccountConfig,
    TAccountBoard,
    TAccountRound,
    TAccountRoundWildcatEntries,
    TAccountRoundSecret,
    TAccountTreasury,
    TAccountZincMint,
    TAccountRoundZincPayoutTokenAccount,
    TAccountCurveAdminTokenAccount,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CloseRoundAccountsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountBoard,
    TAccountRound,
    TAccountRoundWildcatEntries,
    TAccountRoundSecret,
    TAccountTreasury,
    TAccountZincMint,
    TAccountRoundZincPayoutTokenAccount,
    TAccountCurveAdminTokenAccount,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    board: { value: input.board ?? null, isWritable: false },
    round: { value: input.round ?? null, isWritable: true },
    roundWildcatEntries: {
      value: input.roundWildcatEntries ?? null,
      isWritable: true,
    },
    roundSecret: { value: input.roundSecret ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: false },
    roundZincPayoutTokenAccount: {
      value: input.roundZincPayoutTokenAccount ?? null,
      isWritable: true,
    },
    curveAdminTokenAccount: {
      value: input.curveAdminTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.board.value) {
    accounts.board.value = await findBoardPda();
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.curveAdminTokenAccount.value) {
    accounts.curveAdminTokenAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "treasury",
            accounts.treasury.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "tokenProgram",
            accounts.tokenProgram.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "zincMint",
            accounts.zincMint.value,
          ),
        ),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
      getAccountMeta("round", accounts.round),
      getAccountMeta("roundWildcatEntries", accounts.roundWildcatEntries),
      getAccountMeta("roundSecret", accounts.roundSecret),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta(
        "roundZincPayoutTokenAccount",
        accounts.roundZincPayoutTokenAccount,
      ),
      getAccountMeta("curveAdminTokenAccount", accounts.curveAdminTokenAccount),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getCloseRoundAccountsInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseRoundAccountsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountBoard,
    TAccountRound,
    TAccountRoundWildcatEntries,
    TAccountRoundSecret,
    TAccountTreasury,
    TAccountZincMint,
    TAccountRoundZincPayoutTokenAccount,
    TAccountCurveAdminTokenAccount,
    TAccountTokenProgram
  >);
}

export type CloseRoundAccountsInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
  TAccountRound extends string = string,
  TAccountRoundWildcatEntries extends string = string,
  TAccountRoundSecret extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountRoundZincPayoutTokenAccount extends string = string,
  TAccountCurveAdminTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Crank signer authorized to submit cleanup transactions. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing the crank authority and canonical treasury address. */
  config: Address<TAccountConfig>;
  /** Board account used to ensure no live pointer references the round. */
  board: Address<TAccountBoard>;
  /** Fully cleaned round account being closed to the crank signer. */
  round: Address<TAccountRound>;
  /** Optional Wildcat sidecar being closed with the round when present. */
  roundWildcatEntries?: Address<TAccountRoundWildcatEntries>;
  /** Matching round-secret account being closed to the crank signer. */
  roundSecret: Address<TAccountRoundSecret>;
  /** Canonical treasury PDA used to validate the payout sweep destination. */
  treasury: Address<TAccountTreasury>;
  /** Protocol ZINC mint used by the round payout vault. */
  zincMint: Address<TAccountZincMint>;
  /** Round-owned ZINC vault being swept and closed. */
  roundZincPayoutTokenAccount: Address<TAccountRoundZincPayoutTokenAccount>;
  /** Treasury curve-admin vault that receives residual round ZINC dust. */
  curveAdminTokenAccount: Address<TAccountCurveAdminTokenAccount>;
  /** SPL Token program used to sweep and close the round ZINC vault. */
  tokenProgram?: Address<TAccountTokenProgram>;
};

export function getCloseRoundAccountsInstruction<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TAccountRound extends string,
  TAccountRoundWildcatEntries extends string,
  TAccountRoundSecret extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountRoundZincPayoutTokenAccount extends string,
  TAccountCurveAdminTokenAccount extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: CloseRoundAccountsInput<
    TAccountSigner,
    TAccountConfig,
    TAccountBoard,
    TAccountRound,
    TAccountRoundWildcatEntries,
    TAccountRoundSecret,
    TAccountTreasury,
    TAccountZincMint,
    TAccountRoundZincPayoutTokenAccount,
    TAccountCurveAdminTokenAccount,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CloseRoundAccountsInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountConfig,
  TAccountBoard,
  TAccountRound,
  TAccountRoundWildcatEntries,
  TAccountRoundSecret,
  TAccountTreasury,
  TAccountZincMint,
  TAccountRoundZincPayoutTokenAccount,
  TAccountCurveAdminTokenAccount,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    board: { value: input.board ?? null, isWritable: false },
    round: { value: input.round ?? null, isWritable: true },
    roundWildcatEntries: {
      value: input.roundWildcatEntries ?? null,
      isWritable: true,
    },
    roundSecret: { value: input.roundSecret ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: false },
    roundZincPayoutTokenAccount: {
      value: input.roundZincPayoutTokenAccount ?? null,
      isWritable: true,
    },
    curveAdminTokenAccount: {
      value: input.curveAdminTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
      getAccountMeta("round", accounts.round),
      getAccountMeta("roundWildcatEntries", accounts.roundWildcatEntries),
      getAccountMeta("roundSecret", accounts.roundSecret),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta(
        "roundZincPayoutTokenAccount",
        accounts.roundZincPayoutTokenAccount,
      ),
      getAccountMeta("curveAdminTokenAccount", accounts.curveAdminTokenAccount),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getCloseRoundAccountsInstructionDataEncoder().encode({}),
    programAddress,
  } as CloseRoundAccountsInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountBoard,
    TAccountRound,
    TAccountRoundWildcatEntries,
    TAccountRoundSecret,
    TAccountTreasury,
    TAccountZincMint,
    TAccountRoundZincPayoutTokenAccount,
    TAccountCurveAdminTokenAccount,
    TAccountTokenProgram
  >);
}

export type ParsedCloseRoundAccountsInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Crank signer authorized to submit cleanup transactions. */
    signer: TAccountMetas[0];
    /** Global config containing the crank authority and canonical treasury address. */
    config: TAccountMetas[1];
    /** Board account used to ensure no live pointer references the round. */
    board: TAccountMetas[2];
    /** Fully cleaned round account being closed to the crank signer. */
    round: TAccountMetas[3];
    /** Optional Wildcat sidecar being closed with the round when present. */
    roundWildcatEntries?: TAccountMetas[4] | undefined;
    /** Matching round-secret account being closed to the crank signer. */
    roundSecret: TAccountMetas[5];
    /** Canonical treasury PDA used to validate the payout sweep destination. */
    treasury: TAccountMetas[6];
    /** Protocol ZINC mint used by the round payout vault. */
    zincMint: TAccountMetas[7];
    /** Round-owned ZINC vault being swept and closed. */
    roundZincPayoutTokenAccount: TAccountMetas[8];
    /** Treasury curve-admin vault that receives residual round ZINC dust. */
    curveAdminTokenAccount: TAccountMetas[9];
    /** SPL Token program used to sweep and close the round ZINC vault. */
    tokenProgram: TAccountMetas[10];
  };
  data: CloseRoundAccountsInstructionData;
};

export function parseCloseRoundAccountsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCloseRoundAccountsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 11) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 11,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  const getNextOptionalAccount = () => {
    const accountMeta = getNextAccount();
    return accountMeta.address === ZINC_PROGRAM_ADDRESS
      ? undefined
      : accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      config: getNextAccount(),
      board: getNextAccount(),
      round: getNextAccount(),
      roundWildcatEntries: getNextOptionalAccount(),
      roundSecret: getNextAccount(),
      treasury: getNextAccount(),
      zincMint: getNextAccount(),
      roundZincPayoutTokenAccount: getNextAccount(),
      curveAdminTokenAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getCloseRoundAccountsInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
