/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findBoardPda,
  findConfigPda,
  findStockpileExtrasPda,
  findTreasuryPda,
} from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const DEPOSIT_STOCKPILE_EXTRA_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([243, 122, 13, 200, 79, 143, 185, 145]);

export function getDepositStockpileExtraDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    DEPOSIT_STOCKPILE_EXTRA_DISCRIMINATOR
  );
}

export type DepositStockpileExtraInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountBoard extends string | AccountMeta<string> = string,
  TAccountStockpile extends string | AccountMeta<string> = string,
  TAccountStockpileExtras extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountExtraMint extends string | AccountMeta<string> = string,
  TAccountAdminSourceTokenAccount extends string | AccountMeta<string> = string,
  TAccountStockpileExtraTokenAccount extends
    | string
    | AccountMeta<string> = string,
  TAccountAssociatedTokenProgram extends
    | string
    | AccountMeta<string> = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBoard extends string
        ? ReadonlyAccount<TAccountBoard>
        : TAccountBoard,
      TAccountStockpile extends string
        ? WritableAccount<TAccountStockpile>
        : TAccountStockpile,
      TAccountStockpileExtras extends string
        ? WritableAccount<TAccountStockpileExtras>
        : TAccountStockpileExtras,
      TAccountTreasury extends string
        ? ReadonlyAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountExtraMint extends string
        ? ReadonlyAccount<TAccountExtraMint>
        : TAccountExtraMint,
      TAccountAdminSourceTokenAccount extends string
        ? WritableAccount<TAccountAdminSourceTokenAccount>
        : TAccountAdminSourceTokenAccount,
      TAccountStockpileExtraTokenAccount extends string
        ? WritableAccount<TAccountStockpileExtraTokenAccount>
        : TAccountStockpileExtraTokenAccount,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts
    ]
  >;

export type DepositStockpileExtraInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Raw token amount transferred into stockpile-extra custody. */
  amountRaw: bigint;
};

export type DepositStockpileExtraInstructionDataArgs = {
  /** Raw token amount transferred into stockpile-extra custody. */
  amountRaw: number | bigint;
};

export function getDepositStockpileExtraInstructionDataEncoder(): FixedSizeEncoder<DepositStockpileExtraInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amountRaw", getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: DEPOSIT_STOCKPILE_EXTRA_DISCRIMINATOR,
    })
  );
}

export function getDepositStockpileExtraInstructionDataDecoder(): FixedSizeDecoder<DepositStockpileExtraInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amountRaw", getU64Decoder()],
  ]);
}

export function getDepositStockpileExtraInstructionDataCodec(): FixedSizeCodec<
  DepositStockpileExtraInstructionDataArgs,
  DepositStockpileExtraInstructionData
> {
  return combineCodec(
    getDepositStockpileExtraInstructionDataEncoder(),
    getDepositStockpileExtraInstructionDataDecoder()
  );
}

export type DepositStockpileExtraAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
  TAccountStockpile extends string = string,
  TAccountStockpileExtras extends string = string,
  TAccountTreasury extends string = string,
  TAccountExtraMint extends string = string,
  TAccountAdminSourceTokenAccount extends string = string,
  TAccountStockpileExtraTokenAccount extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string
> = {
  /** Admin that funds the extra-prize deposit. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config containing the admin authority. */
  config?: Address<TAccountConfig>;
  /** Board used to ensure the targeted stockpile is the currently live cycle. */
  board?: Address<TAccountBoard>;
  /** Live stockpile receiving one additional SPL prize. */
  stockpile: Address<TAccountStockpile>;
  /** Singleton pending-extras account assigned to the live stockpile. */
  stockpileExtras?: Address<TAccountStockpileExtras>;
  /** Treasury PDA that owns the stockpile-extra custody accounts. */
  treasury?: Address<TAccountTreasury>;
  /** Classic SPL mint being deposited as an extra prize. */
  extraMint: Address<TAccountExtraMint>;
  /** Admin-owned source account funding the extra prize. */
  adminSourceTokenAccount: Address<TAccountAdminSourceTokenAccount>;
  stockpileExtraTokenAccount: Address<TAccountStockpileExtraTokenAccount>;
  /** Associated Token Program used to create the treasury ATA on demand. */
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  /** Classic SPL Token Program used by v1 stockpile extras. */
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  amountRaw: DepositStockpileExtraInstructionDataArgs["amountRaw"];
};

export async function getDepositStockpileExtraInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TAccountStockpile extends string,
  TAccountStockpileExtras extends string,
  TAccountTreasury extends string,
  TAccountExtraMint extends string,
  TAccountAdminSourceTokenAccount extends string,
  TAccountStockpileExtraTokenAccount extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: DepositStockpileExtraAsyncInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountBoard,
    TAccountStockpile,
    TAccountStockpileExtras,
    TAccountTreasury,
    TAccountExtraMint,
    TAccountAdminSourceTokenAccount,
    TAccountStockpileExtraTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  DepositStockpileExtraInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountBoard,
    TAccountStockpile,
    TAccountStockpileExtras,
    TAccountTreasury,
    TAccountExtraMint,
    TAccountAdminSourceTokenAccount,
    TAccountStockpileExtraTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    board: { value: input.board ?? null, isWritable: false },
    stockpile: { value: input.stockpile ?? null, isWritable: true },
    stockpileExtras: { value: input.stockpileExtras ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: false },
    extraMint: { value: input.extraMint ?? null, isWritable: false },
    adminSourceTokenAccount: {
      value: input.adminSourceTokenAccount ?? null,
      isWritable: true,
    },
    stockpileExtraTokenAccount: {
      value: input.stockpileExtraTokenAccount ?? null,
      isWritable: true,
    },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.board.value) {
    accounts.board.value = await findBoardPda();
  }
  if (!accounts.stockpileExtras.value) {
    accounts.stockpileExtras.value = await findStockpileExtrasPda();
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
      getAccountMeta("stockpile", accounts.stockpile),
      getAccountMeta("stockpileExtras", accounts.stockpileExtras),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("extraMint", accounts.extraMint),
      getAccountMeta(
        "adminSourceTokenAccount",
        accounts.adminSourceTokenAccount
      ),
      getAccountMeta(
        "stockpileExtraTokenAccount",
        accounts.stockpileExtraTokenAccount
      ),
      getAccountMeta("associatedTokenProgram", accounts.associatedTokenProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getDepositStockpileExtraInstructionDataEncoder().encode(
      args as DepositStockpileExtraInstructionDataArgs
    ),
    programAddress,
  } as DepositStockpileExtraInstruction<TProgramAddress, TAccountAdmin, TAccountConfig, TAccountBoard, TAccountStockpile, TAccountStockpileExtras, TAccountTreasury, TAccountExtraMint, TAccountAdminSourceTokenAccount, TAccountStockpileExtraTokenAccount, TAccountAssociatedTokenProgram, TAccountTokenProgram, TAccountSystemProgram>);
}

export type DepositStockpileExtraInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
  TAccountStockpile extends string = string,
  TAccountStockpileExtras extends string = string,
  TAccountTreasury extends string = string,
  TAccountExtraMint extends string = string,
  TAccountAdminSourceTokenAccount extends string = string,
  TAccountStockpileExtraTokenAccount extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string
> = {
  /** Admin that funds the extra-prize deposit. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config containing the admin authority. */
  config: Address<TAccountConfig>;
  /** Board used to ensure the targeted stockpile is the currently live cycle. */
  board: Address<TAccountBoard>;
  /** Live stockpile receiving one additional SPL prize. */
  stockpile: Address<TAccountStockpile>;
  /** Singleton pending-extras account assigned to the live stockpile. */
  stockpileExtras: Address<TAccountStockpileExtras>;
  /** Treasury PDA that owns the stockpile-extra custody accounts. */
  treasury: Address<TAccountTreasury>;
  /** Classic SPL mint being deposited as an extra prize. */
  extraMint: Address<TAccountExtraMint>;
  /** Admin-owned source account funding the extra prize. */
  adminSourceTokenAccount: Address<TAccountAdminSourceTokenAccount>;
  stockpileExtraTokenAccount: Address<TAccountStockpileExtraTokenAccount>;
  /** Associated Token Program used to create the treasury ATA on demand. */
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  /** Classic SPL Token Program used by v1 stockpile extras. */
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  amountRaw: DepositStockpileExtraInstructionDataArgs["amountRaw"];
};

export function getDepositStockpileExtraInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TAccountStockpile extends string,
  TAccountStockpileExtras extends string,
  TAccountTreasury extends string,
  TAccountExtraMint extends string,
  TAccountAdminSourceTokenAccount extends string,
  TAccountStockpileExtraTokenAccount extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: DepositStockpileExtraInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountBoard,
    TAccountStockpile,
    TAccountStockpileExtras,
    TAccountTreasury,
    TAccountExtraMint,
    TAccountAdminSourceTokenAccount,
    TAccountStockpileExtraTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): DepositStockpileExtraInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountConfig,
  TAccountBoard,
  TAccountStockpile,
  TAccountStockpileExtras,
  TAccountTreasury,
  TAccountExtraMint,
  TAccountAdminSourceTokenAccount,
  TAccountStockpileExtraTokenAccount,
  TAccountAssociatedTokenProgram,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    board: { value: input.board ?? null, isWritable: false },
    stockpile: { value: input.stockpile ?? null, isWritable: true },
    stockpileExtras: { value: input.stockpileExtras ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: false },
    extraMint: { value: input.extraMint ?? null, isWritable: false },
    adminSourceTokenAccount: {
      value: input.adminSourceTokenAccount ?? null,
      isWritable: true,
    },
    stockpileExtraTokenAccount: {
      value: input.stockpileExtraTokenAccount ?? null,
      isWritable: true,
    },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
      getAccountMeta("stockpile", accounts.stockpile),
      getAccountMeta("stockpileExtras", accounts.stockpileExtras),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("extraMint", accounts.extraMint),
      getAccountMeta(
        "adminSourceTokenAccount",
        accounts.adminSourceTokenAccount
      ),
      getAccountMeta(
        "stockpileExtraTokenAccount",
        accounts.stockpileExtraTokenAccount
      ),
      getAccountMeta("associatedTokenProgram", accounts.associatedTokenProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getDepositStockpileExtraInstructionDataEncoder().encode(
      args as DepositStockpileExtraInstructionDataArgs
    ),
    programAddress,
  } as DepositStockpileExtraInstruction<TProgramAddress, TAccountAdmin, TAccountConfig, TAccountBoard, TAccountStockpile, TAccountStockpileExtras, TAccountTreasury, TAccountExtraMint, TAccountAdminSourceTokenAccount, TAccountStockpileExtraTokenAccount, TAccountAssociatedTokenProgram, TAccountTokenProgram, TAccountSystemProgram>);
}

export type ParsedDepositStockpileExtraInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin that funds the extra-prize deposit. */
    admin: TAccountMetas[0];
    /** Global config containing the admin authority. */
    config: TAccountMetas[1];
    /** Board used to ensure the targeted stockpile is the currently live cycle. */
    board: TAccountMetas[2];
    /** Live stockpile receiving one additional SPL prize. */
    stockpile: TAccountMetas[3];
    /** Singleton pending-extras account assigned to the live stockpile. */
    stockpileExtras: TAccountMetas[4];
    /** Treasury PDA that owns the stockpile-extra custody accounts. */
    treasury: TAccountMetas[5];
    /** Classic SPL mint being deposited as an extra prize. */
    extraMint: TAccountMetas[6];
    /** Admin-owned source account funding the extra prize. */
    adminSourceTokenAccount: TAccountMetas[7];
    stockpileExtraTokenAccount: TAccountMetas[8];
    /** Associated Token Program used to create the treasury ATA on demand. */
    associatedTokenProgram: TAccountMetas[9];
    /** Classic SPL Token Program used by v1 stockpile extras. */
    tokenProgram: TAccountMetas[10];
    systemProgram: TAccountMetas[11];
  };
  data: DepositStockpileExtraInstructionData;
};

export function parseDepositStockpileExtraInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedDepositStockpileExtraInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 12,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      config: getNextAccount(),
      board: getNextAccount(),
      stockpile: getNextAccount(),
      stockpileExtras: getNextAccount(),
      treasury: getNextAccount(),
      extraMint: getNextAccount(),
      adminSourceTokenAccount: getNextAccount(),
      stockpileExtraTokenAccount: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getDepositStockpileExtraInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
