/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findAutoMinerSessionPda,
  findDeployRoundFromAutoSessionPlayerProfilePda,
} from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const INIT_AUTO_MINER_SESSION_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([242, 248, 89, 30, 189, 159, 59, 157]);

export function getInitAutoMinerSessionDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_AUTO_MINER_SESSION_DISCRIMINATOR,
  );
}

export type InitAutoMinerSessionInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountAutoMinerSession extends string | AccountMeta<string> = string,
  TAccountPlayerProfile extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? WritableSignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountAutoMinerSession extends string
        ? WritableAccount<TAccountAutoMinerSession>
        : TAccountAutoMinerSession,
      TAccountPlayerProfile extends string
        ? WritableAccount<TAccountPlayerProfile>
        : TAccountPlayerProfile,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitAutoMinerSessionInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Crank wallet allowed to execute auto deploys. */
  executor: Address;
  /** Gross lamports to deploy into each eligible round. */
  amountPerRound: bigint;
  /** Ephemeral public key used to encrypt the tile-pattern bits to the crank. */
  maskBitsEncryptionKey: ReadonlyUint8Array;
  /** Rescue CTR nonce used for the encrypted tile-pattern bits. */
  maskBitsNonce: bigint;
  /** Encrypted tile-pattern bits readable only by the configured crank. */
  maskBitsCiphertext: ReadonlyUint8Array;
  /** Crank encryption-key version used by the browser when encrypting the pattern. */
  maskBitsKeyVersion: number;
  /** Initial user-funded spendable budget. */
  initialBudget: bigint;
  /** Funding quote round count retained for compatibility; budget is the deploy limiter. */
  maxRounds: bigint;
  /** Optional last slot at which the session can still deploy. */
  expirySlot: Option<bigint>;
  /** Fixed lamport reimbursement paid to the crank after a successful deploy. */
  crankReimbursementLamports: bigint;
};

export type InitAutoMinerSessionInstructionDataArgs = {
  /** Crank wallet allowed to execute auto deploys. */
  executor: Address;
  /** Gross lamports to deploy into each eligible round. */
  amountPerRound: number | bigint;
  /** Ephemeral public key used to encrypt the tile-pattern bits to the crank. */
  maskBitsEncryptionKey: ReadonlyUint8Array;
  /** Rescue CTR nonce used for the encrypted tile-pattern bits. */
  maskBitsNonce: number | bigint;
  /** Encrypted tile-pattern bits readable only by the configured crank. */
  maskBitsCiphertext: ReadonlyUint8Array;
  /** Crank encryption-key version used by the browser when encrypting the pattern. */
  maskBitsKeyVersion: number;
  /** Initial user-funded spendable budget. */
  initialBudget: number | bigint;
  /** Funding quote round count retained for compatibility; budget is the deploy limiter. */
  maxRounds: number | bigint;
  /** Optional last slot at which the session can still deploy. */
  expirySlot: OptionOrNullable<number | bigint>;
  /** Fixed lamport reimbursement paid to the crank after a successful deploy. */
  crankReimbursementLamports: number | bigint;
};

export function getInitAutoMinerSessionInstructionDataEncoder(): Encoder<InitAutoMinerSessionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["executor", getAddressEncoder()],
      ["amountPerRound", getU64Encoder()],
      ["maskBitsEncryptionKey", fixEncoderSize(getBytesEncoder(), 32)],
      ["maskBitsNonce", getU128Encoder()],
      ["maskBitsCiphertext", fixEncoderSize(getBytesEncoder(), 32)],
      ["maskBitsKeyVersion", getU16Encoder()],
      ["initialBudget", getU64Encoder()],
      ["maxRounds", getU64Encoder()],
      ["expirySlot", getOptionEncoder(getU64Encoder())],
      ["crankReimbursementLamports", getU64Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INIT_AUTO_MINER_SESSION_DISCRIMINATOR,
    }),
  );
}

export function getInitAutoMinerSessionInstructionDataDecoder(): Decoder<InitAutoMinerSessionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["executor", getAddressDecoder()],
    ["amountPerRound", getU64Decoder()],
    ["maskBitsEncryptionKey", fixDecoderSize(getBytesDecoder(), 32)],
    ["maskBitsNonce", getU128Decoder()],
    ["maskBitsCiphertext", fixDecoderSize(getBytesDecoder(), 32)],
    ["maskBitsKeyVersion", getU16Decoder()],
    ["initialBudget", getU64Decoder()],
    ["maxRounds", getU64Decoder()],
    ["expirySlot", getOptionDecoder(getU64Decoder())],
    ["crankReimbursementLamports", getU64Decoder()],
  ]);
}

export function getInitAutoMinerSessionInstructionDataCodec(): Codec<
  InitAutoMinerSessionInstructionDataArgs,
  InitAutoMinerSessionInstructionData
> {
  return combineCodec(
    getInitAutoMinerSessionInstructionDataEncoder(),
    getInitAutoMinerSessionInstructionDataDecoder(),
  );
}

export type InitAutoMinerSessionAsyncInput<
  TAccountAuthority extends string = string,
  TAccountAutoMinerSession extends string = string,
  TAccountPlayerProfile extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Wallet that owns and funds the auto-miner session. */
  authority: TransactionSigner<TAccountAuthority>;
  /** Player-owned auto-miner session PDA. */
  autoMinerSession?: Address<TAccountAutoMinerSession>;
  /** Lifetime deploy profile for the auto-miner authority. */
  playerProfile?: Address<TAccountPlayerProfile>;
  /** System program used for account creation and budget transfer. */
  systemProgram?: Address<TAccountSystemProgram>;
  executor: InitAutoMinerSessionInstructionDataArgs["executor"];
  amountPerRound: InitAutoMinerSessionInstructionDataArgs["amountPerRound"];
  maskBitsEncryptionKey: InitAutoMinerSessionInstructionDataArgs["maskBitsEncryptionKey"];
  maskBitsNonce: InitAutoMinerSessionInstructionDataArgs["maskBitsNonce"];
  maskBitsCiphertext: InitAutoMinerSessionInstructionDataArgs["maskBitsCiphertext"];
  maskBitsKeyVersion: InitAutoMinerSessionInstructionDataArgs["maskBitsKeyVersion"];
  initialBudget: InitAutoMinerSessionInstructionDataArgs["initialBudget"];
  maxRounds: InitAutoMinerSessionInstructionDataArgs["maxRounds"];
  expirySlot: InitAutoMinerSessionInstructionDataArgs["expirySlot"];
  crankReimbursementLamports: InitAutoMinerSessionInstructionDataArgs["crankReimbursementLamports"];
};

export async function getInitAutoMinerSessionInstructionAsync<
  TAccountAuthority extends string,
  TAccountAutoMinerSession extends string,
  TAccountPlayerProfile extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: InitAutoMinerSessionAsyncInput<
    TAccountAuthority,
    TAccountAutoMinerSession,
    TAccountPlayerProfile,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitAutoMinerSessionInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountAutoMinerSession,
    TAccountPlayerProfile,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    autoMinerSession: {
      value: input.autoMinerSession ?? null,
      isWritable: true,
    },
    playerProfile: { value: input.playerProfile ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.autoMinerSession.value) {
    accounts.autoMinerSession.value = await findAutoMinerSessionPda({
      authority: getAddressFromResolvedInstructionAccount(
        "authority",
        accounts.authority.value,
      ),
    });
  }
  if (!accounts.playerProfile.value) {
    accounts.playerProfile.value =
      await findDeployRoundFromAutoSessionPlayerProfilePda({
        authority: getAddressFromResolvedInstructionAccount(
          "authority",
          accounts.authority.value,
        ),
      });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("autoMinerSession", accounts.autoMinerSession),
      getAccountMeta("playerProfile", accounts.playerProfile),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitAutoMinerSessionInstructionDataEncoder().encode(
      args as InitAutoMinerSessionInstructionDataArgs,
    ),
    programAddress,
  } as InitAutoMinerSessionInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountAutoMinerSession,
    TAccountPlayerProfile,
    TAccountSystemProgram
  >);
}

export type InitAutoMinerSessionInput<
  TAccountAuthority extends string = string,
  TAccountAutoMinerSession extends string = string,
  TAccountPlayerProfile extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Wallet that owns and funds the auto-miner session. */
  authority: TransactionSigner<TAccountAuthority>;
  /** Player-owned auto-miner session PDA. */
  autoMinerSession: Address<TAccountAutoMinerSession>;
  /** Lifetime deploy profile for the auto-miner authority. */
  playerProfile: Address<TAccountPlayerProfile>;
  /** System program used for account creation and budget transfer. */
  systemProgram?: Address<TAccountSystemProgram>;
  executor: InitAutoMinerSessionInstructionDataArgs["executor"];
  amountPerRound: InitAutoMinerSessionInstructionDataArgs["amountPerRound"];
  maskBitsEncryptionKey: InitAutoMinerSessionInstructionDataArgs["maskBitsEncryptionKey"];
  maskBitsNonce: InitAutoMinerSessionInstructionDataArgs["maskBitsNonce"];
  maskBitsCiphertext: InitAutoMinerSessionInstructionDataArgs["maskBitsCiphertext"];
  maskBitsKeyVersion: InitAutoMinerSessionInstructionDataArgs["maskBitsKeyVersion"];
  initialBudget: InitAutoMinerSessionInstructionDataArgs["initialBudget"];
  maxRounds: InitAutoMinerSessionInstructionDataArgs["maxRounds"];
  expirySlot: InitAutoMinerSessionInstructionDataArgs["expirySlot"];
  crankReimbursementLamports: InitAutoMinerSessionInstructionDataArgs["crankReimbursementLamports"];
};

export function getInitAutoMinerSessionInstruction<
  TAccountAuthority extends string,
  TAccountAutoMinerSession extends string,
  TAccountPlayerProfile extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: InitAutoMinerSessionInput<
    TAccountAuthority,
    TAccountAutoMinerSession,
    TAccountPlayerProfile,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitAutoMinerSessionInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountAutoMinerSession,
  TAccountPlayerProfile,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: true },
    autoMinerSession: {
      value: input.autoMinerSession ?? null,
      isWritable: true,
    },
    playerProfile: { value: input.playerProfile ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("autoMinerSession", accounts.autoMinerSession),
      getAccountMeta("playerProfile", accounts.playerProfile),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitAutoMinerSessionInstructionDataEncoder().encode(
      args as InitAutoMinerSessionInstructionDataArgs,
    ),
    programAddress,
  } as InitAutoMinerSessionInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountAutoMinerSession,
    TAccountPlayerProfile,
    TAccountSystemProgram
  >);
}

export type ParsedInitAutoMinerSessionInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Wallet that owns and funds the auto-miner session. */
    authority: TAccountMetas[0];
    /** Player-owned auto-miner session PDA. */
    autoMinerSession: TAccountMetas[1];
    /** Lifetime deploy profile for the auto-miner authority. */
    playerProfile: TAccountMetas[2];
    /** System program used for account creation and budget transfer. */
    systemProgram: TAccountMetas[3];
  };
  data: InitAutoMinerSessionInstructionData;
};

export function parseInitAutoMinerSessionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitAutoMinerSessionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 4,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      autoMinerSession: getNextAccount(),
      playerProfile: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitAutoMinerSessionInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
