/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { ZINC_PROGRAM_ADDRESS } from "../programs";
import {
  getSignedComputationOutputsInitRoundRandOutputDecoder,
  getSignedComputationOutputsInitRoundRandOutputEncoder,
  type SignedComputationOutputsInitRoundRandOutput,
  type SignedComputationOutputsInitRoundRandOutputArgs,
} from "../types";

export const INIT_ROUND_RAND_CALLBACK_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([192, 158, 104, 209, 71, 9, 24, 97]);

export function getInitRoundRandCallbackDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_ROUND_RAND_CALLBACK_DISCRIMINATOR
  );
}

export type InitRoundRandCallbackInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountArciumProgram extends
    | string
    | AccountMeta<string> = "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ",
  TAccountCompDefAccount extends string | AccountMeta<string> = string,
  TAccountMxeAccount extends string | AccountMeta<string> = string,
  TAccountComputationAccount extends string | AccountMeta<string> = string,
  TAccountClusterAccount extends string | AccountMeta<string> = string,
  TAccountInstructionsSysvar extends
    | string
    | AccountMeta<string> = "Sysvar1nstructions1111111111111111111111111",
  TAccountRound extends string | AccountMeta<string> = string,
  TAccountRoundSecret extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountArciumProgram extends string
        ? ReadonlyAccount<TAccountArciumProgram>
        : TAccountArciumProgram,
      TAccountCompDefAccount extends string
        ? ReadonlyAccount<TAccountCompDefAccount>
        : TAccountCompDefAccount,
      TAccountMxeAccount extends string
        ? ReadonlyAccount<TAccountMxeAccount>
        : TAccountMxeAccount,
      TAccountComputationAccount extends string
        ? ReadonlyAccount<TAccountComputationAccount>
        : TAccountComputationAccount,
      TAccountClusterAccount extends string
        ? ReadonlyAccount<TAccountClusterAccount>
        : TAccountClusterAccount,
      TAccountInstructionsSysvar extends string
        ? ReadonlyAccount<TAccountInstructionsSysvar>
        : TAccountInstructionsSysvar,
      TAccountRound extends string
        ? WritableAccount<TAccountRound>
        : TAccountRound,
      TAccountRoundSecret extends string
        ? WritableAccount<TAccountRoundSecret>
        : TAccountRoundSecret,
      ...TRemainingAccounts
    ]
  >;

export type InitRoundRandCallbackInstructionData = {
  discriminator: ReadonlyUint8Array;
  output: SignedComputationOutputsInitRoundRandOutput;
};

export type InitRoundRandCallbackInstructionDataArgs = {
  output: SignedComputationOutputsInitRoundRandOutputArgs;
};

export function getInitRoundRandCallbackInstructionDataEncoder(): Encoder<InitRoundRandCallbackInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["output", getSignedComputationOutputsInitRoundRandOutputEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INIT_ROUND_RAND_CALLBACK_DISCRIMINATOR,
    })
  );
}

export function getInitRoundRandCallbackInstructionDataDecoder(): Decoder<InitRoundRandCallbackInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["output", getSignedComputationOutputsInitRoundRandOutputDecoder()],
  ]);
}

export function getInitRoundRandCallbackInstructionDataCodec(): Codec<
  InitRoundRandCallbackInstructionDataArgs,
  InitRoundRandCallbackInstructionData
> {
  return combineCodec(
    getInitRoundRandCallbackInstructionDataEncoder(),
    getInitRoundRandCallbackInstructionDataDecoder()
  );
}

export type InitRoundRandCallbackInput<
  TAccountArciumProgram extends string = string,
  TAccountCompDefAccount extends string = string,
  TAccountMxeAccount extends string = string,
  TAccountComputationAccount extends string = string,
  TAccountClusterAccount extends string = string,
  TAccountInstructionsSysvar extends string = string,
  TAccountRound extends string = string,
  TAccountRoundSecret extends string = string
> = {
  arciumProgram?: Address<TAccountArciumProgram>;
  /** Computation definition used to verify the callback output. */
  compDefAccount: Address<TAccountCompDefAccount>;
  /** MXE account backing the encrypted computations for this program. */
  mxeAccount: Address<TAccountMxeAccount>;
  computationAccount: Address<TAccountComputationAccount>;
  /** Arcium cluster state used to verify the signed output. */
  clusterAccount: Address<TAccountClusterAccount>;
  instructionsSysvar?: Address<TAccountInstructionsSysvar>;
  /** Round being marked ready after entropy generation. */
  round: Address<TAccountRound>;
  /** Secret storage that receives the encrypted random output. */
  roundSecret: Address<TAccountRoundSecret>;
  output: InitRoundRandCallbackInstructionDataArgs["output"];
};

export function getInitRoundRandCallbackInstruction<
  TAccountArciumProgram extends string,
  TAccountCompDefAccount extends string,
  TAccountMxeAccount extends string,
  TAccountComputationAccount extends string,
  TAccountClusterAccount extends string,
  TAccountInstructionsSysvar extends string,
  TAccountRound extends string,
  TAccountRoundSecret extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: InitRoundRandCallbackInput<
    TAccountArciumProgram,
    TAccountCompDefAccount,
    TAccountMxeAccount,
    TAccountComputationAccount,
    TAccountClusterAccount,
    TAccountInstructionsSysvar,
    TAccountRound,
    TAccountRoundSecret
  >,
  config?: { programAddress?: TProgramAddress }
): InitRoundRandCallbackInstruction<
  TProgramAddress,
  TAccountArciumProgram,
  TAccountCompDefAccount,
  TAccountMxeAccount,
  TAccountComputationAccount,
  TAccountClusterAccount,
  TAccountInstructionsSysvar,
  TAccountRound,
  TAccountRoundSecret
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    arciumProgram: { value: input.arciumProgram ?? null, isWritable: false },
    compDefAccount: { value: input.compDefAccount ?? null, isWritable: false },
    mxeAccount: { value: input.mxeAccount ?? null, isWritable: false },
    computationAccount: {
      value: input.computationAccount ?? null,
      isWritable: false,
    },
    clusterAccount: { value: input.clusterAccount ?? null, isWritable: false },
    instructionsSysvar: {
      value: input.instructionsSysvar ?? null,
      isWritable: false,
    },
    round: { value: input.round ?? null, isWritable: true },
    roundSecret: { value: input.roundSecret ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.arciumProgram.value) {
    accounts.arciumProgram.value =
      "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ" as Address<"Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ">;
  }
  if (!accounts.instructionsSysvar.value) {
    accounts.instructionsSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("arciumProgram", accounts.arciumProgram),
      getAccountMeta("compDefAccount", accounts.compDefAccount),
      getAccountMeta("mxeAccount", accounts.mxeAccount),
      getAccountMeta("computationAccount", accounts.computationAccount),
      getAccountMeta("clusterAccount", accounts.clusterAccount),
      getAccountMeta("instructionsSysvar", accounts.instructionsSysvar),
      getAccountMeta("round", accounts.round),
      getAccountMeta("roundSecret", accounts.roundSecret),
    ],
    data: getInitRoundRandCallbackInstructionDataEncoder().encode(
      args as InitRoundRandCallbackInstructionDataArgs
    ),
    programAddress,
  } as InitRoundRandCallbackInstruction<TProgramAddress, TAccountArciumProgram, TAccountCompDefAccount, TAccountMxeAccount, TAccountComputationAccount, TAccountClusterAccount, TAccountInstructionsSysvar, TAccountRound, TAccountRoundSecret>);
}

export type ParsedInitRoundRandCallbackInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    arciumProgram: TAccountMetas[0];
    /** Computation definition used to verify the callback output. */
    compDefAccount: TAccountMetas[1];
    /** MXE account backing the encrypted computations for this program. */
    mxeAccount: TAccountMetas[2];
    computationAccount: TAccountMetas[3];
    /** Arcium cluster state used to verify the signed output. */
    clusterAccount: TAccountMetas[4];
    instructionsSysvar: TAccountMetas[5];
    /** Round being marked ready after entropy generation. */
    round: TAccountMetas[6];
    /** Secret storage that receives the encrypted random output. */
    roundSecret: TAccountMetas[7];
  };
  data: InitRoundRandCallbackInstructionData;
};

export function parseInitRoundRandCallbackInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitRoundRandCallbackInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 8,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      arciumProgram: getNextAccount(),
      compDefAccount: getNextAccount(),
      mxeAccount: getNextAccount(),
      computationAccount: getNextAccount(),
      clusterAccount: getNextAccount(),
      instructionsSysvar: getNextAccount(),
      round: getNextAccount(),
      roundSecret: getNextAccount(),
    },
    data: getInitRoundRandCallbackInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
