/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getNonNullResolvedInstructionInput,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findBoardPda,
  findConfigPda,
  findRoundPda,
  findRoundSecretPda,
  findSignPdaAccountPda,
  findTreasuryPda,
} from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const INIT_ROUND_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  147, 244, 62, 18, 218, 248, 44, 234,
]);

export function getInitRoundDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(INIT_ROUND_DISCRIMINATOR);
}

export type InitRoundInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountBoard extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountRound extends string | AccountMeta<string> = string,
  TAccountRoundSecret extends string | AccountMeta<string> = string,
  TAccountSignPdaAccount extends string | AccountMeta<string> = string,
  TAccountMxeAccount extends string | AccountMeta<string> = string,
  TAccountMempoolAccount extends string | AccountMeta<string> = string,
  TAccountExecutingPool extends string | AccountMeta<string> = string,
  TAccountComputationAccount extends string | AccountMeta<string> = string,
  TAccountCompDefAccount extends string | AccountMeta<string> = string,
  TAccountClusterAccount extends string | AccountMeta<string> = string,
  TAccountPoolAccount extends string | AccountMeta<string> =
    "G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC",
  TAccountClockAccount extends string | AccountMeta<string> =
    "7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountArciumProgram extends string | AccountMeta<string> =
    "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBoard extends string
        ? WritableAccount<TAccountBoard>
        : TAccountBoard,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountRound extends string
        ? WritableAccount<TAccountRound>
        : TAccountRound,
      TAccountRoundSecret extends string
        ? WritableAccount<TAccountRoundSecret>
        : TAccountRoundSecret,
      TAccountSignPdaAccount extends string
        ? WritableAccount<TAccountSignPdaAccount>
        : TAccountSignPdaAccount,
      TAccountMxeAccount extends string
        ? ReadonlyAccount<TAccountMxeAccount>
        : TAccountMxeAccount,
      TAccountMempoolAccount extends string
        ? WritableAccount<TAccountMempoolAccount>
        : TAccountMempoolAccount,
      TAccountExecutingPool extends string
        ? WritableAccount<TAccountExecutingPool>
        : TAccountExecutingPool,
      TAccountComputationAccount extends string
        ? WritableAccount<TAccountComputationAccount>
        : TAccountComputationAccount,
      TAccountCompDefAccount extends string
        ? ReadonlyAccount<TAccountCompDefAccount>
        : TAccountCompDefAccount,
      TAccountClusterAccount extends string
        ? WritableAccount<TAccountClusterAccount>
        : TAccountClusterAccount,
      TAccountPoolAccount extends string
        ? WritableAccount<TAccountPoolAccount>
        : TAccountPoolAccount,
      TAccountClockAccount extends string
        ? WritableAccount<TAccountClockAccount>
        : TAccountClockAccount,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountArciumProgram extends string
        ? ReadonlyAccount<TAccountArciumProgram>
        : TAccountArciumProgram,
      ...TRemainingAccounts,
    ]
  >;

export type InitRoundInstructionData = {
  discriminator: ReadonlyUint8Array;
  roundId: bigint;
  computationOffset: bigint;
};

export type InitRoundInstructionDataArgs = {
  roundId: number | bigint;
  computationOffset: number | bigint;
};

export function getInitRoundInstructionDataEncoder(): FixedSizeEncoder<InitRoundInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["roundId", getU64Encoder()],
      ["computationOffset", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: INIT_ROUND_DISCRIMINATOR }),
  );
}

export function getInitRoundInstructionDataDecoder(): FixedSizeDecoder<InitRoundInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["roundId", getU64Decoder()],
    ["computationOffset", getU64Decoder()],
  ]);
}

export function getInitRoundInstructionDataCodec(): FixedSizeCodec<
  InitRoundInstructionDataArgs,
  InitRoundInstructionData
> {
  return combineCodec(
    getInitRoundInstructionDataEncoder(),
    getInitRoundInstructionDataDecoder(),
  );
}

export type InitRoundAsyncInput<
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
  TAccountTreasury extends string = string,
  TAccountRound extends string = string,
  TAccountRoundSecret extends string = string,
  TAccountSignPdaAccount extends string = string,
  TAccountMxeAccount extends string = string,
  TAccountMempoolAccount extends string = string,
  TAccountExecutingPool extends string = string,
  TAccountComputationAccount extends string = string,
  TAccountCompDefAccount extends string = string,
  TAccountClusterAccount extends string = string,
  TAccountPoolAccount extends string = string,
  TAccountClockAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountArciumProgram extends string = string,
> = {
  /** Pays for the round accounts and Arcium queue transaction. */
  payer: TransactionSigner<TAccountPayer>;
  /** Global config that owns the crank authority. */
  config?: Address<TAccountConfig>;
  /** Tracks the active round, if any, and the next allocatable ID. */
  board?: Address<TAccountBoard>;
  /** Treasury PDA that may refill the crank before queueing Arcium work. */
  treasury?: Address<TAccountTreasury>;
  /** Newly allocated round account awaiting encrypted entropy. */
  round?: Address<TAccountRound>;
  /** Secret storage for the encrypted random value tied to this round. */
  roundSecret?: Address<TAccountRoundSecret>;
  /** Arcium signer PDA reused across queued computations. */
  signPdaAccount?: Address<TAccountSignPdaAccount>;
  /** MXE account backing the encrypted computations for this program. */
  mxeAccount: Address<TAccountMxeAccount>;
  mempoolAccount: Address<TAccountMempoolAccount>;
  executingPool: Address<TAccountExecutingPool>;
  computationAccount: Address<TAccountComputationAccount>;
  /** Computation definition for encrypted round entropy generation. */
  compDefAccount: Address<TAccountCompDefAccount>;
  /** Arcium cluster state referenced during queueing. */
  clusterAccount: Address<TAccountClusterAccount>;
  /** Fee pool used by Arcium for computation costs. */
  poolAccount?: Address<TAccountPoolAccount>;
  /** Arcium clock used for computation scheduling. */
  clockAccount?: Address<TAccountClockAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  arciumProgram?: Address<TAccountArciumProgram>;
  roundId: InitRoundInstructionDataArgs["roundId"];
  computationOffset: InitRoundInstructionDataArgs["computationOffset"];
};

export async function getInitRoundInstructionAsync<
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TAccountTreasury extends string,
  TAccountRound extends string,
  TAccountRoundSecret extends string,
  TAccountSignPdaAccount extends string,
  TAccountMxeAccount extends string,
  TAccountMempoolAccount extends string,
  TAccountExecutingPool extends string,
  TAccountComputationAccount extends string,
  TAccountCompDefAccount extends string,
  TAccountClusterAccount extends string,
  TAccountPoolAccount extends string,
  TAccountClockAccount extends string,
  TAccountSystemProgram extends string,
  TAccountArciumProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: InitRoundAsyncInput<
    TAccountPayer,
    TAccountConfig,
    TAccountBoard,
    TAccountTreasury,
    TAccountRound,
    TAccountRoundSecret,
    TAccountSignPdaAccount,
    TAccountMxeAccount,
    TAccountMempoolAccount,
    TAccountExecutingPool,
    TAccountComputationAccount,
    TAccountCompDefAccount,
    TAccountClusterAccount,
    TAccountPoolAccount,
    TAccountClockAccount,
    TAccountSystemProgram,
    TAccountArciumProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  InitRoundInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountConfig,
    TAccountBoard,
    TAccountTreasury,
    TAccountRound,
    TAccountRoundSecret,
    TAccountSignPdaAccount,
    TAccountMxeAccount,
    TAccountMempoolAccount,
    TAccountExecutingPool,
    TAccountComputationAccount,
    TAccountCompDefAccount,
    TAccountClusterAccount,
    TAccountPoolAccount,
    TAccountClockAccount,
    TAccountSystemProgram,
    TAccountArciumProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    board: { value: input.board ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    round: { value: input.round ?? null, isWritable: true },
    roundSecret: { value: input.roundSecret ?? null, isWritable: true },
    signPdaAccount: { value: input.signPdaAccount ?? null, isWritable: true },
    mxeAccount: { value: input.mxeAccount ?? null, isWritable: false },
    mempoolAccount: { value: input.mempoolAccount ?? null, isWritable: true },
    executingPool: { value: input.executingPool ?? null, isWritable: true },
    computationAccount: {
      value: input.computationAccount ?? null,
      isWritable: true,
    },
    compDefAccount: { value: input.compDefAccount ?? null, isWritable: false },
    clusterAccount: { value: input.clusterAccount ?? null, isWritable: true },
    poolAccount: { value: input.poolAccount ?? null, isWritable: true },
    clockAccount: { value: input.clockAccount ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    arciumProgram: { value: input.arciumProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.board.value) {
    accounts.board.value = await findBoardPda();
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.round.value) {
    accounts.round.value = await findRoundPda({
      roundId: getNonNullResolvedInstructionInput("roundId", args.roundId),
    });
  }
  if (!accounts.roundSecret.value) {
    accounts.roundSecret.value = await findRoundSecretPda({
      roundId: getNonNullResolvedInstructionInput("roundId", args.roundId),
    });
  }
  if (!accounts.signPdaAccount.value) {
    accounts.signPdaAccount.value = await findSignPdaAccountPda();
  }
  if (!accounts.poolAccount.value) {
    accounts.poolAccount.value =
      "G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC" as Address<"G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC">;
  }
  if (!accounts.clockAccount.value) {
    accounts.clockAccount.value =
      "7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot" as Address<"7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.arciumProgram.value) {
    accounts.arciumProgram.value =
      "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ" as Address<"Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("round", accounts.round),
      getAccountMeta("roundSecret", accounts.roundSecret),
      getAccountMeta("signPdaAccount", accounts.signPdaAccount),
      getAccountMeta("mxeAccount", accounts.mxeAccount),
      getAccountMeta("mempoolAccount", accounts.mempoolAccount),
      getAccountMeta("executingPool", accounts.executingPool),
      getAccountMeta("computationAccount", accounts.computationAccount),
      getAccountMeta("compDefAccount", accounts.compDefAccount),
      getAccountMeta("clusterAccount", accounts.clusterAccount),
      getAccountMeta("poolAccount", accounts.poolAccount),
      getAccountMeta("clockAccount", accounts.clockAccount),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("arciumProgram", accounts.arciumProgram),
    ],
    data: getInitRoundInstructionDataEncoder().encode(
      args as InitRoundInstructionDataArgs,
    ),
    programAddress,
  } as InitRoundInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountConfig,
    TAccountBoard,
    TAccountTreasury,
    TAccountRound,
    TAccountRoundSecret,
    TAccountSignPdaAccount,
    TAccountMxeAccount,
    TAccountMempoolAccount,
    TAccountExecutingPool,
    TAccountComputationAccount,
    TAccountCompDefAccount,
    TAccountClusterAccount,
    TAccountPoolAccount,
    TAccountClockAccount,
    TAccountSystemProgram,
    TAccountArciumProgram
  >);
}

export type InitRoundInput<
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
  TAccountTreasury extends string = string,
  TAccountRound extends string = string,
  TAccountRoundSecret extends string = string,
  TAccountSignPdaAccount extends string = string,
  TAccountMxeAccount extends string = string,
  TAccountMempoolAccount extends string = string,
  TAccountExecutingPool extends string = string,
  TAccountComputationAccount extends string = string,
  TAccountCompDefAccount extends string = string,
  TAccountClusterAccount extends string = string,
  TAccountPoolAccount extends string = string,
  TAccountClockAccount extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountArciumProgram extends string = string,
> = {
  /** Pays for the round accounts and Arcium queue transaction. */
  payer: TransactionSigner<TAccountPayer>;
  /** Global config that owns the crank authority. */
  config: Address<TAccountConfig>;
  /** Tracks the active round, if any, and the next allocatable ID. */
  board: Address<TAccountBoard>;
  /** Treasury PDA that may refill the crank before queueing Arcium work. */
  treasury: Address<TAccountTreasury>;
  /** Newly allocated round account awaiting encrypted entropy. */
  round: Address<TAccountRound>;
  /** Secret storage for the encrypted random value tied to this round. */
  roundSecret: Address<TAccountRoundSecret>;
  /** Arcium signer PDA reused across queued computations. */
  signPdaAccount: Address<TAccountSignPdaAccount>;
  /** MXE account backing the encrypted computations for this program. */
  mxeAccount: Address<TAccountMxeAccount>;
  mempoolAccount: Address<TAccountMempoolAccount>;
  executingPool: Address<TAccountExecutingPool>;
  computationAccount: Address<TAccountComputationAccount>;
  /** Computation definition for encrypted round entropy generation. */
  compDefAccount: Address<TAccountCompDefAccount>;
  /** Arcium cluster state referenced during queueing. */
  clusterAccount: Address<TAccountClusterAccount>;
  /** Fee pool used by Arcium for computation costs. */
  poolAccount?: Address<TAccountPoolAccount>;
  /** Arcium clock used for computation scheduling. */
  clockAccount?: Address<TAccountClockAccount>;
  systemProgram?: Address<TAccountSystemProgram>;
  arciumProgram?: Address<TAccountArciumProgram>;
  roundId: InitRoundInstructionDataArgs["roundId"];
  computationOffset: InitRoundInstructionDataArgs["computationOffset"];
};

export function getInitRoundInstruction<
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TAccountTreasury extends string,
  TAccountRound extends string,
  TAccountRoundSecret extends string,
  TAccountSignPdaAccount extends string,
  TAccountMxeAccount extends string,
  TAccountMempoolAccount extends string,
  TAccountExecutingPool extends string,
  TAccountComputationAccount extends string,
  TAccountCompDefAccount extends string,
  TAccountClusterAccount extends string,
  TAccountPoolAccount extends string,
  TAccountClockAccount extends string,
  TAccountSystemProgram extends string,
  TAccountArciumProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: InitRoundInput<
    TAccountPayer,
    TAccountConfig,
    TAccountBoard,
    TAccountTreasury,
    TAccountRound,
    TAccountRoundSecret,
    TAccountSignPdaAccount,
    TAccountMxeAccount,
    TAccountMempoolAccount,
    TAccountExecutingPool,
    TAccountComputationAccount,
    TAccountCompDefAccount,
    TAccountClusterAccount,
    TAccountPoolAccount,
    TAccountClockAccount,
    TAccountSystemProgram,
    TAccountArciumProgram
  >,
  config?: { programAddress?: TProgramAddress },
): InitRoundInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountConfig,
  TAccountBoard,
  TAccountTreasury,
  TAccountRound,
  TAccountRoundSecret,
  TAccountSignPdaAccount,
  TAccountMxeAccount,
  TAccountMempoolAccount,
  TAccountExecutingPool,
  TAccountComputationAccount,
  TAccountCompDefAccount,
  TAccountClusterAccount,
  TAccountPoolAccount,
  TAccountClockAccount,
  TAccountSystemProgram,
  TAccountArciumProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    board: { value: input.board ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    round: { value: input.round ?? null, isWritable: true },
    roundSecret: { value: input.roundSecret ?? null, isWritable: true },
    signPdaAccount: { value: input.signPdaAccount ?? null, isWritable: true },
    mxeAccount: { value: input.mxeAccount ?? null, isWritable: false },
    mempoolAccount: { value: input.mempoolAccount ?? null, isWritable: true },
    executingPool: { value: input.executingPool ?? null, isWritable: true },
    computationAccount: {
      value: input.computationAccount ?? null,
      isWritable: true,
    },
    compDefAccount: { value: input.compDefAccount ?? null, isWritable: false },
    clusterAccount: { value: input.clusterAccount ?? null, isWritable: true },
    poolAccount: { value: input.poolAccount ?? null, isWritable: true },
    clockAccount: { value: input.clockAccount ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    arciumProgram: { value: input.arciumProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.poolAccount.value) {
    accounts.poolAccount.value =
      "G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC" as Address<"G2sRWJvi3xoyh5k2gY49eG9L8YhAEWQPtNb1zb1GXTtC">;
  }
  if (!accounts.clockAccount.value) {
    accounts.clockAccount.value =
      "7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot" as Address<"7EbMUTLo5DjdzbN7s8BXeZwXzEwNQb1hScfRvWg8a6ot">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.arciumProgram.value) {
    accounts.arciumProgram.value =
      "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ" as Address<"Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("round", accounts.round),
      getAccountMeta("roundSecret", accounts.roundSecret),
      getAccountMeta("signPdaAccount", accounts.signPdaAccount),
      getAccountMeta("mxeAccount", accounts.mxeAccount),
      getAccountMeta("mempoolAccount", accounts.mempoolAccount),
      getAccountMeta("executingPool", accounts.executingPool),
      getAccountMeta("computationAccount", accounts.computationAccount),
      getAccountMeta("compDefAccount", accounts.compDefAccount),
      getAccountMeta("clusterAccount", accounts.clusterAccount),
      getAccountMeta("poolAccount", accounts.poolAccount),
      getAccountMeta("clockAccount", accounts.clockAccount),
      getAccountMeta("systemProgram", accounts.systemProgram),
      getAccountMeta("arciumProgram", accounts.arciumProgram),
    ],
    data: getInitRoundInstructionDataEncoder().encode(
      args as InitRoundInstructionDataArgs,
    ),
    programAddress,
  } as InitRoundInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountConfig,
    TAccountBoard,
    TAccountTreasury,
    TAccountRound,
    TAccountRoundSecret,
    TAccountSignPdaAccount,
    TAccountMxeAccount,
    TAccountMempoolAccount,
    TAccountExecutingPool,
    TAccountComputationAccount,
    TAccountCompDefAccount,
    TAccountClusterAccount,
    TAccountPoolAccount,
    TAccountClockAccount,
    TAccountSystemProgram,
    TAccountArciumProgram
  >);
}

export type ParsedInitRoundInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Pays for the round accounts and Arcium queue transaction. */
    payer: TAccountMetas[0];
    /** Global config that owns the crank authority. */
    config: TAccountMetas[1];
    /** Tracks the active round, if any, and the next allocatable ID. */
    board: TAccountMetas[2];
    /** Treasury PDA that may refill the crank before queueing Arcium work. */
    treasury: TAccountMetas[3];
    /** Newly allocated round account awaiting encrypted entropy. */
    round: TAccountMetas[4];
    /** Secret storage for the encrypted random value tied to this round. */
    roundSecret: TAccountMetas[5];
    /** Arcium signer PDA reused across queued computations. */
    signPdaAccount: TAccountMetas[6];
    /** MXE account backing the encrypted computations for this program. */
    mxeAccount: TAccountMetas[7];
    mempoolAccount: TAccountMetas[8];
    executingPool: TAccountMetas[9];
    computationAccount: TAccountMetas[10];
    /** Computation definition for encrypted round entropy generation. */
    compDefAccount: TAccountMetas[11];
    /** Arcium cluster state referenced during queueing. */
    clusterAccount: TAccountMetas[12];
    /** Fee pool used by Arcium for computation costs. */
    poolAccount: TAccountMetas[13];
    /** Arcium clock used for computation scheduling. */
    clockAccount: TAccountMetas[14];
    systemProgram: TAccountMetas[15];
    arciumProgram: TAccountMetas[16];
  };
  data: InitRoundInstructionData;
};

export function parseInitRoundInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedInitRoundInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 17) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 17,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      config: getNextAccount(),
      board: getNextAccount(),
      treasury: getNextAccount(),
      round: getNextAccount(),
      roundSecret: getNextAccount(),
      signPdaAccount: getNextAccount(),
      mxeAccount: getNextAccount(),
      mempoolAccount: getNextAccount(),
      executingPool: getNextAccount(),
      computationAccount: getNextAccount(),
      compDefAccount: getNextAccount(),
      clusterAccount: getNextAccount(),
      poolAccount: getNextAccount(),
      clockAccount: getNextAccount(),
      systemProgram: getNextAccount(),
      arciumProgram: getNextAccount(),
    },
    data: getInitRoundInstructionDataDecoder().decode(instruction.data),
  };
}
