/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findConfigPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";
import {
  getInitCompDefArgsDecoder,
  getInitCompDefArgsEncoder,
  type InitCompDefArgs,
  type InitCompDefArgsArgs,
} from "../types";

export const INIT_STOCKPILE_RAND_COMP_DEF_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([125, 176, 101, 247, 237, 176, 50, 211]);

export function getInitStockpileRandCompDefDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_STOCKPILE_RAND_COMP_DEF_DISCRIMINATOR
  );
}

export type InitStockpileRandCompDefInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountMxeAccount extends string | AccountMeta<string> = string,
  TAccountCompDefAccount extends string | AccountMeta<string> = string,
  TAccountAddressLookupTable extends string | AccountMeta<string> = string,
  TAccountLutProgram extends
    | string
    | AccountMeta<string> = "AddressLookupTab1e1111111111111111111111111",
  TAccountArciumProgram extends
    | string
    | AccountMeta<string> = "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ",
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountMxeAccount extends string
        ? WritableAccount<TAccountMxeAccount>
        : TAccountMxeAccount,
      TAccountCompDefAccount extends string
        ? WritableAccount<TAccountCompDefAccount>
        : TAccountCompDefAccount,
      TAccountAddressLookupTable extends string
        ? WritableAccount<TAccountAddressLookupTable>
        : TAccountAddressLookupTable,
      TAccountLutProgram extends string
        ? ReadonlyAccount<TAccountLutProgram>
        : TAccountLutProgram,
      TAccountArciumProgram extends string
        ? ReadonlyAccount<TAccountArciumProgram>
        : TAccountArciumProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts
    ]
  >;

export type InitStockpileRandCompDefInstructionData = {
  discriminator: ReadonlyUint8Array;
  args: InitCompDefArgs;
};

export type InitStockpileRandCompDefInstructionDataArgs = {
  args: InitCompDefArgsArgs;
};

export function getInitStockpileRandCompDefInstructionDataEncoder(): Encoder<InitStockpileRandCompDefInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["args", getInitCompDefArgsEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INIT_STOCKPILE_RAND_COMP_DEF_DISCRIMINATOR,
    })
  );
}

export function getInitStockpileRandCompDefInstructionDataDecoder(): Decoder<InitStockpileRandCompDefInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["args", getInitCompDefArgsDecoder()],
  ]);
}

export function getInitStockpileRandCompDefInstructionDataCodec(): Codec<
  InitStockpileRandCompDefInstructionDataArgs,
  InitStockpileRandCompDefInstructionData
> {
  return combineCodec(
    getInitStockpileRandCompDefInstructionDataEncoder(),
    getInitStockpileRandCompDefInstructionDataDecoder()
  );
}

export type InitStockpileRandCompDefAsyncInput<
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountMxeAccount extends string = string,
  TAccountCompDefAccount extends string = string,
  TAccountAddressLookupTable extends string = string,
  TAccountLutProgram extends string = string,
  TAccountArciumProgram extends string = string,
  TAccountSystemProgram extends string = string
> = {
  /** Pays for the computation-definition account initialization. */
  payer: TransactionSigner<TAccountPayer>;
  /** Global config containing the crank authority. */
  config?: Address<TAccountConfig>;
  /** MXE account for this program's encrypted circuits. */
  mxeAccount: Address<TAccountMxeAccount>;
  compDefAccount: Address<TAccountCompDefAccount>;
  addressLookupTable: Address<TAccountAddressLookupTable>;
  lutProgram?: Address<TAccountLutProgram>;
  arciumProgram?: Address<TAccountArciumProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  args: InitStockpileRandCompDefInstructionDataArgs["args"];
};

export async function getInitStockpileRandCompDefInstructionAsync<
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountMxeAccount extends string,
  TAccountCompDefAccount extends string,
  TAccountAddressLookupTable extends string,
  TAccountLutProgram extends string,
  TAccountArciumProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: InitStockpileRandCompDefAsyncInput<
    TAccountPayer,
    TAccountConfig,
    TAccountMxeAccount,
    TAccountCompDefAccount,
    TAccountAddressLookupTable,
    TAccountLutProgram,
    TAccountArciumProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  InitStockpileRandCompDefInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountConfig,
    TAccountMxeAccount,
    TAccountCompDefAccount,
    TAccountAddressLookupTable,
    TAccountLutProgram,
    TAccountArciumProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mxeAccount: { value: input.mxeAccount ?? null, isWritable: true },
    compDefAccount: { value: input.compDefAccount ?? null, isWritable: true },
    addressLookupTable: {
      value: input.addressLookupTable ?? null,
      isWritable: true,
    },
    lutProgram: { value: input.lutProgram ?? null, isWritable: false },
    arciumProgram: { value: input.arciumProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.lutProgram.value) {
    accounts.lutProgram.value =
      "AddressLookupTab1e1111111111111111111111111" as Address<"AddressLookupTab1e1111111111111111111111111">;
  }
  if (!accounts.arciumProgram.value) {
    accounts.arciumProgram.value =
      "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ" as Address<"Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("mxeAccount", accounts.mxeAccount),
      getAccountMeta("compDefAccount", accounts.compDefAccount),
      getAccountMeta("addressLookupTable", accounts.addressLookupTable),
      getAccountMeta("lutProgram", accounts.lutProgram),
      getAccountMeta("arciumProgram", accounts.arciumProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitStockpileRandCompDefInstructionDataEncoder().encode(
      args as InitStockpileRandCompDefInstructionDataArgs
    ),
    programAddress,
  } as InitStockpileRandCompDefInstruction<TProgramAddress, TAccountPayer, TAccountConfig, TAccountMxeAccount, TAccountCompDefAccount, TAccountAddressLookupTable, TAccountLutProgram, TAccountArciumProgram, TAccountSystemProgram>);
}

export type InitStockpileRandCompDefInput<
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountMxeAccount extends string = string,
  TAccountCompDefAccount extends string = string,
  TAccountAddressLookupTable extends string = string,
  TAccountLutProgram extends string = string,
  TAccountArciumProgram extends string = string,
  TAccountSystemProgram extends string = string
> = {
  /** Pays for the computation-definition account initialization. */
  payer: TransactionSigner<TAccountPayer>;
  /** Global config containing the crank authority. */
  config: Address<TAccountConfig>;
  /** MXE account for this program's encrypted circuits. */
  mxeAccount: Address<TAccountMxeAccount>;
  compDefAccount: Address<TAccountCompDefAccount>;
  addressLookupTable: Address<TAccountAddressLookupTable>;
  lutProgram?: Address<TAccountLutProgram>;
  arciumProgram?: Address<TAccountArciumProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  args: InitStockpileRandCompDefInstructionDataArgs["args"];
};

export function getInitStockpileRandCompDefInstruction<
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountMxeAccount extends string,
  TAccountCompDefAccount extends string,
  TAccountAddressLookupTable extends string,
  TAccountLutProgram extends string,
  TAccountArciumProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: InitStockpileRandCompDefInput<
    TAccountPayer,
    TAccountConfig,
    TAccountMxeAccount,
    TAccountCompDefAccount,
    TAccountAddressLookupTable,
    TAccountLutProgram,
    TAccountArciumProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): InitStockpileRandCompDefInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountConfig,
  TAccountMxeAccount,
  TAccountCompDefAccount,
  TAccountAddressLookupTable,
  TAccountLutProgram,
  TAccountArciumProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    mxeAccount: { value: input.mxeAccount ?? null, isWritable: true },
    compDefAccount: { value: input.compDefAccount ?? null, isWritable: true },
    addressLookupTable: {
      value: input.addressLookupTable ?? null,
      isWritable: true,
    },
    lutProgram: { value: input.lutProgram ?? null, isWritable: false },
    arciumProgram: { value: input.arciumProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.lutProgram.value) {
    accounts.lutProgram.value =
      "AddressLookupTab1e1111111111111111111111111" as Address<"AddressLookupTab1e1111111111111111111111111">;
  }
  if (!accounts.arciumProgram.value) {
    accounts.arciumProgram.value =
      "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ" as Address<"Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("payer", accounts.payer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("mxeAccount", accounts.mxeAccount),
      getAccountMeta("compDefAccount", accounts.compDefAccount),
      getAccountMeta("addressLookupTable", accounts.addressLookupTable),
      getAccountMeta("lutProgram", accounts.lutProgram),
      getAccountMeta("arciumProgram", accounts.arciumProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getInitStockpileRandCompDefInstructionDataEncoder().encode(
      args as InitStockpileRandCompDefInstructionDataArgs
    ),
    programAddress,
  } as InitStockpileRandCompDefInstruction<TProgramAddress, TAccountPayer, TAccountConfig, TAccountMxeAccount, TAccountCompDefAccount, TAccountAddressLookupTable, TAccountLutProgram, TAccountArciumProgram, TAccountSystemProgram>);
}

export type ParsedInitStockpileRandCompDefInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Pays for the computation-definition account initialization. */
    payer: TAccountMetas[0];
    /** Global config containing the crank authority. */
    config: TAccountMetas[1];
    /** MXE account for this program's encrypted circuits. */
    mxeAccount: TAccountMetas[2];
    compDefAccount: TAccountMetas[3];
    addressLookupTable: TAccountMetas[4];
    lutProgram: TAccountMetas[5];
    arciumProgram: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
  };
  data: InitStockpileRandCompDefInstructionData;
};

export function parseInitStockpileRandCompDefInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitStockpileRandCompDefInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 8,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      config: getNextAccount(),
      mxeAccount: getNextAccount(),
      compDefAccount: getNextAccount(),
      addressLookupTable: getNextAccount(),
      lutProgram: getNextAccount(),
      arciumProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getInitStockpileRandCompDefInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
