/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findBoardPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";
import {
  getSignedComputationOutputsInitStockpileRandOutputDecoder,
  getSignedComputationOutputsInitStockpileRandOutputEncoder,
  type SignedComputationOutputsInitStockpileRandOutput,
  type SignedComputationOutputsInitStockpileRandOutputArgs,
} from "../types";

export const INIT_STOCKPILE_RAND_CALLBACK_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([198, 198, 8, 119, 229, 69, 211, 83]);

export function getInitStockpileRandCallbackDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    INIT_STOCKPILE_RAND_CALLBACK_DISCRIMINATOR
  );
}

export type InitStockpileRandCallbackInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountArciumProgram extends
    | string
    | AccountMeta<string> = "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ",
  TAccountCompDefAccount extends string | AccountMeta<string> = string,
  TAccountMxeAccount extends string | AccountMeta<string> = string,
  TAccountComputationAccount extends string | AccountMeta<string> = string,
  TAccountClusterAccount extends string | AccountMeta<string> = string,
  TAccountInstructionsSysvar extends
    | string
    | AccountMeta<string> = "Sysvar1nstructions1111111111111111111111111",
  TAccountBoard extends string | AccountMeta<string> = string,
  TAccountStockpile extends string | AccountMeta<string> = string,
  TAccountStockpileSecret extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountArciumProgram extends string
        ? ReadonlyAccount<TAccountArciumProgram>
        : TAccountArciumProgram,
      TAccountCompDefAccount extends string
        ? ReadonlyAccount<TAccountCompDefAccount>
        : TAccountCompDefAccount,
      TAccountMxeAccount extends string
        ? ReadonlyAccount<TAccountMxeAccount>
        : TAccountMxeAccount,
      TAccountComputationAccount extends string
        ? ReadonlyAccount<TAccountComputationAccount>
        : TAccountComputationAccount,
      TAccountClusterAccount extends string
        ? ReadonlyAccount<TAccountClusterAccount>
        : TAccountClusterAccount,
      TAccountInstructionsSysvar extends string
        ? ReadonlyAccount<TAccountInstructionsSysvar>
        : TAccountInstructionsSysvar,
      TAccountBoard extends string
        ? WritableAccount<TAccountBoard>
        : TAccountBoard,
      TAccountStockpile extends string
        ? WritableAccount<TAccountStockpile>
        : TAccountStockpile,
      TAccountStockpileSecret extends string
        ? WritableAccount<TAccountStockpileSecret>
        : TAccountStockpileSecret,
      ...TRemainingAccounts
    ]
  >;

export type InitStockpileRandCallbackInstructionData = {
  discriminator: ReadonlyUint8Array;
  output: SignedComputationOutputsInitStockpileRandOutput;
};

export type InitStockpileRandCallbackInstructionDataArgs = {
  output: SignedComputationOutputsInitStockpileRandOutputArgs;
};

export function getInitStockpileRandCallbackInstructionDataEncoder(): Encoder<InitStockpileRandCallbackInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["output", getSignedComputationOutputsInitStockpileRandOutputEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: INIT_STOCKPILE_RAND_CALLBACK_DISCRIMINATOR,
    })
  );
}

export function getInitStockpileRandCallbackInstructionDataDecoder(): Decoder<InitStockpileRandCallbackInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["output", getSignedComputationOutputsInitStockpileRandOutputDecoder()],
  ]);
}

export function getInitStockpileRandCallbackInstructionDataCodec(): Codec<
  InitStockpileRandCallbackInstructionDataArgs,
  InitStockpileRandCallbackInstructionData
> {
  return combineCodec(
    getInitStockpileRandCallbackInstructionDataEncoder(),
    getInitStockpileRandCallbackInstructionDataDecoder()
  );
}

export type InitStockpileRandCallbackAsyncInput<
  TAccountArciumProgram extends string = string,
  TAccountCompDefAccount extends string = string,
  TAccountMxeAccount extends string = string,
  TAccountComputationAccount extends string = string,
  TAccountClusterAccount extends string = string,
  TAccountInstructionsSysvar extends string = string,
  TAccountBoard extends string = string,
  TAccountStockpile extends string = string,
  TAccountStockpileSecret extends string = string
> = {
  arciumProgram?: Address<TAccountArciumProgram>;
  /** Computation definition used to verify the callback output. */
  compDefAccount: Address<TAccountCompDefAccount>;
  /** MXE account backing the encrypted computations for this program. */
  mxeAccount: Address<TAccountMxeAccount>;
  computationAccount: Address<TAccountComputationAccount>;
  /** Arcium cluster state used to verify the signed output. */
  clusterAccount: Address<TAccountClusterAccount>;
  instructionsSysvar?: Address<TAccountInstructionsSysvar>;
  /** Board used to record the active stockpile id. */
  board?: Address<TAccountBoard>;
  /** Stockpile being opened after entropy generation. */
  stockpile: Address<TAccountStockpile>;
  /** Secret storage that receives the encrypted random output. */
  stockpileSecret: Address<TAccountStockpileSecret>;
  output: InitStockpileRandCallbackInstructionDataArgs["output"];
};

export async function getInitStockpileRandCallbackInstructionAsync<
  TAccountArciumProgram extends string,
  TAccountCompDefAccount extends string,
  TAccountMxeAccount extends string,
  TAccountComputationAccount extends string,
  TAccountClusterAccount extends string,
  TAccountInstructionsSysvar extends string,
  TAccountBoard extends string,
  TAccountStockpile extends string,
  TAccountStockpileSecret extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: InitStockpileRandCallbackAsyncInput<
    TAccountArciumProgram,
    TAccountCompDefAccount,
    TAccountMxeAccount,
    TAccountComputationAccount,
    TAccountClusterAccount,
    TAccountInstructionsSysvar,
    TAccountBoard,
    TAccountStockpile,
    TAccountStockpileSecret
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  InitStockpileRandCallbackInstruction<
    TProgramAddress,
    TAccountArciumProgram,
    TAccountCompDefAccount,
    TAccountMxeAccount,
    TAccountComputationAccount,
    TAccountClusterAccount,
    TAccountInstructionsSysvar,
    TAccountBoard,
    TAccountStockpile,
    TAccountStockpileSecret
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    arciumProgram: { value: input.arciumProgram ?? null, isWritable: false },
    compDefAccount: { value: input.compDefAccount ?? null, isWritable: false },
    mxeAccount: { value: input.mxeAccount ?? null, isWritable: false },
    computationAccount: {
      value: input.computationAccount ?? null,
      isWritable: false,
    },
    clusterAccount: { value: input.clusterAccount ?? null, isWritable: false },
    instructionsSysvar: {
      value: input.instructionsSysvar ?? null,
      isWritable: false,
    },
    board: { value: input.board ?? null, isWritable: true },
    stockpile: { value: input.stockpile ?? null, isWritable: true },
    stockpileSecret: { value: input.stockpileSecret ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.arciumProgram.value) {
    accounts.arciumProgram.value =
      "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ" as Address<"Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ">;
  }
  if (!accounts.instructionsSysvar.value) {
    accounts.instructionsSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }
  if (!accounts.board.value) {
    accounts.board.value = await findBoardPda();
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("arciumProgram", accounts.arciumProgram),
      getAccountMeta("compDefAccount", accounts.compDefAccount),
      getAccountMeta("mxeAccount", accounts.mxeAccount),
      getAccountMeta("computationAccount", accounts.computationAccount),
      getAccountMeta("clusterAccount", accounts.clusterAccount),
      getAccountMeta("instructionsSysvar", accounts.instructionsSysvar),
      getAccountMeta("board", accounts.board),
      getAccountMeta("stockpile", accounts.stockpile),
      getAccountMeta("stockpileSecret", accounts.stockpileSecret),
    ],
    data: getInitStockpileRandCallbackInstructionDataEncoder().encode(
      args as InitStockpileRandCallbackInstructionDataArgs
    ),
    programAddress,
  } as InitStockpileRandCallbackInstruction<TProgramAddress, TAccountArciumProgram, TAccountCompDefAccount, TAccountMxeAccount, TAccountComputationAccount, TAccountClusterAccount, TAccountInstructionsSysvar, TAccountBoard, TAccountStockpile, TAccountStockpileSecret>);
}

export type InitStockpileRandCallbackInput<
  TAccountArciumProgram extends string = string,
  TAccountCompDefAccount extends string = string,
  TAccountMxeAccount extends string = string,
  TAccountComputationAccount extends string = string,
  TAccountClusterAccount extends string = string,
  TAccountInstructionsSysvar extends string = string,
  TAccountBoard extends string = string,
  TAccountStockpile extends string = string,
  TAccountStockpileSecret extends string = string
> = {
  arciumProgram?: Address<TAccountArciumProgram>;
  /** Computation definition used to verify the callback output. */
  compDefAccount: Address<TAccountCompDefAccount>;
  /** MXE account backing the encrypted computations for this program. */
  mxeAccount: Address<TAccountMxeAccount>;
  computationAccount: Address<TAccountComputationAccount>;
  /** Arcium cluster state used to verify the signed output. */
  clusterAccount: Address<TAccountClusterAccount>;
  instructionsSysvar?: Address<TAccountInstructionsSysvar>;
  /** Board used to record the active stockpile id. */
  board: Address<TAccountBoard>;
  /** Stockpile being opened after entropy generation. */
  stockpile: Address<TAccountStockpile>;
  /** Secret storage that receives the encrypted random output. */
  stockpileSecret: Address<TAccountStockpileSecret>;
  output: InitStockpileRandCallbackInstructionDataArgs["output"];
};

export function getInitStockpileRandCallbackInstruction<
  TAccountArciumProgram extends string,
  TAccountCompDefAccount extends string,
  TAccountMxeAccount extends string,
  TAccountComputationAccount extends string,
  TAccountClusterAccount extends string,
  TAccountInstructionsSysvar extends string,
  TAccountBoard extends string,
  TAccountStockpile extends string,
  TAccountStockpileSecret extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: InitStockpileRandCallbackInput<
    TAccountArciumProgram,
    TAccountCompDefAccount,
    TAccountMxeAccount,
    TAccountComputationAccount,
    TAccountClusterAccount,
    TAccountInstructionsSysvar,
    TAccountBoard,
    TAccountStockpile,
    TAccountStockpileSecret
  >,
  config?: { programAddress?: TProgramAddress }
): InitStockpileRandCallbackInstruction<
  TProgramAddress,
  TAccountArciumProgram,
  TAccountCompDefAccount,
  TAccountMxeAccount,
  TAccountComputationAccount,
  TAccountClusterAccount,
  TAccountInstructionsSysvar,
  TAccountBoard,
  TAccountStockpile,
  TAccountStockpileSecret
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    arciumProgram: { value: input.arciumProgram ?? null, isWritable: false },
    compDefAccount: { value: input.compDefAccount ?? null, isWritable: false },
    mxeAccount: { value: input.mxeAccount ?? null, isWritable: false },
    computationAccount: {
      value: input.computationAccount ?? null,
      isWritable: false,
    },
    clusterAccount: { value: input.clusterAccount ?? null, isWritable: false },
    instructionsSysvar: {
      value: input.instructionsSysvar ?? null,
      isWritable: false,
    },
    board: { value: input.board ?? null, isWritable: true },
    stockpile: { value: input.stockpile ?? null, isWritable: true },
    stockpileSecret: { value: input.stockpileSecret ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.arciumProgram.value) {
    accounts.arciumProgram.value =
      "Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ" as Address<"Arcj82pX7HxYKLR92qvgZUAd7vGS1k4hQvAFcPATFdEQ">;
  }
  if (!accounts.instructionsSysvar.value) {
    accounts.instructionsSysvar.value =
      "Sysvar1nstructions1111111111111111111111111" as Address<"Sysvar1nstructions1111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("arciumProgram", accounts.arciumProgram),
      getAccountMeta("compDefAccount", accounts.compDefAccount),
      getAccountMeta("mxeAccount", accounts.mxeAccount),
      getAccountMeta("computationAccount", accounts.computationAccount),
      getAccountMeta("clusterAccount", accounts.clusterAccount),
      getAccountMeta("instructionsSysvar", accounts.instructionsSysvar),
      getAccountMeta("board", accounts.board),
      getAccountMeta("stockpile", accounts.stockpile),
      getAccountMeta("stockpileSecret", accounts.stockpileSecret),
    ],
    data: getInitStockpileRandCallbackInstructionDataEncoder().encode(
      args as InitStockpileRandCallbackInstructionDataArgs
    ),
    programAddress,
  } as InitStockpileRandCallbackInstruction<TProgramAddress, TAccountArciumProgram, TAccountCompDefAccount, TAccountMxeAccount, TAccountComputationAccount, TAccountClusterAccount, TAccountInstructionsSysvar, TAccountBoard, TAccountStockpile, TAccountStockpileSecret>);
}

export type ParsedInitStockpileRandCallbackInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    arciumProgram: TAccountMetas[0];
    /** Computation definition used to verify the callback output. */
    compDefAccount: TAccountMetas[1];
    /** MXE account backing the encrypted computations for this program. */
    mxeAccount: TAccountMetas[2];
    computationAccount: TAccountMetas[3];
    /** Arcium cluster state used to verify the signed output. */
    clusterAccount: TAccountMetas[4];
    instructionsSysvar: TAccountMetas[5];
    /** Board used to record the active stockpile id. */
    board: TAccountMetas[6];
    /** Stockpile being opened after entropy generation. */
    stockpile: TAccountMetas[7];
    /** Secret storage that receives the encrypted random output. */
    stockpileSecret: TAccountMetas[8];
  };
  data: InitStockpileRandCallbackInstructionData;
};

export function parseInitStockpileRandCallbackInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedInitStockpileRandCallbackInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      arciumProgram: getNextAccount(),
      compDefAccount: getNextAccount(),
      mxeAccount: getNextAccount(),
      computationAccount: getNextAccount(),
      clusterAccount: getNextAccount(),
      instructionsSysvar: getNextAccount(),
      board: getNextAccount(),
      stockpile: getNextAccount(),
      stockpileSecret: getNextAccount(),
    },
    data: getInitStockpileRandCallbackInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
