/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findBoardPda,
  findConfigPda,
  findPlayerProfilePda,
  findStakingRewardTokenAccountPda,
  findTreasuryPda,
} from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const JOIN_STOCKPILE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  62, 217, 82, 43, 3, 79, 57, 242,
]);

export function getJoinStockpileDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    JOIN_STOCKPILE_DISCRIMINATOR,
  );
}

export type JoinStockpileInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountBoard extends string | AccountMeta<string> = string,
  TAccountStockpile extends string | AccountMeta<string> = string,
  TAccountPlayerProfile extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountZincMint extends string | AccountMeta<string> = string,
  TAccountStockpileTokenAccount extends string | AccountMeta<string> = string,
  TAccountSignerZincTokenAccount extends string | AccountMeta<string> = string,
  TAccountStakingRewardTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBoard extends string
        ? ReadonlyAccount<TAccountBoard>
        : TAccountBoard,
      TAccountStockpile extends string
        ? WritableAccount<TAccountStockpile>
        : TAccountStockpile,
      TAccountPlayerProfile extends string
        ? WritableAccount<TAccountPlayerProfile>
        : TAccountPlayerProfile,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountZincMint extends string
        ? WritableAccount<TAccountZincMint>
        : TAccountZincMint,
      TAccountStockpileTokenAccount extends string
        ? WritableAccount<TAccountStockpileTokenAccount>
        : TAccountStockpileTokenAccount,
      TAccountSignerZincTokenAccount extends string
        ? WritableAccount<TAccountSignerZincTokenAccount>
        : TAccountSignerZincTokenAccount,
      TAccountStakingRewardTokenAccount extends string
        ? WritableAccount<TAccountStakingRewardTokenAccount>
        : TAccountStakingRewardTokenAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type JoinStockpileInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Spendable stockpile bricks committed to the current cycle, in `x10k` units. */
  bricksX10k: bigint;
};

export type JoinStockpileInstructionDataArgs = {
  /** Spendable stockpile bricks committed to the current cycle, in `x10k` units. */
  bricksX10k: number | bigint;
};

export function getJoinStockpileInstructionDataEncoder(): FixedSizeEncoder<JoinStockpileInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["bricksX10k", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: JOIN_STOCKPILE_DISCRIMINATOR }),
  );
}

export function getJoinStockpileInstructionDataDecoder(): FixedSizeDecoder<JoinStockpileInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["bricksX10k", getU64Decoder()],
  ]);
}

export function getJoinStockpileInstructionDataCodec(): FixedSizeCodec<
  JoinStockpileInstructionDataArgs,
  JoinStockpileInstructionData
> {
  return combineCodec(
    getJoinStockpileInstructionDataEncoder(),
    getJoinStockpileInstructionDataDecoder(),
  );
}

export type JoinStockpileAsyncInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
  TAccountStockpile extends string = string,
  TAccountPlayerProfile extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountStockpileTokenAccount extends string = string,
  TAccountSignerZincTokenAccount extends string = string,
  TAccountStakingRewardTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Player joining the currently open stockpile. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing stockpile rules. */
  config?: Address<TAccountConfig>;
  /** Board used to identify the current stockpile cycle. */
  board?: Address<TAccountBoard>;
  /** Open stockpile cycle receiving the player's bricks. */
  stockpile: Address<TAccountStockpile>;
  /** Lifetime profile storing historical and spendable stockpile bricks. */
  playerProfile?: Address<TAccountPlayerProfile>;
  /** Treasury account that owns global ZINC and staking accounting. */
  treasury?: Address<TAccountTreasury>;
  /** Protocol ZINC mint burned by the stockpile entry sink. */
  zincMint: Address<TAccountZincMint>;
  /** Live stockpile ZINC vault used to price the entry fee. */
  stockpileTokenAccount: Address<TAccountStockpileTokenAccount>;
  /** Signer-owned ZINC token account that funds the entry fee. */
  signerZincTokenAccount?: Address<TAccountSignerZincTokenAccount>;
  /** Treasury-owned reward vault that receives the staker share of the entry fee. */
  stakingRewardTokenAccount?: Address<TAccountStakingRewardTokenAccount>;
  /** SPL Token Program that owns the ZINC mint and vaults. */
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  bricksX10k: JoinStockpileInstructionDataArgs["bricksX10k"];
};

export async function getJoinStockpileInstructionAsync<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TAccountStockpile extends string,
  TAccountPlayerProfile extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountStockpileTokenAccount extends string,
  TAccountSignerZincTokenAccount extends string,
  TAccountStakingRewardTokenAccount extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: JoinStockpileAsyncInput<
    TAccountSigner,
    TAccountConfig,
    TAccountBoard,
    TAccountStockpile,
    TAccountPlayerProfile,
    TAccountTreasury,
    TAccountZincMint,
    TAccountStockpileTokenAccount,
    TAccountSignerZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  JoinStockpileInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountBoard,
    TAccountStockpile,
    TAccountPlayerProfile,
    TAccountTreasury,
    TAccountZincMint,
    TAccountStockpileTokenAccount,
    TAccountSignerZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    board: { value: input.board ?? null, isWritable: false },
    stockpile: { value: input.stockpile ?? null, isWritable: true },
    playerProfile: { value: input.playerProfile ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: true },
    stockpileTokenAccount: {
      value: input.stockpileTokenAccount ?? null,
      isWritable: true,
    },
    signerZincTokenAccount: {
      value: input.signerZincTokenAccount ?? null,
      isWritable: true,
    },
    stakingRewardTokenAccount: {
      value: input.stakingRewardTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.board.value) {
    accounts.board.value = await findBoardPda();
  }
  if (!accounts.playerProfile.value) {
    accounts.playerProfile.value = await findPlayerProfilePda({
      signer: getAddressFromResolvedInstructionAccount(
        "signer",
        accounts.signer.value,
      ),
    });
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.signerZincTokenAccount.value) {
    accounts.signerZincTokenAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "signer",
            accounts.signer.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "tokenProgram",
            accounts.tokenProgram.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "zincMint",
            accounts.zincMint.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.stakingRewardTokenAccount.value) {
    accounts.stakingRewardTokenAccount.value =
      await findStakingRewardTokenAccountPda();
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
      getAccountMeta("stockpile", accounts.stockpile),
      getAccountMeta("playerProfile", accounts.playerProfile),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("stockpileTokenAccount", accounts.stockpileTokenAccount),
      getAccountMeta("signerZincTokenAccount", accounts.signerZincTokenAccount),
      getAccountMeta(
        "stakingRewardTokenAccount",
        accounts.stakingRewardTokenAccount,
      ),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getJoinStockpileInstructionDataEncoder().encode(
      args as JoinStockpileInstructionDataArgs,
    ),
    programAddress,
  } as JoinStockpileInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountBoard,
    TAccountStockpile,
    TAccountPlayerProfile,
    TAccountTreasury,
    TAccountZincMint,
    TAccountStockpileTokenAccount,
    TAccountSignerZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type JoinStockpileInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
  TAccountStockpile extends string = string,
  TAccountPlayerProfile extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountStockpileTokenAccount extends string = string,
  TAccountSignerZincTokenAccount extends string = string,
  TAccountStakingRewardTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Player joining the currently open stockpile. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing stockpile rules. */
  config: Address<TAccountConfig>;
  /** Board used to identify the current stockpile cycle. */
  board: Address<TAccountBoard>;
  /** Open stockpile cycle receiving the player's bricks. */
  stockpile: Address<TAccountStockpile>;
  /** Lifetime profile storing historical and spendable stockpile bricks. */
  playerProfile: Address<TAccountPlayerProfile>;
  /** Treasury account that owns global ZINC and staking accounting. */
  treasury: Address<TAccountTreasury>;
  /** Protocol ZINC mint burned by the stockpile entry sink. */
  zincMint: Address<TAccountZincMint>;
  /** Live stockpile ZINC vault used to price the entry fee. */
  stockpileTokenAccount: Address<TAccountStockpileTokenAccount>;
  /** Signer-owned ZINC token account that funds the entry fee. */
  signerZincTokenAccount: Address<TAccountSignerZincTokenAccount>;
  /** Treasury-owned reward vault that receives the staker share of the entry fee. */
  stakingRewardTokenAccount: Address<TAccountStakingRewardTokenAccount>;
  /** SPL Token Program that owns the ZINC mint and vaults. */
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  bricksX10k: JoinStockpileInstructionDataArgs["bricksX10k"];
};

export function getJoinStockpileInstruction<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TAccountStockpile extends string,
  TAccountPlayerProfile extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountStockpileTokenAccount extends string,
  TAccountSignerZincTokenAccount extends string,
  TAccountStakingRewardTokenAccount extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: JoinStockpileInput<
    TAccountSigner,
    TAccountConfig,
    TAccountBoard,
    TAccountStockpile,
    TAccountPlayerProfile,
    TAccountTreasury,
    TAccountZincMint,
    TAccountStockpileTokenAccount,
    TAccountSignerZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): JoinStockpileInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountConfig,
  TAccountBoard,
  TAccountStockpile,
  TAccountPlayerProfile,
  TAccountTreasury,
  TAccountZincMint,
  TAccountStockpileTokenAccount,
  TAccountSignerZincTokenAccount,
  TAccountStakingRewardTokenAccount,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    board: { value: input.board ?? null, isWritable: false },
    stockpile: { value: input.stockpile ?? null, isWritable: true },
    playerProfile: { value: input.playerProfile ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: true },
    stockpileTokenAccount: {
      value: input.stockpileTokenAccount ?? null,
      isWritable: true,
    },
    signerZincTokenAccount: {
      value: input.signerZincTokenAccount ?? null,
      isWritable: true,
    },
    stakingRewardTokenAccount: {
      value: input.stakingRewardTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
      getAccountMeta("stockpile", accounts.stockpile),
      getAccountMeta("playerProfile", accounts.playerProfile),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("stockpileTokenAccount", accounts.stockpileTokenAccount),
      getAccountMeta("signerZincTokenAccount", accounts.signerZincTokenAccount),
      getAccountMeta(
        "stakingRewardTokenAccount",
        accounts.stakingRewardTokenAccount,
      ),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getJoinStockpileInstructionDataEncoder().encode(
      args as JoinStockpileInstructionDataArgs,
    ),
    programAddress,
  } as JoinStockpileInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountBoard,
    TAccountStockpile,
    TAccountPlayerProfile,
    TAccountTreasury,
    TAccountZincMint,
    TAccountStockpileTokenAccount,
    TAccountSignerZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedJoinStockpileInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Player joining the currently open stockpile. */
    signer: TAccountMetas[0];
    /** Global config containing stockpile rules. */
    config: TAccountMetas[1];
    /** Board used to identify the current stockpile cycle. */
    board: TAccountMetas[2];
    /** Open stockpile cycle receiving the player's bricks. */
    stockpile: TAccountMetas[3];
    /** Lifetime profile storing historical and spendable stockpile bricks. */
    playerProfile: TAccountMetas[4];
    /** Treasury account that owns global ZINC and staking accounting. */
    treasury: TAccountMetas[5];
    /** Protocol ZINC mint burned by the stockpile entry sink. */
    zincMint: TAccountMetas[6];
    /** Live stockpile ZINC vault used to price the entry fee. */
    stockpileTokenAccount: TAccountMetas[7];
    /** Signer-owned ZINC token account that funds the entry fee. */
    signerZincTokenAccount: TAccountMetas[8];
    /** Treasury-owned reward vault that receives the staker share of the entry fee. */
    stakingRewardTokenAccount: TAccountMetas[9];
    /** SPL Token Program that owns the ZINC mint and vaults. */
    tokenProgram: TAccountMetas[10];
    systemProgram: TAccountMetas[11];
  };
  data: JoinStockpileInstructionData;
};

export function parseJoinStockpileInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedJoinStockpileInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 12) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 12,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      config: getNextAccount(),
      board: getNextAccount(),
      stockpile: getNextAccount(),
      playerProfile: getNextAccount(),
      treasury: getNextAccount(),
      zincMint: getNextAccount(),
      stockpileTokenAccount: getNextAccount(),
      signerZincTokenAccount: getNextAccount(),
      stakingRewardTokenAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getJoinStockpileInstructionDataDecoder().decode(instruction.data),
  };
}
