/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findBuybackPoolPda, findConfigPda, findTreasuryPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const LOCK_BUYBACK_LIQUIDITY_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([232, 167, 111, 218, 205, 250, 130, 93]);

export function getLockBuybackLiquidityDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    LOCK_BUYBACK_LIQUIDITY_DISCRIMINATOR,
  );
}

export type LockBuybackLiquidityInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountBuybackPool extends string | AccountMeta<string> = string,
  TAccountPool extends string | AccountMeta<string> = string,
  TAccountPosition extends string | AccountMeta<string> = string,
  TAccountPositionNftAccount extends string | AccountMeta<string> = string,
  TAccountEventAuthority extends string | AccountMeta<string> = string,
  TAccountMeteoraProgram extends string | AccountMeta<string> =
    "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountTreasury extends string
        ? ReadonlyAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountBuybackPool extends string
        ? ReadonlyAccount<TAccountBuybackPool>
        : TAccountBuybackPool,
      TAccountPool extends string
        ? WritableAccount<TAccountPool>
        : TAccountPool,
      TAccountPosition extends string
        ? WritableAccount<TAccountPosition>
        : TAccountPosition,
      TAccountPositionNftAccount extends string
        ? ReadonlyAccount<TAccountPositionNftAccount>
        : TAccountPositionNftAccount,
      TAccountEventAuthority extends string
        ? ReadonlyAccount<TAccountEventAuthority>
        : TAccountEventAuthority,
      TAccountMeteoraProgram extends string
        ? ReadonlyAccount<TAccountMeteoraProgram>
        : TAccountMeteoraProgram,
      ...TRemainingAccounts,
    ]
  >;

export type LockBuybackLiquidityInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Liquidity amount to permanently lock from the stored Meteora position. */
  liquidityDelta: bigint;
};

export type LockBuybackLiquidityInstructionDataArgs = {
  /** Liquidity amount to permanently lock from the stored Meteora position. */
  liquidityDelta: number | bigint;
};

export function getLockBuybackLiquidityInstructionDataEncoder(): FixedSizeEncoder<LockBuybackLiquidityInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["liquidityDelta", getU128Encoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: LOCK_BUYBACK_LIQUIDITY_DISCRIMINATOR,
    }),
  );
}

export function getLockBuybackLiquidityInstructionDataDecoder(): FixedSizeDecoder<LockBuybackLiquidityInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["liquidityDelta", getU128Decoder()],
  ]);
}

export function getLockBuybackLiquidityInstructionDataCodec(): FixedSizeCodec<
  LockBuybackLiquidityInstructionDataArgs,
  LockBuybackLiquidityInstructionData
> {
  return combineCodec(
    getLockBuybackLiquidityInstructionDataEncoder(),
    getLockBuybackLiquidityInstructionDataDecoder(),
  );
}

export type LockBuybackLiquidityAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountTreasury extends string = string,
  TAccountBuybackPool extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountPositionNftAccount extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountMeteoraProgram extends string = string,
> = {
  /** Admin signer authorized to permanently lock protocol-owned LP principal. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config containing admin and treasury settings. */
  config?: Address<TAccountConfig>;
  /** Treasury PDA that owns the Meteora position NFT. */
  treasury?: Address<TAccountTreasury>;
  /** Stored Meteora buyback pool manifest. */
  buybackPool?: Address<TAccountBuybackPool>;
  pool: Address<TAccountPool>;
  position: Address<TAccountPosition>;
  positionNftAccount: Address<TAccountPositionNftAccount>;
  eventAuthority: Address<TAccountEventAuthority>;
  meteoraProgram?: Address<TAccountMeteoraProgram>;
  liquidityDelta: LockBuybackLiquidityInstructionDataArgs["liquidityDelta"];
};

export async function getLockBuybackLiquidityInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountTreasury extends string,
  TAccountBuybackPool extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountPositionNftAccount extends string,
  TAccountEventAuthority extends string,
  TAccountMeteoraProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: LockBuybackLiquidityAsyncInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountBuybackPool,
    TAccountPool,
    TAccountPosition,
    TAccountPositionNftAccount,
    TAccountEventAuthority,
    TAccountMeteoraProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  LockBuybackLiquidityInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountBuybackPool,
    TAccountPool,
    TAccountPosition,
    TAccountPositionNftAccount,
    TAccountEventAuthority,
    TAccountMeteoraProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: false },
    buybackPool: { value: input.buybackPool ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    positionNftAccount: {
      value: input.positionNftAccount ?? null,
      isWritable: false,
    },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    meteoraProgram: { value: input.meteoraProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.buybackPool.value) {
    accounts.buybackPool.value = await findBuybackPoolPda();
  }
  if (!accounts.meteoraProgram.value) {
    accounts.meteoraProgram.value =
      "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG" as Address<"cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("buybackPool", accounts.buybackPool),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("position", accounts.position),
      getAccountMeta("positionNftAccount", accounts.positionNftAccount),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("meteoraProgram", accounts.meteoraProgram),
    ],
    data: getLockBuybackLiquidityInstructionDataEncoder().encode(
      args as LockBuybackLiquidityInstructionDataArgs,
    ),
    programAddress,
  } as LockBuybackLiquidityInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountBuybackPool,
    TAccountPool,
    TAccountPosition,
    TAccountPositionNftAccount,
    TAccountEventAuthority,
    TAccountMeteoraProgram
  >);
}

export type LockBuybackLiquidityInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountTreasury extends string = string,
  TAccountBuybackPool extends string = string,
  TAccountPool extends string = string,
  TAccountPosition extends string = string,
  TAccountPositionNftAccount extends string = string,
  TAccountEventAuthority extends string = string,
  TAccountMeteoraProgram extends string = string,
> = {
  /** Admin signer authorized to permanently lock protocol-owned LP principal. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config containing admin and treasury settings. */
  config: Address<TAccountConfig>;
  /** Treasury PDA that owns the Meteora position NFT. */
  treasury: Address<TAccountTreasury>;
  /** Stored Meteora buyback pool manifest. */
  buybackPool: Address<TAccountBuybackPool>;
  pool: Address<TAccountPool>;
  position: Address<TAccountPosition>;
  positionNftAccount: Address<TAccountPositionNftAccount>;
  eventAuthority: Address<TAccountEventAuthority>;
  meteoraProgram?: Address<TAccountMeteoraProgram>;
  liquidityDelta: LockBuybackLiquidityInstructionDataArgs["liquidityDelta"];
};

export function getLockBuybackLiquidityInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountTreasury extends string,
  TAccountBuybackPool extends string,
  TAccountPool extends string,
  TAccountPosition extends string,
  TAccountPositionNftAccount extends string,
  TAccountEventAuthority extends string,
  TAccountMeteoraProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: LockBuybackLiquidityInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountBuybackPool,
    TAccountPool,
    TAccountPosition,
    TAccountPositionNftAccount,
    TAccountEventAuthority,
    TAccountMeteoraProgram
  >,
  config?: { programAddress?: TProgramAddress },
): LockBuybackLiquidityInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountConfig,
  TAccountTreasury,
  TAccountBuybackPool,
  TAccountPool,
  TAccountPosition,
  TAccountPositionNftAccount,
  TAccountEventAuthority,
  TAccountMeteoraProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: false },
    buybackPool: { value: input.buybackPool ?? null, isWritable: false },
    pool: { value: input.pool ?? null, isWritable: true },
    position: { value: input.position ?? null, isWritable: true },
    positionNftAccount: {
      value: input.positionNftAccount ?? null,
      isWritable: false,
    },
    eventAuthority: { value: input.eventAuthority ?? null, isWritable: false },
    meteoraProgram: { value: input.meteoraProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.meteoraProgram.value) {
    accounts.meteoraProgram.value =
      "cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG" as Address<"cpamdpZCGKUy5JxQXB4dcpGPiikHawvSWAd6mEn1sGG">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("buybackPool", accounts.buybackPool),
      getAccountMeta("pool", accounts.pool),
      getAccountMeta("position", accounts.position),
      getAccountMeta("positionNftAccount", accounts.positionNftAccount),
      getAccountMeta("eventAuthority", accounts.eventAuthority),
      getAccountMeta("meteoraProgram", accounts.meteoraProgram),
    ],
    data: getLockBuybackLiquidityInstructionDataEncoder().encode(
      args as LockBuybackLiquidityInstructionDataArgs,
    ),
    programAddress,
  } as LockBuybackLiquidityInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountBuybackPool,
    TAccountPool,
    TAccountPosition,
    TAccountPositionNftAccount,
    TAccountEventAuthority,
    TAccountMeteoraProgram
  >);
}

export type ParsedLockBuybackLiquidityInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin signer authorized to permanently lock protocol-owned LP principal. */
    admin: TAccountMetas[0];
    /** Global config containing admin and treasury settings. */
    config: TAccountMetas[1];
    /** Treasury PDA that owns the Meteora position NFT. */
    treasury: TAccountMetas[2];
    /** Stored Meteora buyback pool manifest. */
    buybackPool: TAccountMetas[3];
    pool: TAccountMetas[4];
    position: TAccountMetas[5];
    positionNftAccount: TAccountMetas[6];
    eventAuthority: TAccountMetas[7];
    meteoraProgram: TAccountMetas[8];
  };
  data: LockBuybackLiquidityInstructionData;
};

export function parseLockBuybackLiquidityInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedLockBuybackLiquidityInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 9,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      config: getNextAccount(),
      treasury: getNextAccount(),
      buybackPool: getNextAccount(),
      pool: getNextAccount(),
      position: getNextAccount(),
      positionNftAccount: getNextAccount(),
      eventAuthority: getNextAccount(),
      meteoraProgram: getNextAccount(),
    },
    data: getLockBuybackLiquidityInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
