/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findStakingRewardTokenAccountPda, findTreasuryPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const MELT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  42, 127, 85, 29, 150, 84, 21, 158,
]);

export function getMeltDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(MELT_DISCRIMINATOR);
}

export type MeltInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountZincMint extends string | AccountMeta<string> = string,
  TAccountSignerZincTokenAccount extends string | AccountMeta<string> = string,
  TAccountStakingRewardTokenAccount extends string | AccountMeta<string> =
    string,
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountZincMint extends string
        ? WritableAccount<TAccountZincMint>
        : TAccountZincMint,
      TAccountSignerZincTokenAccount extends string
        ? WritableAccount<TAccountSignerZincTokenAccount>
        : TAccountSignerZincTokenAccount,
      TAccountStakingRewardTokenAccount extends string
        ? WritableAccount<TAccountStakingRewardTokenAccount>
        : TAccountStakingRewardTokenAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      ...TRemainingAccounts,
    ]
  >;

export type MeltInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Raw ZINC amount to route through the shared melt sink. */
  amount: bigint;
};

export type MeltInstructionDataArgs = {
  /** Raw ZINC amount to route through the shared melt sink. */
  amount: number | bigint;
};

export function getMeltInstructionDataEncoder(): FixedSizeEncoder<MeltInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MELT_DISCRIMINATOR }),
  );
}

export function getMeltInstructionDataDecoder(): FixedSizeDecoder<MeltInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getMeltInstructionDataCodec(): FixedSizeCodec<
  MeltInstructionDataArgs,
  MeltInstructionData
> {
  return combineCodec(
    getMeltInstructionDataEncoder(),
    getMeltInstructionDataDecoder(),
  );
}

export type MeltAsyncInput<
  TAccountSigner extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountSignerZincTokenAccount extends string = string,
  TAccountStakingRewardTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Wallet that contributes ZINC into the shared melt sink. */
  signer: TransactionSigner<TAccountSigner>;
  /** Treasury PDA that owns global staking accounting. */
  treasury?: Address<TAccountTreasury>;
  /** Protocol ZINC mint. */
  zincMint: Address<TAccountZincMint>;
  /** Signer-owned ZINC token account that funds the melt. */
  signerZincTokenAccount?: Address<TAccountSignerZincTokenAccount>;
  /** Treasury-owned reward vault that receives the staker share. */
  stakingRewardTokenAccount?: Address<TAccountStakingRewardTokenAccount>;
  /** SPL Token Program that owns the ZINC mint and reward vault. */
  tokenProgram?: Address<TAccountTokenProgram>;
  amount: MeltInstructionDataArgs["amount"];
};

export async function getMeltInstructionAsync<
  TAccountSigner extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountSignerZincTokenAccount extends string,
  TAccountStakingRewardTokenAccount extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: MeltAsyncInput<
    TAccountSigner,
    TAccountTreasury,
    TAccountZincMint,
    TAccountSignerZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  MeltInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountTreasury,
    TAccountZincMint,
    TAccountSignerZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountTokenProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: true },
    signerZincTokenAccount: {
      value: input.signerZincTokenAccount ?? null,
      isWritable: true,
    },
    stakingRewardTokenAccount: {
      value: input.stakingRewardTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.signerZincTokenAccount.value) {
    accounts.signerZincTokenAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "signer",
            accounts.signer.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "tokenProgram",
            accounts.tokenProgram.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "zincMint",
            accounts.zincMint.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.stakingRewardTokenAccount.value) {
    accounts.stakingRewardTokenAccount.value =
      await findStakingRewardTokenAccountPda();
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("signerZincTokenAccount", accounts.signerZincTokenAccount),
      getAccountMeta(
        "stakingRewardTokenAccount",
        accounts.stakingRewardTokenAccount,
      ),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getMeltInstructionDataEncoder().encode(
      args as MeltInstructionDataArgs,
    ),
    programAddress,
  } as MeltInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountTreasury,
    TAccountZincMint,
    TAccountSignerZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountTokenProgram
  >);
}

export type MeltInput<
  TAccountSigner extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountSignerZincTokenAccount extends string = string,
  TAccountStakingRewardTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
> = {
  /** Wallet that contributes ZINC into the shared melt sink. */
  signer: TransactionSigner<TAccountSigner>;
  /** Treasury PDA that owns global staking accounting. */
  treasury: Address<TAccountTreasury>;
  /** Protocol ZINC mint. */
  zincMint: Address<TAccountZincMint>;
  /** Signer-owned ZINC token account that funds the melt. */
  signerZincTokenAccount: Address<TAccountSignerZincTokenAccount>;
  /** Treasury-owned reward vault that receives the staker share. */
  stakingRewardTokenAccount: Address<TAccountStakingRewardTokenAccount>;
  /** SPL Token Program that owns the ZINC mint and reward vault. */
  tokenProgram?: Address<TAccountTokenProgram>;
  amount: MeltInstructionDataArgs["amount"];
};

export function getMeltInstruction<
  TAccountSigner extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountSignerZincTokenAccount extends string,
  TAccountStakingRewardTokenAccount extends string,
  TAccountTokenProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: MeltInput<
    TAccountSigner,
    TAccountTreasury,
    TAccountZincMint,
    TAccountSignerZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountTokenProgram
  >,
  config?: { programAddress?: TProgramAddress },
): MeltInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountTreasury,
  TAccountZincMint,
  TAccountSignerZincTokenAccount,
  TAccountStakingRewardTokenAccount,
  TAccountTokenProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: true },
    signerZincTokenAccount: {
      value: input.signerZincTokenAccount ?? null,
      isWritable: true,
    },
    stakingRewardTokenAccount: {
      value: input.stakingRewardTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("signerZincTokenAccount", accounts.signerZincTokenAccount),
      getAccountMeta(
        "stakingRewardTokenAccount",
        accounts.stakingRewardTokenAccount,
      ),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
    ],
    data: getMeltInstructionDataEncoder().encode(
      args as MeltInstructionDataArgs,
    ),
    programAddress,
  } as MeltInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountTreasury,
    TAccountZincMint,
    TAccountSignerZincTokenAccount,
    TAccountStakingRewardTokenAccount,
    TAccountTokenProgram
  >);
}

export type ParsedMeltInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Wallet that contributes ZINC into the shared melt sink. */
    signer: TAccountMetas[0];
    /** Treasury PDA that owns global staking accounting. */
    treasury: TAccountMetas[1];
    /** Protocol ZINC mint. */
    zincMint: TAccountMetas[2];
    /** Signer-owned ZINC token account that funds the melt. */
    signerZincTokenAccount: TAccountMetas[3];
    /** Treasury-owned reward vault that receives the staker share. */
    stakingRewardTokenAccount: TAccountMetas[4];
    /** SPL Token Program that owns the ZINC mint and reward vault. */
    tokenProgram: TAccountMetas[5];
  };
  data: MeltInstructionData;
};

export function parseMeltInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedMeltInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      treasury: getNextAccount(),
      zincMint: getNextAccount(),
      signerZincTokenAccount: getNextAccount(),
      stakingRewardTokenAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
    },
    data: getMeltInstructionDataDecoder().decode(instruction.data),
  };
}
