/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findConfigPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const MIGRATE_BOARD_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  193, 200, 206, 200, 229, 146, 107, 47,
]);

export function getMigrateBoardDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    MIGRATE_BOARD_DISCRIMINATOR,
  );
}

export type MigrateBoardInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountBoard extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBoard extends string
        ? WritableAccount<TAccountBoard>
        : TAccountBoard,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type MigrateBoardInstructionData = { discriminator: ReadonlyUint8Array };

export type MigrateBoardInstructionDataArgs = {};

export function getMigrateBoardInstructionDataEncoder(): FixedSizeEncoder<MigrateBoardInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: MIGRATE_BOARD_DISCRIMINATOR }),
  );
}

export function getMigrateBoardInstructionDataDecoder(): FixedSizeDecoder<MigrateBoardInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getMigrateBoardInstructionDataCodec(): FixedSizeCodec<
  MigrateBoardInstructionDataArgs,
  MigrateBoardInstructionData
> {
  return combineCodec(
    getMigrateBoardInstructionDataEncoder(),
    getMigrateBoardInstructionDataDecoder(),
  );
}

export type MigrateBoardAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Admin signer that pays any rent increase and authorizes the migration. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config containing the admin authority. */
  config?: Address<TAccountConfig>;
  board: Address<TAccountBoard>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getMigrateBoardInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: MigrateBoardAsyncInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountBoard,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  MigrateBoardInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountBoard,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    board: { value: input.board ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getMigrateBoardInstructionDataEncoder().encode({}),
    programAddress,
  } as MigrateBoardInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountBoard,
    TAccountSystemProgram
  >);
}

export type MigrateBoardInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Admin signer that pays any rent increase and authorizes the migration. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config containing the admin authority. */
  config: Address<TAccountConfig>;
  board: Address<TAccountBoard>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getMigrateBoardInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: MigrateBoardInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountBoard,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): MigrateBoardInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountConfig,
  TAccountBoard,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    board: { value: input.board ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getMigrateBoardInstructionDataEncoder().encode({}),
    programAddress,
  } as MigrateBoardInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountBoard,
    TAccountSystemProgram
  >);
}

export type ParsedMigrateBoardInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin signer that pays any rent increase and authorizes the migration. */
    admin: TAccountMetas[0];
    /** Global config containing the admin authority. */
    config: TAccountMetas[1];
    board: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: MigrateBoardInstructionData;
};

export function parseMigrateBoardInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedMigrateBoardInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 4,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      config: getNextAccount(),
      board: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getMigrateBoardInstructionDataDecoder().decode(instruction.data),
  };
}
