/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findConfigPda, findTreasuryPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const MINT_ZINC_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  80, 143, 133, 161, 167, 234, 77, 127,
]);

export function getMintZincDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(MINT_ZINC_DISCRIMINATOR);
}

export type MintZincInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountZincMint extends string | AccountMeta<string> = string,
  TAccountAdminTokenAccount extends string | AccountMeta<string> = string,
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> =
    "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountZincMint extends string
        ? WritableAccount<TAccountZincMint>
        : TAccountZincMint,
      TAccountAdminTokenAccount extends string
        ? WritableAccount<TAccountAdminTokenAccount>
        : TAccountAdminTokenAccount,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type MintZincInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Raw base-unit ZINC amount to mint into the configured admin ATA. */
  amount: bigint;
};

export type MintZincInstructionDataArgs = {
  /** Raw base-unit ZINC amount to mint into the configured admin ATA. */
  amount: number | bigint;
};

export function getMintZincInstructionDataEncoder(): FixedSizeEncoder<MintZincInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MINT_ZINC_DISCRIMINATOR }),
  );
}

export function getMintZincInstructionDataDecoder(): FixedSizeDecoder<MintZincInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getMintZincInstructionDataCodec(): FixedSizeCodec<
  MintZincInstructionDataArgs,
  MintZincInstructionData
> {
  return combineCodec(
    getMintZincInstructionDataEncoder(),
    getMintZincInstructionDataDecoder(),
  );
}

export type MintZincAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountAdminTokenAccount extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Configured admin signer that receives the minted canonical ZINC. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config that authorizes the admin and supply cap. */
  config?: Address<TAccountConfig>;
  /** Treasury PDA that owns the canonical ZINC mint authority and lifetime accounting. */
  treasury?: Address<TAccountTreasury>;
  /** Protocol ZINC mint controlled by the treasury PDA. */
  zincMint: Address<TAccountZincMint>;
  /** Canonical admin ATA that receives the newly minted ZINC. */
  adminTokenAccount?: Address<TAccountAdminTokenAccount>;
  /** Associated Token Program used to create or validate the canonical admin ATA. */
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  /** SPL Token Program that owns the ZINC mint and destination ATA. */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** System Program used by ATA creation when the admin ATA is absent. */
  systemProgram?: Address<TAccountSystemProgram>;
  amount: MintZincInstructionDataArgs["amount"];
};

export async function getMintZincInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountAdminTokenAccount extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: MintZincAsyncInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountZincMint,
    TAccountAdminTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  MintZincInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountZincMint,
    TAccountAdminTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: true },
    adminTokenAccount: {
      value: input.adminTokenAccount ?? null,
      isWritable: true,
    },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.adminTokenAccount.value) {
    accounts.adminTokenAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "admin",
            accounts.admin.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "tokenProgram",
            accounts.tokenProgram.value,
          ),
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "zincMint",
            accounts.zincMint.value,
          ),
        ),
      ],
    });
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("adminTokenAccount", accounts.adminTokenAccount),
      getAccountMeta("associatedTokenProgram", accounts.associatedTokenProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getMintZincInstructionDataEncoder().encode(
      args as MintZincInstructionDataArgs,
    ),
    programAddress,
  } as MintZincInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountZincMint,
    TAccountAdminTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type MintZincInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountAdminTokenAccount extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Configured admin signer that receives the minted canonical ZINC. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config that authorizes the admin and supply cap. */
  config: Address<TAccountConfig>;
  /** Treasury PDA that owns the canonical ZINC mint authority and lifetime accounting. */
  treasury: Address<TAccountTreasury>;
  /** Protocol ZINC mint controlled by the treasury PDA. */
  zincMint: Address<TAccountZincMint>;
  /** Canonical admin ATA that receives the newly minted ZINC. */
  adminTokenAccount: Address<TAccountAdminTokenAccount>;
  /** Associated Token Program used to create or validate the canonical admin ATA. */
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  /** SPL Token Program that owns the ZINC mint and destination ATA. */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** System Program used by ATA creation when the admin ATA is absent. */
  systemProgram?: Address<TAccountSystemProgram>;
  amount: MintZincInstructionDataArgs["amount"];
};

export function getMintZincInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountAdminTokenAccount extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: MintZincInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountZincMint,
    TAccountAdminTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): MintZincInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountConfig,
  TAccountTreasury,
  TAccountZincMint,
  TAccountAdminTokenAccount,
  TAccountAssociatedTokenProgram,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: true },
    adminTokenAccount: {
      value: input.adminTokenAccount ?? null,
      isWritable: true,
    },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("adminTokenAccount", accounts.adminTokenAccount),
      getAccountMeta("associatedTokenProgram", accounts.associatedTokenProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getMintZincInstructionDataEncoder().encode(
      args as MintZincInstructionDataArgs,
    ),
    programAddress,
  } as MintZincInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountZincMint,
    TAccountAdminTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedMintZincInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Configured admin signer that receives the minted canonical ZINC. */
    admin: TAccountMetas[0];
    /** Global config that authorizes the admin and supply cap. */
    config: TAccountMetas[1];
    /** Treasury PDA that owns the canonical ZINC mint authority and lifetime accounting. */
    treasury: TAccountMetas[2];
    /** Protocol ZINC mint controlled by the treasury PDA. */
    zincMint: TAccountMetas[3];
    /** Canonical admin ATA that receives the newly minted ZINC. */
    adminTokenAccount: TAccountMetas[4];
    /** Associated Token Program used to create or validate the canonical admin ATA. */
    associatedTokenProgram: TAccountMetas[5];
    /** SPL Token Program that owns the ZINC mint and destination ATA. */
    tokenProgram: TAccountMetas[6];
    /** System Program used by ATA creation when the admin ATA is absent. */
    systemProgram: TAccountMetas[7];
  };
  data: MintZincInstructionData;
};

export function parseMintZincInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedMintZincInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 8,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      config: getNextAccount(),
      treasury: getNextAccount(),
      zincMint: getNextAccount(),
      adminTokenAccount: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getMintZincInstructionDataDecoder().decode(instruction.data),
  };
}
