/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findBoardPda,
  findConfigPda,
  findStockpileExtrasPda,
  findStockpileSolVaultPda,
  findTreasuryPda,
} from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const PAYOUT_STOCKPILE_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([150, 118, 163, 66, 221, 25, 36, 185]);

export function getPayoutStockpileDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PAYOUT_STOCKPILE_DISCRIMINATOR,
  );
}

export type PayoutStockpileInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountStockpile extends string | AccountMeta<string> = string,
  TAccountStockpileWinners extends string | AccountMeta<string> = string,
  TAccountStockpileExtras extends string | AccountMeta<string> = string,
  TAccountBoard extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountStockpileSolVault extends string | AccountMeta<string> = string,
  TAccountZincMint extends string | AccountMeta<string> = string,
  TAccountStockpileTokenAccount extends string | AccountMeta<string> = string,
  TAccountWinner extends string | AccountMeta<string> = string,
  TAccountWinnerZincTokenAccount extends string | AccountMeta<string> = string,
  TAccountAssociatedTokenProgram extends string | AccountMeta<string> =
    "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
  TAccountTokenProgram extends string | AccountMeta<string> =
    "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountStockpile extends string
        ? WritableAccount<TAccountStockpile>
        : TAccountStockpile,
      TAccountStockpileWinners extends string
        ? WritableAccount<TAccountStockpileWinners>
        : TAccountStockpileWinners,
      TAccountStockpileExtras extends string
        ? ReadonlyAccount<TAccountStockpileExtras>
        : TAccountStockpileExtras,
      TAccountBoard extends string
        ? WritableAccount<TAccountBoard>
        : TAccountBoard,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountStockpileSolVault extends string
        ? WritableAccount<TAccountStockpileSolVault>
        : TAccountStockpileSolVault,
      TAccountZincMint extends string
        ? ReadonlyAccount<TAccountZincMint>
        : TAccountZincMint,
      TAccountStockpileTokenAccount extends string
        ? WritableAccount<TAccountStockpileTokenAccount>
        : TAccountStockpileTokenAccount,
      TAccountWinner extends string
        ? WritableAccount<TAccountWinner>
        : TAccountWinner,
      TAccountWinnerZincTokenAccount extends string
        ? WritableAccount<TAccountWinnerZincTokenAccount>
        : TAccountWinnerZincTokenAccount,
      TAccountAssociatedTokenProgram extends string
        ? ReadonlyAccount<TAccountAssociatedTokenProgram>
        : TAccountAssociatedTokenProgram,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type PayoutStockpileInstructionData = {
  discriminator: ReadonlyUint8Array;
  rank: number;
};

export type PayoutStockpileInstructionDataArgs = { rank: number };

export function getPayoutStockpileInstructionDataEncoder(): FixedSizeEncoder<PayoutStockpileInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["rank", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: PAYOUT_STOCKPILE_DISCRIMINATOR }),
  );
}

export function getPayoutStockpileInstructionDataDecoder(): FixedSizeDecoder<PayoutStockpileInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["rank", getU8Decoder()],
  ]);
}

export function getPayoutStockpileInstructionDataCodec(): FixedSizeCodec<
  PayoutStockpileInstructionDataArgs,
  PayoutStockpileInstructionData
> {
  return combineCodec(
    getPayoutStockpileInstructionDataEncoder(),
    getPayoutStockpileInstructionDataDecoder(),
  );
}

export type PayoutStockpileAsyncInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountStockpile extends string = string,
  TAccountStockpileWinners extends string = string,
  TAccountStockpileExtras extends string = string,
  TAccountBoard extends string = string,
  TAccountTreasury extends string = string,
  TAccountStockpileSolVault extends string = string,
  TAccountZincMint extends string = string,
  TAccountStockpileTokenAccount extends string = string,
  TAccountWinner extends string = string,
  TAccountWinnerZincTokenAccount extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Crank signer that submits the payout transaction and pays ATA rent if needed. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing the crank authority. */
  config?: Address<TAccountConfig>;
  /** Revealed stockpile whose payout is being transferred. */
  stockpile: Address<TAccountStockpile>;
  stockpileWinners: Address<TAccountStockpileWinners>;
  /** Singleton pending-extras account tied to the unresolved stockpile cycle. */
  stockpileExtras?: Address<TAccountStockpileExtras>;
  /** Board used to enforce that only the unresolved stockpile can be paid. */
  board?: Address<TAccountBoard>;
  /** Treasury PDA that owns the stockpile SOL and ZINC payout inventory. */
  treasury?: Address<TAccountTreasury>;
  /** Program-owned lamport vault that funds stockpile SOL payouts. */
  stockpileSolVault?: Address<TAccountStockpileSolVault>;
  /** Protocol ZINC mint used for stockpile payouts. */
  zincMint: Address<TAccountZincMint>;
  /** Dedicated stockpile vault that funds ZINC stockpile payouts. */
  stockpileTokenAccount: Address<TAccountStockpileTokenAccount>;
  winner: Address<TAccountWinner>;
  winnerZincTokenAccount: Address<TAccountWinnerZincTokenAccount>;
  /** Associated Token Program used to create the winner ATA on demand. */
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  /** SPL Token Program that owns the ZINC mint and token accounts. */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** System Program used if the winner ATA needs to be created. */
  systemProgram?: Address<TAccountSystemProgram>;
  rank: PayoutStockpileInstructionDataArgs["rank"];
};

export async function getPayoutStockpileInstructionAsync<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountStockpile extends string,
  TAccountStockpileWinners extends string,
  TAccountStockpileExtras extends string,
  TAccountBoard extends string,
  TAccountTreasury extends string,
  TAccountStockpileSolVault extends string,
  TAccountZincMint extends string,
  TAccountStockpileTokenAccount extends string,
  TAccountWinner extends string,
  TAccountWinnerZincTokenAccount extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: PayoutStockpileAsyncInput<
    TAccountSigner,
    TAccountConfig,
    TAccountStockpile,
    TAccountStockpileWinners,
    TAccountStockpileExtras,
    TAccountBoard,
    TAccountTreasury,
    TAccountStockpileSolVault,
    TAccountZincMint,
    TAccountStockpileTokenAccount,
    TAccountWinner,
    TAccountWinnerZincTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  PayoutStockpileInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountStockpile,
    TAccountStockpileWinners,
    TAccountStockpileExtras,
    TAccountBoard,
    TAccountTreasury,
    TAccountStockpileSolVault,
    TAccountZincMint,
    TAccountStockpileTokenAccount,
    TAccountWinner,
    TAccountWinnerZincTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    stockpile: { value: input.stockpile ?? null, isWritable: true },
    stockpileWinners: {
      value: input.stockpileWinners ?? null,
      isWritable: true,
    },
    stockpileExtras: {
      value: input.stockpileExtras ?? null,
      isWritable: false,
    },
    board: { value: input.board ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    stockpileSolVault: {
      value: input.stockpileSolVault ?? null,
      isWritable: true,
    },
    zincMint: { value: input.zincMint ?? null, isWritable: false },
    stockpileTokenAccount: {
      value: input.stockpileTokenAccount ?? null,
      isWritable: true,
    },
    winner: { value: input.winner ?? null, isWritable: true },
    winnerZincTokenAccount: {
      value: input.winnerZincTokenAccount ?? null,
      isWritable: true,
    },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.stockpileExtras.value) {
    accounts.stockpileExtras.value = await findStockpileExtrasPda();
  }
  if (!accounts.board.value) {
    accounts.board.value = await findBoardPda();
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.stockpileSolVault.value) {
    accounts.stockpileSolVault.value = await findStockpileSolVaultPda();
  }
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("stockpile", accounts.stockpile),
      getAccountMeta("stockpileWinners", accounts.stockpileWinners),
      getAccountMeta("stockpileExtras", accounts.stockpileExtras),
      getAccountMeta("board", accounts.board),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("stockpileSolVault", accounts.stockpileSolVault),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("stockpileTokenAccount", accounts.stockpileTokenAccount),
      getAccountMeta("winner", accounts.winner),
      getAccountMeta("winnerZincTokenAccount", accounts.winnerZincTokenAccount),
      getAccountMeta("associatedTokenProgram", accounts.associatedTokenProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getPayoutStockpileInstructionDataEncoder().encode(
      args as PayoutStockpileInstructionDataArgs,
    ),
    programAddress,
  } as PayoutStockpileInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountStockpile,
    TAccountStockpileWinners,
    TAccountStockpileExtras,
    TAccountBoard,
    TAccountTreasury,
    TAccountStockpileSolVault,
    TAccountZincMint,
    TAccountStockpileTokenAccount,
    TAccountWinner,
    TAccountWinnerZincTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type PayoutStockpileInput<
  TAccountSigner extends string = string,
  TAccountConfig extends string = string,
  TAccountStockpile extends string = string,
  TAccountStockpileWinners extends string = string,
  TAccountStockpileExtras extends string = string,
  TAccountBoard extends string = string,
  TAccountTreasury extends string = string,
  TAccountStockpileSolVault extends string = string,
  TAccountZincMint extends string = string,
  TAccountStockpileTokenAccount extends string = string,
  TAccountWinner extends string = string,
  TAccountWinnerZincTokenAccount extends string = string,
  TAccountAssociatedTokenProgram extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Crank signer that submits the payout transaction and pays ATA rent if needed. */
  signer: TransactionSigner<TAccountSigner>;
  /** Global config containing the crank authority. */
  config: Address<TAccountConfig>;
  /** Revealed stockpile whose payout is being transferred. */
  stockpile: Address<TAccountStockpile>;
  stockpileWinners: Address<TAccountStockpileWinners>;
  /** Singleton pending-extras account tied to the unresolved stockpile cycle. */
  stockpileExtras: Address<TAccountStockpileExtras>;
  /** Board used to enforce that only the unresolved stockpile can be paid. */
  board: Address<TAccountBoard>;
  /** Treasury PDA that owns the stockpile SOL and ZINC payout inventory. */
  treasury: Address<TAccountTreasury>;
  /** Program-owned lamport vault that funds stockpile SOL payouts. */
  stockpileSolVault: Address<TAccountStockpileSolVault>;
  /** Protocol ZINC mint used for stockpile payouts. */
  zincMint: Address<TAccountZincMint>;
  /** Dedicated stockpile vault that funds ZINC stockpile payouts. */
  stockpileTokenAccount: Address<TAccountStockpileTokenAccount>;
  winner: Address<TAccountWinner>;
  winnerZincTokenAccount: Address<TAccountWinnerZincTokenAccount>;
  /** Associated Token Program used to create the winner ATA on demand. */
  associatedTokenProgram?: Address<TAccountAssociatedTokenProgram>;
  /** SPL Token Program that owns the ZINC mint and token accounts. */
  tokenProgram?: Address<TAccountTokenProgram>;
  /** System Program used if the winner ATA needs to be created. */
  systemProgram?: Address<TAccountSystemProgram>;
  rank: PayoutStockpileInstructionDataArgs["rank"];
};

export function getPayoutStockpileInstruction<
  TAccountSigner extends string,
  TAccountConfig extends string,
  TAccountStockpile extends string,
  TAccountStockpileWinners extends string,
  TAccountStockpileExtras extends string,
  TAccountBoard extends string,
  TAccountTreasury extends string,
  TAccountStockpileSolVault extends string,
  TAccountZincMint extends string,
  TAccountStockpileTokenAccount extends string,
  TAccountWinner extends string,
  TAccountWinnerZincTokenAccount extends string,
  TAccountAssociatedTokenProgram extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: PayoutStockpileInput<
    TAccountSigner,
    TAccountConfig,
    TAccountStockpile,
    TAccountStockpileWinners,
    TAccountStockpileExtras,
    TAccountBoard,
    TAccountTreasury,
    TAccountStockpileSolVault,
    TAccountZincMint,
    TAccountStockpileTokenAccount,
    TAccountWinner,
    TAccountWinnerZincTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): PayoutStockpileInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountConfig,
  TAccountStockpile,
  TAccountStockpileWinners,
  TAccountStockpileExtras,
  TAccountBoard,
  TAccountTreasury,
  TAccountStockpileSolVault,
  TAccountZincMint,
  TAccountStockpileTokenAccount,
  TAccountWinner,
  TAccountWinnerZincTokenAccount,
  TAccountAssociatedTokenProgram,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    stockpile: { value: input.stockpile ?? null, isWritable: true },
    stockpileWinners: {
      value: input.stockpileWinners ?? null,
      isWritable: true,
    },
    stockpileExtras: {
      value: input.stockpileExtras ?? null,
      isWritable: false,
    },
    board: { value: input.board ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    stockpileSolVault: {
      value: input.stockpileSolVault ?? null,
      isWritable: true,
    },
    zincMint: { value: input.zincMint ?? null, isWritable: false },
    stockpileTokenAccount: {
      value: input.stockpileTokenAccount ?? null,
      isWritable: true,
    },
    winner: { value: input.winner ?? null, isWritable: true },
    winnerZincTokenAccount: {
      value: input.winnerZincTokenAccount ?? null,
      isWritable: true,
    },
    associatedTokenProgram: {
      value: input.associatedTokenProgram ?? null,
      isWritable: false,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.associatedTokenProgram.value) {
    accounts.associatedTokenProgram.value =
      "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">;
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("config", accounts.config),
      getAccountMeta("stockpile", accounts.stockpile),
      getAccountMeta("stockpileWinners", accounts.stockpileWinners),
      getAccountMeta("stockpileExtras", accounts.stockpileExtras),
      getAccountMeta("board", accounts.board),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("stockpileSolVault", accounts.stockpileSolVault),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("stockpileTokenAccount", accounts.stockpileTokenAccount),
      getAccountMeta("winner", accounts.winner),
      getAccountMeta("winnerZincTokenAccount", accounts.winnerZincTokenAccount),
      getAccountMeta("associatedTokenProgram", accounts.associatedTokenProgram),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getPayoutStockpileInstructionDataEncoder().encode(
      args as PayoutStockpileInstructionDataArgs,
    ),
    programAddress,
  } as PayoutStockpileInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountConfig,
    TAccountStockpile,
    TAccountStockpileWinners,
    TAccountStockpileExtras,
    TAccountBoard,
    TAccountTreasury,
    TAccountStockpileSolVault,
    TAccountZincMint,
    TAccountStockpileTokenAccount,
    TAccountWinner,
    TAccountWinnerZincTokenAccount,
    TAccountAssociatedTokenProgram,
    TAccountTokenProgram,
    TAccountSystemProgram
  >);
}

export type ParsedPayoutStockpileInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Crank signer that submits the payout transaction and pays ATA rent if needed. */
    signer: TAccountMetas[0];
    /** Global config containing the crank authority. */
    config: TAccountMetas[1];
    /** Revealed stockpile whose payout is being transferred. */
    stockpile: TAccountMetas[2];
    stockpileWinners: TAccountMetas[3];
    /** Singleton pending-extras account tied to the unresolved stockpile cycle. */
    stockpileExtras: TAccountMetas[4];
    /** Board used to enforce that only the unresolved stockpile can be paid. */
    board: TAccountMetas[5];
    /** Treasury PDA that owns the stockpile SOL and ZINC payout inventory. */
    treasury: TAccountMetas[6];
    /** Program-owned lamport vault that funds stockpile SOL payouts. */
    stockpileSolVault: TAccountMetas[7];
    /** Protocol ZINC mint used for stockpile payouts. */
    zincMint: TAccountMetas[8];
    /** Dedicated stockpile vault that funds ZINC stockpile payouts. */
    stockpileTokenAccount: TAccountMetas[9];
    winner: TAccountMetas[10];
    winnerZincTokenAccount: TAccountMetas[11];
    /** Associated Token Program used to create the winner ATA on demand. */
    associatedTokenProgram: TAccountMetas[12];
    /** SPL Token Program that owns the ZINC mint and token accounts. */
    tokenProgram: TAccountMetas[13];
    /** System Program used if the winner ATA needs to be created. */
    systemProgram: TAccountMetas[14];
  };
  data: PayoutStockpileInstructionData;
};

export function parsePayoutStockpileInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedPayoutStockpileInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 15) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 15,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      config: getNextAccount(),
      stockpile: getNextAccount(),
      stockpileWinners: getNextAccount(),
      stockpileExtras: getNextAccount(),
      board: getNextAccount(),
      treasury: getNextAccount(),
      stockpileSolVault: getNextAccount(),
      zincMint: getNextAccount(),
      stockpileTokenAccount: getNextAccount(),
      winner: getNextAccount(),
      winnerZincTokenAccount: getNextAccount(),
      associatedTokenProgram: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getPayoutStockpileInstructionDataDecoder().decode(instruction.data),
  };
}
