/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findConfigPda, findTreasuryPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const RECOVER_SETTLE_MINER_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([107, 18, 214, 148, 17, 176, 106, 169]);

export function getRecoverSettleMinerDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    RECOVER_SETTLE_MINER_DISCRIMINATOR,
  );
}

export type RecoverSettleMinerInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountRound extends string | AccountMeta<string> = string,
  TAccountMiner extends string | AccountMeta<string> = string,
  TAccountPlayerProfile extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountRound extends string
        ? WritableAccount<TAccountRound>
        : TAccountRound,
      TAccountMiner extends string
        ? WritableAccount<TAccountMiner>
        : TAccountMiner,
      TAccountPlayerProfile extends string
        ? WritableAccount<TAccountPlayerProfile>
        : TAccountPlayerProfile,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      ...TRemainingAccounts,
    ]
  >;

export type RecoverSettleMinerInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Admin-reviewed effective lamports on the winning tile for this miner. */
  winningStake: bigint;
  /** Admin-reviewed number of selected tiles in the recovered mask evidence. */
  selectedCount: number;
  /** Operator-facing reason for this recovery action. */
  reason: string;
  /** Hash of the off-chain evidence bundle that justifies the recovered result. */
  evidenceHash: ReadonlyUint8Array;
};

export type RecoverSettleMinerInstructionDataArgs = {
  /** Admin-reviewed effective lamports on the winning tile for this miner. */
  winningStake: number | bigint;
  /** Admin-reviewed number of selected tiles in the recovered mask evidence. */
  selectedCount: number;
  /** Operator-facing reason for this recovery action. */
  reason: string;
  /** Hash of the off-chain evidence bundle that justifies the recovered result. */
  evidenceHash: ReadonlyUint8Array;
};

export function getRecoverSettleMinerInstructionDataEncoder(): Encoder<RecoverSettleMinerInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["winningStake", getU64Encoder()],
      ["selectedCount", getU8Encoder()],
      ["reason", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["evidenceHash", fixEncoderSize(getBytesEncoder(), 32)],
    ]),
    (value) => ({
      ...value,
      discriminator: RECOVER_SETTLE_MINER_DISCRIMINATOR,
    }),
  );
}

export function getRecoverSettleMinerInstructionDataDecoder(): Decoder<RecoverSettleMinerInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["winningStake", getU64Decoder()],
    ["selectedCount", getU8Decoder()],
    ["reason", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["evidenceHash", fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getRecoverSettleMinerInstructionDataCodec(): Codec<
  RecoverSettleMinerInstructionDataArgs,
  RecoverSettleMinerInstructionData
> {
  return combineCodec(
    getRecoverSettleMinerInstructionDataEncoder(),
    getRecoverSettleMinerInstructionDataDecoder(),
  );
}

export type RecoverSettleMinerAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountRound extends string = string,
  TAccountMiner extends string = string,
  TAccountPlayerProfile extends string = string,
  TAccountTreasury extends string = string,
> = {
  /** Admin signer authorized by the protocol config. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config containing the admin authority and Bonanza settlement settings. */
  config?: Address<TAccountConfig>;
  /** Revealed round currently waiting on per-miner settlement. */
  round: Address<TAccountRound>;
  /** Miner whose settlement result is recovered from admin-reviewed evidence. */
  miner: Address<TAccountMiner>;
  /** Player profile that receives the same hidden-bonus bricks as normal settlement. */
  playerProfile: Address<TAccountPlayerProfile>;
  /** Treasury Bonanza state that may snapshot the live pot when this is the final miner. */
  treasury?: Address<TAccountTreasury>;
  winningStake: RecoverSettleMinerInstructionDataArgs["winningStake"];
  selectedCount: RecoverSettleMinerInstructionDataArgs["selectedCount"];
  reason: RecoverSettleMinerInstructionDataArgs["reason"];
  evidenceHash: RecoverSettleMinerInstructionDataArgs["evidenceHash"];
};

export async function getRecoverSettleMinerInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountRound extends string,
  TAccountMiner extends string,
  TAccountPlayerProfile extends string,
  TAccountTreasury extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: RecoverSettleMinerAsyncInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountRound,
    TAccountMiner,
    TAccountPlayerProfile,
    TAccountTreasury
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RecoverSettleMinerInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountRound,
    TAccountMiner,
    TAccountPlayerProfile,
    TAccountTreasury
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    round: { value: input.round ?? null, isWritable: true },
    miner: { value: input.miner ?? null, isWritable: true },
    playerProfile: { value: input.playerProfile ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("round", accounts.round),
      getAccountMeta("miner", accounts.miner),
      getAccountMeta("playerProfile", accounts.playerProfile),
      getAccountMeta("treasury", accounts.treasury),
    ],
    data: getRecoverSettleMinerInstructionDataEncoder().encode(
      args as RecoverSettleMinerInstructionDataArgs,
    ),
    programAddress,
  } as RecoverSettleMinerInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountRound,
    TAccountMiner,
    TAccountPlayerProfile,
    TAccountTreasury
  >);
}

export type RecoverSettleMinerInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountRound extends string = string,
  TAccountMiner extends string = string,
  TAccountPlayerProfile extends string = string,
  TAccountTreasury extends string = string,
> = {
  /** Admin signer authorized by the protocol config. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config containing the admin authority and Bonanza settlement settings. */
  config: Address<TAccountConfig>;
  /** Revealed round currently waiting on per-miner settlement. */
  round: Address<TAccountRound>;
  /** Miner whose settlement result is recovered from admin-reviewed evidence. */
  miner: Address<TAccountMiner>;
  /** Player profile that receives the same hidden-bonus bricks as normal settlement. */
  playerProfile: Address<TAccountPlayerProfile>;
  /** Treasury Bonanza state that may snapshot the live pot when this is the final miner. */
  treasury: Address<TAccountTreasury>;
  winningStake: RecoverSettleMinerInstructionDataArgs["winningStake"];
  selectedCount: RecoverSettleMinerInstructionDataArgs["selectedCount"];
  reason: RecoverSettleMinerInstructionDataArgs["reason"];
  evidenceHash: RecoverSettleMinerInstructionDataArgs["evidenceHash"];
};

export function getRecoverSettleMinerInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountRound extends string,
  TAccountMiner extends string,
  TAccountPlayerProfile extends string,
  TAccountTreasury extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: RecoverSettleMinerInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountRound,
    TAccountMiner,
    TAccountPlayerProfile,
    TAccountTreasury
  >,
  config?: { programAddress?: TProgramAddress },
): RecoverSettleMinerInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountConfig,
  TAccountRound,
  TAccountMiner,
  TAccountPlayerProfile,
  TAccountTreasury
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    round: { value: input.round ?? null, isWritable: true },
    miner: { value: input.miner ?? null, isWritable: true },
    playerProfile: { value: input.playerProfile ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("round", accounts.round),
      getAccountMeta("miner", accounts.miner),
      getAccountMeta("playerProfile", accounts.playerProfile),
      getAccountMeta("treasury", accounts.treasury),
    ],
    data: getRecoverSettleMinerInstructionDataEncoder().encode(
      args as RecoverSettleMinerInstructionDataArgs,
    ),
    programAddress,
  } as RecoverSettleMinerInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountRound,
    TAccountMiner,
    TAccountPlayerProfile,
    TAccountTreasury
  >);
}

export type ParsedRecoverSettleMinerInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin signer authorized by the protocol config. */
    admin: TAccountMetas[0];
    /** Global config containing the admin authority and Bonanza settlement settings. */
    config: TAccountMetas[1];
    /** Revealed round currently waiting on per-miner settlement. */
    round: TAccountMetas[2];
    /** Miner whose settlement result is recovered from admin-reviewed evidence. */
    miner: TAccountMetas[3];
    /** Player profile that receives the same hidden-bonus bricks as normal settlement. */
    playerProfile: TAccountMetas[4];
    /** Treasury Bonanza state that may snapshot the live pot when this is the final miner. */
    treasury: TAccountMetas[5];
  };
  data: RecoverSettleMinerInstructionData;
};

export function parseRecoverSettleMinerInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRecoverSettleMinerInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      config: getNextAccount(),
      round: getNextAccount(),
      miner: getNextAccount(),
      playerProfile: getNextAccount(),
      treasury: getNextAccount(),
    },
    data: getRecoverSettleMinerInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
