/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findAffiliateProfilePda, findPlayerProfilePda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const REGISTER_AFFILIATE_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([87, 121, 99, 184, 126, 63, 103, 217]);

export function getRegisterAffiliateDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REGISTER_AFFILIATE_DISCRIMINATOR,
  );
}

export type RegisterAffiliateInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountPlayerProfile extends string | AccountMeta<string> = string,
  TAccountAffiliate extends string | AccountMeta<string> = string,
  TAccountAffiliateProfile extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountPlayerProfile extends string
        ? WritableAccount<TAccountPlayerProfile>
        : TAccountPlayerProfile,
      TAccountAffiliate extends string
        ? ReadonlyAccount<TAccountAffiliate>
        : TAccountAffiliate,
      TAccountAffiliateProfile extends string
        ? ReadonlyAccount<TAccountAffiliateProfile>
        : TAccountAffiliateProfile,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type RegisterAffiliateInstructionData = {
  discriminator: ReadonlyUint8Array;
};

export type RegisterAffiliateInstructionDataArgs = {};

export function getRegisterAffiliateInstructionDataEncoder(): FixedSizeEncoder<RegisterAffiliateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: REGISTER_AFFILIATE_DISCRIMINATOR }),
  );
}

export function getRegisterAffiliateInstructionDataDecoder(): FixedSizeDecoder<RegisterAffiliateInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRegisterAffiliateInstructionDataCodec(): FixedSizeCodec<
  RegisterAffiliateInstructionDataArgs,
  RegisterAffiliateInstructionData
> {
  return combineCodec(
    getRegisterAffiliateInstructionDataEncoder(),
    getRegisterAffiliateInstructionDataDecoder(),
  );
}

export type RegisterAffiliateAsyncInput<
  TAccountSigner extends string = string,
  TAccountPlayerProfile extends string = string,
  TAccountAffiliate extends string = string,
  TAccountAffiliateProfile extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Player wallet binding its profile to an affiliate before deploy. */
  signer: TransactionSigner<TAccountSigner>;
  /** Lifetime profile for the signing player. */
  playerProfile?: Address<TAccountPlayerProfile>;
  affiliate: Address<TAccountAffiliate>;
  /** Existing initialized player profile owned by the affiliate wallet. */
  affiliateProfile?: Address<TAccountAffiliateProfile>;
  /** System program used when the signer profile must be created. */
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getRegisterAffiliateInstructionAsync<
  TAccountSigner extends string,
  TAccountPlayerProfile extends string,
  TAccountAffiliate extends string,
  TAccountAffiliateProfile extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: RegisterAffiliateAsyncInput<
    TAccountSigner,
    TAccountPlayerProfile,
    TAccountAffiliate,
    TAccountAffiliateProfile,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  RegisterAffiliateInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountPlayerProfile,
    TAccountAffiliate,
    TAccountAffiliateProfile,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    playerProfile: { value: input.playerProfile ?? null, isWritable: true },
    affiliate: { value: input.affiliate ?? null, isWritable: false },
    affiliateProfile: {
      value: input.affiliateProfile ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.playerProfile.value) {
    accounts.playerProfile.value = await findPlayerProfilePda({
      signer: getAddressFromResolvedInstructionAccount(
        "signer",
        accounts.signer.value,
      ),
    });
  }
  if (!accounts.affiliateProfile.value) {
    accounts.affiliateProfile.value = await findAffiliateProfilePda({
      affiliate: getAddressFromResolvedInstructionAccount(
        "affiliate",
        accounts.affiliate.value,
      ),
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("playerProfile", accounts.playerProfile),
      getAccountMeta("affiliate", accounts.affiliate),
      getAccountMeta("affiliateProfile", accounts.affiliateProfile),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getRegisterAffiliateInstructionDataEncoder().encode({}),
    programAddress,
  } as RegisterAffiliateInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountPlayerProfile,
    TAccountAffiliate,
    TAccountAffiliateProfile,
    TAccountSystemProgram
  >);
}

export type RegisterAffiliateInput<
  TAccountSigner extends string = string,
  TAccountPlayerProfile extends string = string,
  TAccountAffiliate extends string = string,
  TAccountAffiliateProfile extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  /** Player wallet binding its profile to an affiliate before deploy. */
  signer: TransactionSigner<TAccountSigner>;
  /** Lifetime profile for the signing player. */
  playerProfile: Address<TAccountPlayerProfile>;
  affiliate: Address<TAccountAffiliate>;
  /** Existing initialized player profile owned by the affiliate wallet. */
  affiliateProfile: Address<TAccountAffiliateProfile>;
  /** System program used when the signer profile must be created. */
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getRegisterAffiliateInstruction<
  TAccountSigner extends string,
  TAccountPlayerProfile extends string,
  TAccountAffiliate extends string,
  TAccountAffiliateProfile extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: RegisterAffiliateInput<
    TAccountSigner,
    TAccountPlayerProfile,
    TAccountAffiliate,
    TAccountAffiliateProfile,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): RegisterAffiliateInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountPlayerProfile,
  TAccountAffiliate,
  TAccountAffiliateProfile,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    playerProfile: { value: input.playerProfile ?? null, isWritable: true },
    affiliate: { value: input.affiliate ?? null, isWritable: false },
    affiliateProfile: {
      value: input.affiliateProfile ?? null,
      isWritable: false,
    },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("playerProfile", accounts.playerProfile),
      getAccountMeta("affiliate", accounts.affiliate),
      getAccountMeta("affiliateProfile", accounts.affiliateProfile),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getRegisterAffiliateInstructionDataEncoder().encode({}),
    programAddress,
  } as RegisterAffiliateInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountPlayerProfile,
    TAccountAffiliate,
    TAccountAffiliateProfile,
    TAccountSystemProgram
  >);
}

export type ParsedRegisterAffiliateInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Player wallet binding its profile to an affiliate before deploy. */
    signer: TAccountMetas[0];
    /** Lifetime profile for the signing player. */
    playerProfile: TAccountMetas[1];
    affiliate: TAccountMetas[2];
    /** Existing initialized player profile owned by the affiliate wallet. */
    affiliateProfile: TAccountMetas[3];
    /** System program used when the signer profile must be created. */
    systemProgram: TAccountMetas[4];
  };
  data: RegisterAffiliateInstructionData;
};

export function parseRegisterAffiliateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRegisterAffiliateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 5) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 5,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      playerProfile: getNextAccount(),
      affiliate: getNextAccount(),
      affiliateProfile: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getRegisterAffiliateInstructionDataDecoder().decode(instruction.data),
  };
}
