/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import {
  findStakePositionPda,
  findStakingTokenAccountPda,
  findTreasuryPda,
} from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const STAKE_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  206, 176, 202, 18, 200, 209, 179, 108,
]);

export function getStakeDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(STAKE_DISCRIMINATOR);
}

export type StakeInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountSigner extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountZincMint extends string | AccountMeta<string> = string,
  TAccountSignerZincTokenAccount extends string | AccountMeta<string> = string,
  TAccountStakePosition extends string | AccountMeta<string> = string,
  TAccountStakingTokenAccount extends string | AccountMeta<string> = string,
  TAccountTokenProgram extends
    | string
    | AccountMeta<string> = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
  TAccountSystemProgram extends
    | string
    | AccountMeta<string> = "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountSigner extends string
        ? WritableSignerAccount<TAccountSigner> &
            AccountSignerMeta<TAccountSigner>
        : TAccountSigner,
      TAccountTreasury extends string
        ? WritableAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountZincMint extends string
        ? ReadonlyAccount<TAccountZincMint>
        : TAccountZincMint,
      TAccountSignerZincTokenAccount extends string
        ? WritableAccount<TAccountSignerZincTokenAccount>
        : TAccountSignerZincTokenAccount,
      TAccountStakePosition extends string
        ? WritableAccount<TAccountStakePosition>
        : TAccountStakePosition,
      TAccountStakingTokenAccount extends string
        ? WritableAccount<TAccountStakingTokenAccount>
        : TAccountStakingTokenAccount,
      TAccountTokenProgram extends string
        ? ReadonlyAccount<TAccountTokenProgram>
        : TAccountTokenProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts
    ]
  >;

export type StakeInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Raw ZINC amount to move from the signer into the staking vault. */
  amount: bigint;
};

export type StakeInstructionDataArgs = {
  /** Raw ZINC amount to move from the signer into the staking vault. */
  amount: number | bigint;
};

export function getStakeInstructionDataEncoder(): FixedSizeEncoder<StakeInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["amount", getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: STAKE_DISCRIMINATOR })
  );
}

export function getStakeInstructionDataDecoder(): FixedSizeDecoder<StakeInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["amount", getU64Decoder()],
  ]);
}

export function getStakeInstructionDataCodec(): FixedSizeCodec<
  StakeInstructionDataArgs,
  StakeInstructionData
> {
  return combineCodec(
    getStakeInstructionDataEncoder(),
    getStakeInstructionDataDecoder()
  );
}

export type StakeAsyncInput<
  TAccountSigner extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountSignerZincTokenAccount extends string = string,
  TAccountStakePosition extends string = string,
  TAccountStakingTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string
> = {
  /** Wallet that stakes ZINC and pays rent when opening its stake position. */
  signer: TransactionSigner<TAccountSigner>;
  /** Treasury PDA that owns the shared staking vault and accounting. */
  treasury?: Address<TAccountTreasury>;
  /** Protocol ZINC mint. */
  zincMint: Address<TAccountZincMint>;
  /** Signer-owned ZINC token account that funds the stake deposit. */
  signerZincTokenAccount?: Address<TAccountSignerZincTokenAccount>;
  /** Per-user stake position that records cumulative treasury rewards. */
  stakePosition?: Address<TAccountStakePosition>;
  /** Treasury-owned staking vault that escrows all staked ZINC. */
  stakingTokenAccount?: Address<TAccountStakingTokenAccount>;
  /** SPL Token Program that owns the ZINC mint and staking vault. */
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  amount: StakeInstructionDataArgs["amount"];
};

export async function getStakeInstructionAsync<
  TAccountSigner extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountSignerZincTokenAccount extends string,
  TAccountStakePosition extends string,
  TAccountStakingTokenAccount extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: StakeAsyncInput<
    TAccountSigner,
    TAccountTreasury,
    TAccountZincMint,
    TAccountSignerZincTokenAccount,
    TAccountStakePosition,
    TAccountStakingTokenAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  StakeInstruction<
    TProgramAddress,
    TAccountSigner,
    TAccountTreasury,
    TAccountZincMint,
    TAccountSignerZincTokenAccount,
    TAccountStakePosition,
    TAccountStakingTokenAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: false },
    signerZincTokenAccount: {
      value: input.signerZincTokenAccount ?? null,
      isWritable: true,
    },
    stakePosition: { value: input.stakePosition ?? null, isWritable: true },
    stakingTokenAccount: {
      value: input.stakingTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.signerZincTokenAccount.value) {
    accounts.signerZincTokenAccount.value = await getProgramDerivedAddress({
      programAddress:
        "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" as Address<"ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL">,
      seeds: [
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "signer",
            accounts.signer.value
          )
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "tokenProgram",
            accounts.tokenProgram.value
          )
        ),
        getAddressEncoder().encode(
          getAddressFromResolvedInstructionAccount(
            "zincMint",
            accounts.zincMint.value
          )
        ),
      ],
    });
  }
  if (!accounts.stakePosition.value) {
    accounts.stakePosition.value = await findStakePositionPda({
      signer: getAddressFromResolvedInstructionAccount(
        "signer",
        accounts.signer.value
      ),
    });
  }
  if (!accounts.stakingTokenAccount.value) {
    accounts.stakingTokenAccount.value = await findStakingTokenAccountPda();
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("signerZincTokenAccount", accounts.signerZincTokenAccount),
      getAccountMeta("stakePosition", accounts.stakePosition),
      getAccountMeta("stakingTokenAccount", accounts.stakingTokenAccount),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getStakeInstructionDataEncoder().encode(
      args as StakeInstructionDataArgs
    ),
    programAddress,
  } as StakeInstruction<TProgramAddress, TAccountSigner, TAccountTreasury, TAccountZincMint, TAccountSignerZincTokenAccount, TAccountStakePosition, TAccountStakingTokenAccount, TAccountTokenProgram, TAccountSystemProgram>);
}

export type StakeInput<
  TAccountSigner extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountSignerZincTokenAccount extends string = string,
  TAccountStakePosition extends string = string,
  TAccountStakingTokenAccount extends string = string,
  TAccountTokenProgram extends string = string,
  TAccountSystemProgram extends string = string
> = {
  /** Wallet that stakes ZINC and pays rent when opening its stake position. */
  signer: TransactionSigner<TAccountSigner>;
  /** Treasury PDA that owns the shared staking vault and accounting. */
  treasury: Address<TAccountTreasury>;
  /** Protocol ZINC mint. */
  zincMint: Address<TAccountZincMint>;
  /** Signer-owned ZINC token account that funds the stake deposit. */
  signerZincTokenAccount: Address<TAccountSignerZincTokenAccount>;
  /** Per-user stake position that records cumulative treasury rewards. */
  stakePosition: Address<TAccountStakePosition>;
  /** Treasury-owned staking vault that escrows all staked ZINC. */
  stakingTokenAccount: Address<TAccountStakingTokenAccount>;
  /** SPL Token Program that owns the ZINC mint and staking vault. */
  tokenProgram?: Address<TAccountTokenProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  amount: StakeInstructionDataArgs["amount"];
};

export function getStakeInstruction<
  TAccountSigner extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountSignerZincTokenAccount extends string,
  TAccountStakePosition extends string,
  TAccountStakingTokenAccount extends string,
  TAccountTokenProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: StakeInput<
    TAccountSigner,
    TAccountTreasury,
    TAccountZincMint,
    TAccountSignerZincTokenAccount,
    TAccountStakePosition,
    TAccountStakingTokenAccount,
    TAccountTokenProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress }
): StakeInstruction<
  TProgramAddress,
  TAccountSigner,
  TAccountTreasury,
  TAccountZincMint,
  TAccountSignerZincTokenAccount,
  TAccountStakePosition,
  TAccountStakingTokenAccount,
  TAccountTokenProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    signer: { value: input.signer ?? null, isWritable: true },
    treasury: { value: input.treasury ?? null, isWritable: true },
    zincMint: { value: input.zincMint ?? null, isWritable: false },
    signerZincTokenAccount: {
      value: input.signerZincTokenAccount ?? null,
      isWritable: true,
    },
    stakePosition: { value: input.stakePosition ?? null, isWritable: true },
    stakingTokenAccount: {
      value: input.stakingTokenAccount ?? null,
      isWritable: true,
    },
    tokenProgram: { value: input.tokenProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.tokenProgram.value) {
    accounts.tokenProgram.value =
      "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" as Address<"TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("signer", accounts.signer),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("signerZincTokenAccount", accounts.signerZincTokenAccount),
      getAccountMeta("stakePosition", accounts.stakePosition),
      getAccountMeta("stakingTokenAccount", accounts.stakingTokenAccount),
      getAccountMeta("tokenProgram", accounts.tokenProgram),
      getAccountMeta("systemProgram", accounts.systemProgram),
    ],
    data: getStakeInstructionDataEncoder().encode(
      args as StakeInstructionDataArgs
    ),
    programAddress,
  } as StakeInstruction<TProgramAddress, TAccountSigner, TAccountTreasury, TAccountZincMint, TAccountSignerZincTokenAccount, TAccountStakePosition, TAccountStakingTokenAccount, TAccountTokenProgram, TAccountSystemProgram>);
}

export type ParsedStakeInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Wallet that stakes ZINC and pays rent when opening its stake position. */
    signer: TAccountMetas[0];
    /** Treasury PDA that owns the shared staking vault and accounting. */
    treasury: TAccountMetas[1];
    /** Protocol ZINC mint. */
    zincMint: TAccountMetas[2];
    /** Signer-owned ZINC token account that funds the stake deposit. */
    signerZincTokenAccount: TAccountMetas[3];
    /** Per-user stake position that records cumulative treasury rewards. */
    stakePosition: TAccountMetas[4];
    /** Treasury-owned staking vault that escrows all staked ZINC. */
    stakingTokenAccount: TAccountMetas[5];
    /** SPL Token Program that owns the ZINC mint and staking vault. */
    tokenProgram: TAccountMetas[6];
    systemProgram: TAccountMetas[7];
  };
  data: StakeInstructionData;
};

export function parseStakeInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedStakeInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 8) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 8,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      signer: getNextAccount(),
      treasury: getNextAccount(),
      zincMint: getNextAccount(),
      signerZincTokenAccount: getNextAccount(),
      stakePosition: getNextAccount(),
      stakingTokenAccount: getNextAccount(),
      tokenProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getStakeInstructionDataDecoder().decode(instruction.data),
  };
}
