/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU128Decoder,
  getU128Encoder,
  getU16Decoder,
  getU16Encoder,
  getU64Decoder,
  getU64Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findAutoMinerSessionPda, findConfigPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";

export const UPDATE_AUTO_MINER_SESSION_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([123, 139, 24, 168, 50, 205, 157, 81]);

export function getUpdateAutoMinerSessionDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_AUTO_MINER_SESSION_DISCRIMINATOR,
  );
}

export type UpdateAutoMinerSessionInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountAuthority extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountAutoMinerSession extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAuthority extends string
        ? ReadonlySignerAccount<TAccountAuthority> &
            AccountSignerMeta<TAccountAuthority>
        : TAccountAuthority,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountAutoMinerSession extends string
        ? WritableAccount<TAccountAutoMinerSession>
        : TAccountAutoMinerSession,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateAutoMinerSessionInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Crank wallet allowed to execute auto deploys. */
  executor: Address;
  /** Gross lamports to deploy into each eligible round. */
  amountPerRound: bigint;
  /** Ephemeral public key used to encrypt the tile-pattern bits to the crank. */
  maskBitsEncryptionKey: ReadonlyUint8Array;
  /** Rescue CTR nonce used for the encrypted tile-pattern bits. */
  maskBitsNonce: bigint;
  /** Encrypted tile-pattern bits readable only by the configured crank. */
  maskBitsCiphertext: ReadonlyUint8Array;
  /** Crank encryption-key version used by the browser when encrypting the pattern. */
  maskBitsKeyVersion: number;
  /** Optional last slot at which the session can still deploy. */
  expirySlot: Option<bigint>;
  /** Whether the authority paused auto execution. */
  paused: boolean;
  /** Fixed lamport reimbursement paid to the crank after a successful deploy. */
  crankReimbursementLamports: bigint;
  /** Whether the crank may reload credited round SOL into the session budget. */
  autoReloadSolRewards: boolean;
};

export type UpdateAutoMinerSessionInstructionDataArgs = {
  /** Crank wallet allowed to execute auto deploys. */
  executor: Address;
  /** Gross lamports to deploy into each eligible round. */
  amountPerRound: number | bigint;
  /** Ephemeral public key used to encrypt the tile-pattern bits to the crank. */
  maskBitsEncryptionKey: ReadonlyUint8Array;
  /** Rescue CTR nonce used for the encrypted tile-pattern bits. */
  maskBitsNonce: number | bigint;
  /** Encrypted tile-pattern bits readable only by the configured crank. */
  maskBitsCiphertext: ReadonlyUint8Array;
  /** Crank encryption-key version used by the browser when encrypting the pattern. */
  maskBitsKeyVersion: number;
  /** Optional last slot at which the session can still deploy. */
  expirySlot: OptionOrNullable<number | bigint>;
  /** Whether the authority paused auto execution. */
  paused: boolean;
  /** Fixed lamport reimbursement paid to the crank after a successful deploy. */
  crankReimbursementLamports: number | bigint;
  /** Whether the crank may reload credited round SOL into the session budget. */
  autoReloadSolRewards: boolean;
};

export function getUpdateAutoMinerSessionInstructionDataEncoder(): Encoder<UpdateAutoMinerSessionInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["executor", getAddressEncoder()],
      ["amountPerRound", getU64Encoder()],
      ["maskBitsEncryptionKey", fixEncoderSize(getBytesEncoder(), 32)],
      ["maskBitsNonce", getU128Encoder()],
      ["maskBitsCiphertext", fixEncoderSize(getBytesEncoder(), 32)],
      ["maskBitsKeyVersion", getU16Encoder()],
      ["expirySlot", getOptionEncoder(getU64Encoder())],
      ["paused", getBooleanEncoder()],
      ["crankReimbursementLamports", getU64Encoder()],
      ["autoReloadSolRewards", getBooleanEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_AUTO_MINER_SESSION_DISCRIMINATOR,
    }),
  );
}

export function getUpdateAutoMinerSessionInstructionDataDecoder(): Decoder<UpdateAutoMinerSessionInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["executor", getAddressDecoder()],
    ["amountPerRound", getU64Decoder()],
    ["maskBitsEncryptionKey", fixDecoderSize(getBytesDecoder(), 32)],
    ["maskBitsNonce", getU128Decoder()],
    ["maskBitsCiphertext", fixDecoderSize(getBytesDecoder(), 32)],
    ["maskBitsKeyVersion", getU16Decoder()],
    ["expirySlot", getOptionDecoder(getU64Decoder())],
    ["paused", getBooleanDecoder()],
    ["crankReimbursementLamports", getU64Decoder()],
    ["autoReloadSolRewards", getBooleanDecoder()],
  ]);
}

export function getUpdateAutoMinerSessionInstructionDataCodec(): Codec<
  UpdateAutoMinerSessionInstructionDataArgs,
  UpdateAutoMinerSessionInstructionData
> {
  return combineCodec(
    getUpdateAutoMinerSessionInstructionDataEncoder(),
    getUpdateAutoMinerSessionInstructionDataDecoder(),
  );
}

export type UpdateAutoMinerSessionAsyncInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountAutoMinerSession extends string = string,
> = {
  /** Wallet that owns and controls the session. */
  authority: TransactionSigner<TAccountAuthority>;
  /** Global config that defines the only accepted auto-miner executor. */
  config?: Address<TAccountConfig>;
  /** Player-owned auto-miner session PDA. */
  autoMinerSession?: Address<TAccountAutoMinerSession>;
  executor: UpdateAutoMinerSessionInstructionDataArgs["executor"];
  amountPerRound: UpdateAutoMinerSessionInstructionDataArgs["amountPerRound"];
  maskBitsEncryptionKey: UpdateAutoMinerSessionInstructionDataArgs["maskBitsEncryptionKey"];
  maskBitsNonce: UpdateAutoMinerSessionInstructionDataArgs["maskBitsNonce"];
  maskBitsCiphertext: UpdateAutoMinerSessionInstructionDataArgs["maskBitsCiphertext"];
  maskBitsKeyVersion: UpdateAutoMinerSessionInstructionDataArgs["maskBitsKeyVersion"];
  expirySlot: UpdateAutoMinerSessionInstructionDataArgs["expirySlot"];
  paused: UpdateAutoMinerSessionInstructionDataArgs["paused"];
  crankReimbursementLamports: UpdateAutoMinerSessionInstructionDataArgs["crankReimbursementLamports"];
  autoReloadSolRewards: UpdateAutoMinerSessionInstructionDataArgs["autoReloadSolRewards"];
};

export async function getUpdateAutoMinerSessionInstructionAsync<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountAutoMinerSession extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: UpdateAutoMinerSessionAsyncInput<
    TAccountAuthority,
    TAccountConfig,
    TAccountAutoMinerSession
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  UpdateAutoMinerSessionInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountAutoMinerSession
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    autoMinerSession: {
      value: input.autoMinerSession ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.autoMinerSession.value) {
    accounts.autoMinerSession.value = await findAutoMinerSessionPda({
      authority: getAddressFromResolvedInstructionAccount(
        "authority",
        accounts.authority.value,
      ),
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("autoMinerSession", accounts.autoMinerSession),
    ],
    data: getUpdateAutoMinerSessionInstructionDataEncoder().encode(
      args as UpdateAutoMinerSessionInstructionDataArgs,
    ),
    programAddress,
  } as UpdateAutoMinerSessionInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountAutoMinerSession
  >);
}

export type UpdateAutoMinerSessionInput<
  TAccountAuthority extends string = string,
  TAccountConfig extends string = string,
  TAccountAutoMinerSession extends string = string,
> = {
  /** Wallet that owns and controls the session. */
  authority: TransactionSigner<TAccountAuthority>;
  /** Global config that defines the only accepted auto-miner executor. */
  config: Address<TAccountConfig>;
  /** Player-owned auto-miner session PDA. */
  autoMinerSession: Address<TAccountAutoMinerSession>;
  executor: UpdateAutoMinerSessionInstructionDataArgs["executor"];
  amountPerRound: UpdateAutoMinerSessionInstructionDataArgs["amountPerRound"];
  maskBitsEncryptionKey: UpdateAutoMinerSessionInstructionDataArgs["maskBitsEncryptionKey"];
  maskBitsNonce: UpdateAutoMinerSessionInstructionDataArgs["maskBitsNonce"];
  maskBitsCiphertext: UpdateAutoMinerSessionInstructionDataArgs["maskBitsCiphertext"];
  maskBitsKeyVersion: UpdateAutoMinerSessionInstructionDataArgs["maskBitsKeyVersion"];
  expirySlot: UpdateAutoMinerSessionInstructionDataArgs["expirySlot"];
  paused: UpdateAutoMinerSessionInstructionDataArgs["paused"];
  crankReimbursementLamports: UpdateAutoMinerSessionInstructionDataArgs["crankReimbursementLamports"];
  autoReloadSolRewards: UpdateAutoMinerSessionInstructionDataArgs["autoReloadSolRewards"];
};

export function getUpdateAutoMinerSessionInstruction<
  TAccountAuthority extends string,
  TAccountConfig extends string,
  TAccountAutoMinerSession extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: UpdateAutoMinerSessionInput<
    TAccountAuthority,
    TAccountConfig,
    TAccountAutoMinerSession
  >,
  config?: { programAddress?: TProgramAddress },
): UpdateAutoMinerSessionInstruction<
  TProgramAddress,
  TAccountAuthority,
  TAccountConfig,
  TAccountAutoMinerSession
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    authority: { value: input.authority ?? null, isWritable: false },
    config: { value: input.config ?? null, isWritable: false },
    autoMinerSession: {
      value: input.autoMinerSession ?? null,
      isWritable: true,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("authority", accounts.authority),
      getAccountMeta("config", accounts.config),
      getAccountMeta("autoMinerSession", accounts.autoMinerSession),
    ],
    data: getUpdateAutoMinerSessionInstructionDataEncoder().encode(
      args as UpdateAutoMinerSessionInstructionDataArgs,
    ),
    programAddress,
  } as UpdateAutoMinerSessionInstruction<
    TProgramAddress,
    TAccountAuthority,
    TAccountConfig,
    TAccountAutoMinerSession
  >);
}

export type ParsedUpdateAutoMinerSessionInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Wallet that owns and controls the session. */
    authority: TAccountMetas[0];
    /** Global config that defines the only accepted auto-miner executor. */
    config: TAccountMetas[1];
    /** Player-owned auto-miner session PDA. */
    autoMinerSession: TAccountMetas[2];
  };
  data: UpdateAutoMinerSessionInstructionData;
};

export function parseUpdateAutoMinerSessionInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateAutoMinerSessionInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      authority: getNextAccount(),
      config: getNextAccount(),
      autoMinerSession: getNextAccount(),
    },
    data: getUpdateAutoMinerSessionInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
