/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findBoardPda, findConfigPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";
import {
  getRoundRandomnessModeDecoder,
  getRoundRandomnessModeEncoder,
  getSettlementCapabilityDecoder,
  getSettlementCapabilityEncoder,
  type RoundRandomnessMode,
  type RoundRandomnessModeArgs,
  type SettlementCapability,
  type SettlementCapabilityArgs,
} from "../types";

export const UPDATE_CONFIG_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  29, 158, 252, 191, 10, 83, 219, 99,
]);

export function getUpdateConfigDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_CONFIG_DISCRIMINATOR,
  );
}

export type UpdateConfigInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountBoard extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? WritableAccount<TAccountConfig>
        : TAccountConfig,
      TAccountBoard extends string
        ? WritableAccount<TAccountBoard>
        : TAccountBoard,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateConfigInstructionData = {
  discriminator: ReadonlyUint8Array;
  /** Total deploy-time SOL fee skim in basis points. */
  deployTotalFeeBps: Option<bigint>;
  /** Number of slots a round stays open once activated. */
  roundDurationSlots: Option<bigint>;
  /** Number of slots after reveal before selecting the next playable round. */
  roundStartDelaySlots: Option<bigint>;
  /** Number of slots a stockpile stays open once activated. */
  stockpileDurationSlots: Option<bigint>;
  /** Minimum stockpile bricks required to join one cycle, in `x10k` units. */
  stockpileMinEntryBricksX10k: Option<bigint>;
  /** Gross deploy-time SOL admin fee in basis points. */
  deployAdminFeeBps: Option<bigint>;
  /** Gross deploy-time SOL stockpile fee in basis points. */
  deployStockpileFeeBps: Option<bigint>;
  /** Gross deploy-time SOL affiliate fee in basis points when the player is bound. */
  deployAffiliateFeeBps: Option<bigint>;
  /** Whether affiliates may currently withdraw accrued SOL. */
  affiliateWithdrawalsEnabled: Option<boolean>;
  /** Curve-minted ZINC admin skim in basis points. */
  curveAdminFeeBps: Option<bigint>;
  /** Share of post-skim curve mint reserved for direct round winners, in basis points. */
  winnerZincShareBps: Option<bigint>;
  /** Share of post-skim curve mint that accrues to stockpile ZINC, in basis points. */
  stockpileZincShareBps: Option<bigint>;
  /** No-winner direct-winner ZINC redirect share that accrues to Bonanza, in basis points. */
  noWinnerDirectWinnerZincBonanzaShareBps: Option<bigint>;
  /** No-winner direct-winner ZINC redirect share that accrues to stockpile, in basis points. */
  noWinnerDirectWinnerZincStockpileShareBps: Option<bigint>;
  /** Minimum gross lamports required to enter one round. */
  minDeployLamports: Option<bigint>;
  /** Launch-time maximum mint for one round before ZINC factoring and support caps. */
  curveMaxRoundMint: Option<bigint>;
  /** SOL factoring lamports where the deploy curve reaches about `1 - e^-1` of max mint. */
  curveSaturationLamports: Option<bigint>;
  /** ZINC factoring amount that halves scarcity emissions, in base units. */
  curveHistoryMinted: Option<bigint>;
  /** Min target ZINC support lamports required for one emitted token. */
  curveTargetSupportLamportsPerZinc: Option<bigint>;
  /** Maximum cumulative ZINC the close-round mint path may mint, in base units. */
  curveMaxSupply: Option<bigint>;
  /** Optional crank authority to persist on both config and board. */
  crank: Option<Address>;
  /** Flat deploy-time stockpile-bricks bonus for referred players, in `x10k` units. */
  deployAffiliateBonusBricksX10k: Option<bigint>;
  /** Deterministic Wildcat cadence; `0` disables Wildcat. */
  wildcatRoundFrequency: Option<bigint>;
  /** Direct-winner ZINC share reserved for Wildcat winners, in ppm. */
  wildcatWinnerZincSharePpm: Option<bigint>;
  /** Bonanza roll modulo divisor; `1` makes every winner-positive round eligible. */
  bonanzaHitDivisor: Option<bigint>;
  /** ZINC fee skim for round winner claims, in basis points. */
  roundClaimZincFeeBps: Option<bigint>;
  /** Legacy stockpile ZINC fee kept for serialized config compatibility. */
  stockpileEntryMinZincFee: Option<bigint>;
  /** Stockpile entry fee as a share of the live stockpile ZINC pot, in basis points. */
  stockpileEntryPotFeeBps: Option<bigint>;
  /** Accepted-entry step multiplier for stockpile entry costs, in basis points. */
  stockpileEntryStepBps: Option<bigint>;
  /** Staking brick issuance rate per claimed ZINC, in `x10k` units. */
  stakingBricksPerZincX10k: Option<bigint>;
  /** Number of slots over which newly melted staking rewards vest. */
  stakingRewardVestingSlots: Option<bigint>;
  /** Arcium priority price per CU for round reveal computations, in micro-lamports. */
  arciumRevealCuPriceMicro: Option<bigint>;
  /** Minimum refill size as a share of current stockpile entry bricks, in basis points. */
  stockpileRefillMinEntryBps: Option<bigint>;
  /** Live randomness reveal path for closed rounds. */
  roundRandomnessMode: Option<RoundRandomnessMode>;
  /** Live settlement capability selected by the operator. */
  settlementCapability: Option<SettlementCapability>;
  /** Number of slots after close used as the blockhash reveal sample delay. */
  blockhashRevealDelaySlots: Option<bigint>;
  /** Stockpile bricks required per whole ZINC, in `x10k` units. */
  stockpileBricksPerZincX10k: Option<bigint>;
  /** Configured active Stockpile winner ranks. */
  stockpileWinnerCount: Option<number>;
  /** Ranked Stockpile payout shares in basis points. */
  stockpileWinnerShareBps: Option<Array<bigint>>;
  /** Server BabyJub public key X field element bytes accepted for ZK mask attestations. */
  zkMaskServerBabyjubPubkeyX: Option<ReadonlyUint8Array>;
  /** Server BabyJub public key Y field element bytes accepted for ZK mask attestations. */
  zkMaskServerBabyjubPubkeyY: Option<ReadonlyUint8Array>;
  /** Accepted server key version for ZK mask attestations. */
  zkMaskServerKeyVersion: Option<bigint>;
  /** Accepted circuit version for ZK mask attestations. */
  zkMaskCircuitVersion: Option<bigint>;
  /** Emergency switch that skips init-round Arcium CPI in blockhash private-ZK mode. */
  skipArciumInitCpi: Option<boolean>;
};

export type UpdateConfigInstructionDataArgs = {
  /** Total deploy-time SOL fee skim in basis points. */
  deployTotalFeeBps: OptionOrNullable<number | bigint>;
  /** Number of slots a round stays open once activated. */
  roundDurationSlots: OptionOrNullable<number | bigint>;
  /** Number of slots after reveal before selecting the next playable round. */
  roundStartDelaySlots: OptionOrNullable<number | bigint>;
  /** Number of slots a stockpile stays open once activated. */
  stockpileDurationSlots: OptionOrNullable<number | bigint>;
  /** Minimum stockpile bricks required to join one cycle, in `x10k` units. */
  stockpileMinEntryBricksX10k: OptionOrNullable<number | bigint>;
  /** Gross deploy-time SOL admin fee in basis points. */
  deployAdminFeeBps: OptionOrNullable<number | bigint>;
  /** Gross deploy-time SOL stockpile fee in basis points. */
  deployStockpileFeeBps: OptionOrNullable<number | bigint>;
  /** Gross deploy-time SOL affiliate fee in basis points when the player is bound. */
  deployAffiliateFeeBps: OptionOrNullable<number | bigint>;
  /** Whether affiliates may currently withdraw accrued SOL. */
  affiliateWithdrawalsEnabled: OptionOrNullable<boolean>;
  /** Curve-minted ZINC admin skim in basis points. */
  curveAdminFeeBps: OptionOrNullable<number | bigint>;
  /** Share of post-skim curve mint reserved for direct round winners, in basis points. */
  winnerZincShareBps: OptionOrNullable<number | bigint>;
  /** Share of post-skim curve mint that accrues to stockpile ZINC, in basis points. */
  stockpileZincShareBps: OptionOrNullable<number | bigint>;
  /** No-winner direct-winner ZINC redirect share that accrues to Bonanza, in basis points. */
  noWinnerDirectWinnerZincBonanzaShareBps: OptionOrNullable<number | bigint>;
  /** No-winner direct-winner ZINC redirect share that accrues to stockpile, in basis points. */
  noWinnerDirectWinnerZincStockpileShareBps: OptionOrNullable<number | bigint>;
  /** Minimum gross lamports required to enter one round. */
  minDeployLamports: OptionOrNullable<number | bigint>;
  /** Launch-time maximum mint for one round before ZINC factoring and support caps. */
  curveMaxRoundMint: OptionOrNullable<number | bigint>;
  /** SOL factoring lamports where the deploy curve reaches about `1 - e^-1` of max mint. */
  curveSaturationLamports: OptionOrNullable<number | bigint>;
  /** ZINC factoring amount that halves scarcity emissions, in base units. */
  curveHistoryMinted: OptionOrNullable<number | bigint>;
  /** Min target ZINC support lamports required for one emitted token. */
  curveTargetSupportLamportsPerZinc: OptionOrNullable<number | bigint>;
  /** Maximum cumulative ZINC the close-round mint path may mint, in base units. */
  curveMaxSupply: OptionOrNullable<number | bigint>;
  /** Optional crank authority to persist on both config and board. */
  crank: OptionOrNullable<Address>;
  /** Flat deploy-time stockpile-bricks bonus for referred players, in `x10k` units. */
  deployAffiliateBonusBricksX10k: OptionOrNullable<number | bigint>;
  /** Deterministic Wildcat cadence; `0` disables Wildcat. */
  wildcatRoundFrequency: OptionOrNullable<number | bigint>;
  /** Direct-winner ZINC share reserved for Wildcat winners, in ppm. */
  wildcatWinnerZincSharePpm: OptionOrNullable<number | bigint>;
  /** Bonanza roll modulo divisor; `1` makes every winner-positive round eligible. */
  bonanzaHitDivisor: OptionOrNullable<number | bigint>;
  /** ZINC fee skim for round winner claims, in basis points. */
  roundClaimZincFeeBps: OptionOrNullable<number | bigint>;
  /** Legacy stockpile ZINC fee kept for serialized config compatibility. */
  stockpileEntryMinZincFee: OptionOrNullable<number | bigint>;
  /** Stockpile entry fee as a share of the live stockpile ZINC pot, in basis points. */
  stockpileEntryPotFeeBps: OptionOrNullable<number | bigint>;
  /** Accepted-entry step multiplier for stockpile entry costs, in basis points. */
  stockpileEntryStepBps: OptionOrNullable<number | bigint>;
  /** Staking brick issuance rate per claimed ZINC, in `x10k` units. */
  stakingBricksPerZincX10k: OptionOrNullable<number | bigint>;
  /** Number of slots over which newly melted staking rewards vest. */
  stakingRewardVestingSlots: OptionOrNullable<number | bigint>;
  /** Arcium priority price per CU for round reveal computations, in micro-lamports. */
  arciumRevealCuPriceMicro: OptionOrNullable<number | bigint>;
  /** Minimum refill size as a share of current stockpile entry bricks, in basis points. */
  stockpileRefillMinEntryBps: OptionOrNullable<number | bigint>;
  /** Live randomness reveal path for closed rounds. */
  roundRandomnessMode: OptionOrNullable<RoundRandomnessModeArgs>;
  /** Live settlement capability selected by the operator. */
  settlementCapability: OptionOrNullable<SettlementCapabilityArgs>;
  /** Number of slots after close used as the blockhash reveal sample delay. */
  blockhashRevealDelaySlots: OptionOrNullable<number | bigint>;
  /** Stockpile bricks required per whole ZINC, in `x10k` units. */
  stockpileBricksPerZincX10k: OptionOrNullable<number | bigint>;
  /** Configured active Stockpile winner ranks. */
  stockpileWinnerCount: OptionOrNullable<number>;
  /** Ranked Stockpile payout shares in basis points. */
  stockpileWinnerShareBps: OptionOrNullable<Array<number | bigint>>;
  /** Server BabyJub public key X field element bytes accepted for ZK mask attestations. */
  zkMaskServerBabyjubPubkeyX: OptionOrNullable<ReadonlyUint8Array>;
  /** Server BabyJub public key Y field element bytes accepted for ZK mask attestations. */
  zkMaskServerBabyjubPubkeyY: OptionOrNullable<ReadonlyUint8Array>;
  /** Accepted server key version for ZK mask attestations. */
  zkMaskServerKeyVersion: OptionOrNullable<number | bigint>;
  /** Accepted circuit version for ZK mask attestations. */
  zkMaskCircuitVersion: OptionOrNullable<number | bigint>;
  /** Emergency switch that skips init-round Arcium CPI in blockhash private-ZK mode. */
  skipArciumInitCpi: OptionOrNullable<boolean>;
};

export function getUpdateConfigInstructionDataEncoder(): Encoder<UpdateConfigInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["deployTotalFeeBps", getOptionEncoder(getU64Encoder())],
      ["roundDurationSlots", getOptionEncoder(getU64Encoder())],
      ["roundStartDelaySlots", getOptionEncoder(getU64Encoder())],
      ["stockpileDurationSlots", getOptionEncoder(getU64Encoder())],
      ["stockpileMinEntryBricksX10k", getOptionEncoder(getU64Encoder())],
      ["deployAdminFeeBps", getOptionEncoder(getU64Encoder())],
      ["deployStockpileFeeBps", getOptionEncoder(getU64Encoder())],
      ["deployAffiliateFeeBps", getOptionEncoder(getU64Encoder())],
      ["affiliateWithdrawalsEnabled", getOptionEncoder(getBooleanEncoder())],
      ["curveAdminFeeBps", getOptionEncoder(getU64Encoder())],
      ["winnerZincShareBps", getOptionEncoder(getU64Encoder())],
      ["stockpileZincShareBps", getOptionEncoder(getU64Encoder())],
      [
        "noWinnerDirectWinnerZincBonanzaShareBps",
        getOptionEncoder(getU64Encoder()),
      ],
      [
        "noWinnerDirectWinnerZincStockpileShareBps",
        getOptionEncoder(getU64Encoder()),
      ],
      ["minDeployLamports", getOptionEncoder(getU64Encoder())],
      ["curveMaxRoundMint", getOptionEncoder(getU64Encoder())],
      ["curveSaturationLamports", getOptionEncoder(getU64Encoder())],
      ["curveHistoryMinted", getOptionEncoder(getU64Encoder())],
      ["curveTargetSupportLamportsPerZinc", getOptionEncoder(getU64Encoder())],
      ["curveMaxSupply", getOptionEncoder(getU64Encoder())],
      ["crank", getOptionEncoder(getAddressEncoder())],
      ["deployAffiliateBonusBricksX10k", getOptionEncoder(getU64Encoder())],
      ["wildcatRoundFrequency", getOptionEncoder(getU64Encoder())],
      ["wildcatWinnerZincSharePpm", getOptionEncoder(getU64Encoder())],
      ["bonanzaHitDivisor", getOptionEncoder(getU64Encoder())],
      ["roundClaimZincFeeBps", getOptionEncoder(getU64Encoder())],
      ["stockpileEntryMinZincFee", getOptionEncoder(getU64Encoder())],
      ["stockpileEntryPotFeeBps", getOptionEncoder(getU64Encoder())],
      ["stockpileEntryStepBps", getOptionEncoder(getU64Encoder())],
      ["stakingBricksPerZincX10k", getOptionEncoder(getU64Encoder())],
      ["stakingRewardVestingSlots", getOptionEncoder(getU64Encoder())],
      ["arciumRevealCuPriceMicro", getOptionEncoder(getU64Encoder())],
      ["stockpileRefillMinEntryBps", getOptionEncoder(getU64Encoder())],
      [
        "roundRandomnessMode",
        getOptionEncoder(getRoundRandomnessModeEncoder()),
      ],
      [
        "settlementCapability",
        getOptionEncoder(getSettlementCapabilityEncoder()),
      ],
      ["blockhashRevealDelaySlots", getOptionEncoder(getU64Encoder())],
      ["stockpileBricksPerZincX10k", getOptionEncoder(getU64Encoder())],
      ["stockpileWinnerCount", getOptionEncoder(getU8Encoder())],
      [
        "stockpileWinnerShareBps",
        getOptionEncoder(getArrayEncoder(getU64Encoder(), { size: 5 })),
      ],
      [
        "zkMaskServerBabyjubPubkeyX",
        getOptionEncoder(fixEncoderSize(getBytesEncoder(), 32)),
      ],
      [
        "zkMaskServerBabyjubPubkeyY",
        getOptionEncoder(fixEncoderSize(getBytesEncoder(), 32)),
      ],
      ["zkMaskServerKeyVersion", getOptionEncoder(getU64Encoder())],
      ["zkMaskCircuitVersion", getOptionEncoder(getU64Encoder())],
      ["skipArciumInitCpi", getOptionEncoder(getBooleanEncoder())],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_CONFIG_DISCRIMINATOR }),
  );
}

export function getUpdateConfigInstructionDataDecoder(): Decoder<UpdateConfigInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["deployTotalFeeBps", getOptionDecoder(getU64Decoder())],
    ["roundDurationSlots", getOptionDecoder(getU64Decoder())],
    ["roundStartDelaySlots", getOptionDecoder(getU64Decoder())],
    ["stockpileDurationSlots", getOptionDecoder(getU64Decoder())],
    ["stockpileMinEntryBricksX10k", getOptionDecoder(getU64Decoder())],
    ["deployAdminFeeBps", getOptionDecoder(getU64Decoder())],
    ["deployStockpileFeeBps", getOptionDecoder(getU64Decoder())],
    ["deployAffiliateFeeBps", getOptionDecoder(getU64Decoder())],
    ["affiliateWithdrawalsEnabled", getOptionDecoder(getBooleanDecoder())],
    ["curveAdminFeeBps", getOptionDecoder(getU64Decoder())],
    ["winnerZincShareBps", getOptionDecoder(getU64Decoder())],
    ["stockpileZincShareBps", getOptionDecoder(getU64Decoder())],
    [
      "noWinnerDirectWinnerZincBonanzaShareBps",
      getOptionDecoder(getU64Decoder()),
    ],
    [
      "noWinnerDirectWinnerZincStockpileShareBps",
      getOptionDecoder(getU64Decoder()),
    ],
    ["minDeployLamports", getOptionDecoder(getU64Decoder())],
    ["curveMaxRoundMint", getOptionDecoder(getU64Decoder())],
    ["curveSaturationLamports", getOptionDecoder(getU64Decoder())],
    ["curveHistoryMinted", getOptionDecoder(getU64Decoder())],
    ["curveTargetSupportLamportsPerZinc", getOptionDecoder(getU64Decoder())],
    ["curveMaxSupply", getOptionDecoder(getU64Decoder())],
    ["crank", getOptionDecoder(getAddressDecoder())],
    ["deployAffiliateBonusBricksX10k", getOptionDecoder(getU64Decoder())],
    ["wildcatRoundFrequency", getOptionDecoder(getU64Decoder())],
    ["wildcatWinnerZincSharePpm", getOptionDecoder(getU64Decoder())],
    ["bonanzaHitDivisor", getOptionDecoder(getU64Decoder())],
    ["roundClaimZincFeeBps", getOptionDecoder(getU64Decoder())],
    ["stockpileEntryMinZincFee", getOptionDecoder(getU64Decoder())],
    ["stockpileEntryPotFeeBps", getOptionDecoder(getU64Decoder())],
    ["stockpileEntryStepBps", getOptionDecoder(getU64Decoder())],
    ["stakingBricksPerZincX10k", getOptionDecoder(getU64Decoder())],
    ["stakingRewardVestingSlots", getOptionDecoder(getU64Decoder())],
    ["arciumRevealCuPriceMicro", getOptionDecoder(getU64Decoder())],
    ["stockpileRefillMinEntryBps", getOptionDecoder(getU64Decoder())],
    ["roundRandomnessMode", getOptionDecoder(getRoundRandomnessModeDecoder())],
    [
      "settlementCapability",
      getOptionDecoder(getSettlementCapabilityDecoder()),
    ],
    ["blockhashRevealDelaySlots", getOptionDecoder(getU64Decoder())],
    ["stockpileBricksPerZincX10k", getOptionDecoder(getU64Decoder())],
    ["stockpileWinnerCount", getOptionDecoder(getU8Decoder())],
    [
      "stockpileWinnerShareBps",
      getOptionDecoder(getArrayDecoder(getU64Decoder(), { size: 5 })),
    ],
    [
      "zkMaskServerBabyjubPubkeyX",
      getOptionDecoder(fixDecoderSize(getBytesDecoder(), 32)),
    ],
    [
      "zkMaskServerBabyjubPubkeyY",
      getOptionDecoder(fixDecoderSize(getBytesDecoder(), 32)),
    ],
    ["zkMaskServerKeyVersion", getOptionDecoder(getU64Decoder())],
    ["zkMaskCircuitVersion", getOptionDecoder(getU64Decoder())],
    ["skipArciumInitCpi", getOptionDecoder(getBooleanDecoder())],
  ]);
}

export function getUpdateConfigInstructionDataCodec(): Codec<
  UpdateConfigInstructionDataArgs,
  UpdateConfigInstructionData
> {
  return combineCodec(
    getUpdateConfigInstructionDataEncoder(),
    getUpdateConfigInstructionDataDecoder(),
  );
}

export type UpdateConfigAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config?: Address<TAccountConfig>;
  /** Stores the currently enabled round, if any, and the next allocatable round ID. */
  board?: Address<TAccountBoard>;
  deployTotalFeeBps: UpdateConfigInstructionDataArgs["deployTotalFeeBps"];
  roundDurationSlots: UpdateConfigInstructionDataArgs["roundDurationSlots"];
  roundStartDelaySlots: UpdateConfigInstructionDataArgs["roundStartDelaySlots"];
  stockpileDurationSlots: UpdateConfigInstructionDataArgs["stockpileDurationSlots"];
  stockpileMinEntryBricksX10k: UpdateConfigInstructionDataArgs["stockpileMinEntryBricksX10k"];
  deployAdminFeeBps: UpdateConfigInstructionDataArgs["deployAdminFeeBps"];
  deployStockpileFeeBps: UpdateConfigInstructionDataArgs["deployStockpileFeeBps"];
  deployAffiliateFeeBps: UpdateConfigInstructionDataArgs["deployAffiliateFeeBps"];
  affiliateWithdrawalsEnabled: UpdateConfigInstructionDataArgs["affiliateWithdrawalsEnabled"];
  curveAdminFeeBps: UpdateConfigInstructionDataArgs["curveAdminFeeBps"];
  winnerZincShareBps: UpdateConfigInstructionDataArgs["winnerZincShareBps"];
  stockpileZincShareBps: UpdateConfigInstructionDataArgs["stockpileZincShareBps"];
  noWinnerDirectWinnerZincBonanzaShareBps: UpdateConfigInstructionDataArgs["noWinnerDirectWinnerZincBonanzaShareBps"];
  noWinnerDirectWinnerZincStockpileShareBps: UpdateConfigInstructionDataArgs["noWinnerDirectWinnerZincStockpileShareBps"];
  minDeployLamports: UpdateConfigInstructionDataArgs["minDeployLamports"];
  curveMaxRoundMint: UpdateConfigInstructionDataArgs["curveMaxRoundMint"];
  curveSaturationLamports: UpdateConfigInstructionDataArgs["curveSaturationLamports"];
  curveHistoryMinted: UpdateConfigInstructionDataArgs["curveHistoryMinted"];
  curveTargetSupportLamportsPerZinc: UpdateConfigInstructionDataArgs["curveTargetSupportLamportsPerZinc"];
  curveMaxSupply: UpdateConfigInstructionDataArgs["curveMaxSupply"];
  crank: UpdateConfigInstructionDataArgs["crank"];
  deployAffiliateBonusBricksX10k: UpdateConfigInstructionDataArgs["deployAffiliateBonusBricksX10k"];
  wildcatRoundFrequency: UpdateConfigInstructionDataArgs["wildcatRoundFrequency"];
  wildcatWinnerZincSharePpm: UpdateConfigInstructionDataArgs["wildcatWinnerZincSharePpm"];
  bonanzaHitDivisor: UpdateConfigInstructionDataArgs["bonanzaHitDivisor"];
  roundClaimZincFeeBps: UpdateConfigInstructionDataArgs["roundClaimZincFeeBps"];
  stockpileEntryMinZincFee: UpdateConfigInstructionDataArgs["stockpileEntryMinZincFee"];
  stockpileEntryPotFeeBps: UpdateConfigInstructionDataArgs["stockpileEntryPotFeeBps"];
  stockpileEntryStepBps: UpdateConfigInstructionDataArgs["stockpileEntryStepBps"];
  stakingBricksPerZincX10k: UpdateConfigInstructionDataArgs["stakingBricksPerZincX10k"];
  stakingRewardVestingSlots: UpdateConfigInstructionDataArgs["stakingRewardVestingSlots"];
  arciumRevealCuPriceMicro: UpdateConfigInstructionDataArgs["arciumRevealCuPriceMicro"];
  stockpileRefillMinEntryBps: UpdateConfigInstructionDataArgs["stockpileRefillMinEntryBps"];
  roundRandomnessMode: UpdateConfigInstructionDataArgs["roundRandomnessMode"];
  settlementCapability: UpdateConfigInstructionDataArgs["settlementCapability"];
  blockhashRevealDelaySlots: UpdateConfigInstructionDataArgs["blockhashRevealDelaySlots"];
  stockpileBricksPerZincX10k: UpdateConfigInstructionDataArgs["stockpileBricksPerZincX10k"];
  stockpileWinnerCount: UpdateConfigInstructionDataArgs["stockpileWinnerCount"];
  stockpileWinnerShareBps: UpdateConfigInstructionDataArgs["stockpileWinnerShareBps"];
  zkMaskServerBabyjubPubkeyX: UpdateConfigInstructionDataArgs["zkMaskServerBabyjubPubkeyX"];
  zkMaskServerBabyjubPubkeyY: UpdateConfigInstructionDataArgs["zkMaskServerBabyjubPubkeyY"];
  zkMaskServerKeyVersion: UpdateConfigInstructionDataArgs["zkMaskServerKeyVersion"];
  zkMaskCircuitVersion: UpdateConfigInstructionDataArgs["zkMaskCircuitVersion"];
  skipArciumInitCpi: UpdateConfigInstructionDataArgs["skipArciumInitCpi"];
};

export async function getUpdateConfigInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: UpdateConfigAsyncInput<TAccountAdmin, TAccountConfig, TAccountBoard>,
  config?: { programAddress?: TProgramAddress },
): Promise<
  UpdateConfigInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountBoard
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
    board: { value: input.board ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.board.value) {
    accounts.board.value = await findBoardPda();
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
    ],
    data: getUpdateConfigInstructionDataEncoder().encode(
      args as UpdateConfigInstructionDataArgs,
    ),
    programAddress,
  } as UpdateConfigInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountBoard
  >);
}

export type UpdateConfigInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountBoard extends string = string,
> = {
  admin: TransactionSigner<TAccountAdmin>;
  config: Address<TAccountConfig>;
  /** Stores the currently enabled round, if any, and the next allocatable round ID. */
  board: Address<TAccountBoard>;
  deployTotalFeeBps: UpdateConfigInstructionDataArgs["deployTotalFeeBps"];
  roundDurationSlots: UpdateConfigInstructionDataArgs["roundDurationSlots"];
  roundStartDelaySlots: UpdateConfigInstructionDataArgs["roundStartDelaySlots"];
  stockpileDurationSlots: UpdateConfigInstructionDataArgs["stockpileDurationSlots"];
  stockpileMinEntryBricksX10k: UpdateConfigInstructionDataArgs["stockpileMinEntryBricksX10k"];
  deployAdminFeeBps: UpdateConfigInstructionDataArgs["deployAdminFeeBps"];
  deployStockpileFeeBps: UpdateConfigInstructionDataArgs["deployStockpileFeeBps"];
  deployAffiliateFeeBps: UpdateConfigInstructionDataArgs["deployAffiliateFeeBps"];
  affiliateWithdrawalsEnabled: UpdateConfigInstructionDataArgs["affiliateWithdrawalsEnabled"];
  curveAdminFeeBps: UpdateConfigInstructionDataArgs["curveAdminFeeBps"];
  winnerZincShareBps: UpdateConfigInstructionDataArgs["winnerZincShareBps"];
  stockpileZincShareBps: UpdateConfigInstructionDataArgs["stockpileZincShareBps"];
  noWinnerDirectWinnerZincBonanzaShareBps: UpdateConfigInstructionDataArgs["noWinnerDirectWinnerZincBonanzaShareBps"];
  noWinnerDirectWinnerZincStockpileShareBps: UpdateConfigInstructionDataArgs["noWinnerDirectWinnerZincStockpileShareBps"];
  minDeployLamports: UpdateConfigInstructionDataArgs["minDeployLamports"];
  curveMaxRoundMint: UpdateConfigInstructionDataArgs["curveMaxRoundMint"];
  curveSaturationLamports: UpdateConfigInstructionDataArgs["curveSaturationLamports"];
  curveHistoryMinted: UpdateConfigInstructionDataArgs["curveHistoryMinted"];
  curveTargetSupportLamportsPerZinc: UpdateConfigInstructionDataArgs["curveTargetSupportLamportsPerZinc"];
  curveMaxSupply: UpdateConfigInstructionDataArgs["curveMaxSupply"];
  crank: UpdateConfigInstructionDataArgs["crank"];
  deployAffiliateBonusBricksX10k: UpdateConfigInstructionDataArgs["deployAffiliateBonusBricksX10k"];
  wildcatRoundFrequency: UpdateConfigInstructionDataArgs["wildcatRoundFrequency"];
  wildcatWinnerZincSharePpm: UpdateConfigInstructionDataArgs["wildcatWinnerZincSharePpm"];
  bonanzaHitDivisor: UpdateConfigInstructionDataArgs["bonanzaHitDivisor"];
  roundClaimZincFeeBps: UpdateConfigInstructionDataArgs["roundClaimZincFeeBps"];
  stockpileEntryMinZincFee: UpdateConfigInstructionDataArgs["stockpileEntryMinZincFee"];
  stockpileEntryPotFeeBps: UpdateConfigInstructionDataArgs["stockpileEntryPotFeeBps"];
  stockpileEntryStepBps: UpdateConfigInstructionDataArgs["stockpileEntryStepBps"];
  stakingBricksPerZincX10k: UpdateConfigInstructionDataArgs["stakingBricksPerZincX10k"];
  stakingRewardVestingSlots: UpdateConfigInstructionDataArgs["stakingRewardVestingSlots"];
  arciumRevealCuPriceMicro: UpdateConfigInstructionDataArgs["arciumRevealCuPriceMicro"];
  stockpileRefillMinEntryBps: UpdateConfigInstructionDataArgs["stockpileRefillMinEntryBps"];
  roundRandomnessMode: UpdateConfigInstructionDataArgs["roundRandomnessMode"];
  settlementCapability: UpdateConfigInstructionDataArgs["settlementCapability"];
  blockhashRevealDelaySlots: UpdateConfigInstructionDataArgs["blockhashRevealDelaySlots"];
  stockpileBricksPerZincX10k: UpdateConfigInstructionDataArgs["stockpileBricksPerZincX10k"];
  stockpileWinnerCount: UpdateConfigInstructionDataArgs["stockpileWinnerCount"];
  stockpileWinnerShareBps: UpdateConfigInstructionDataArgs["stockpileWinnerShareBps"];
  zkMaskServerBabyjubPubkeyX: UpdateConfigInstructionDataArgs["zkMaskServerBabyjubPubkeyX"];
  zkMaskServerBabyjubPubkeyY: UpdateConfigInstructionDataArgs["zkMaskServerBabyjubPubkeyY"];
  zkMaskServerKeyVersion: UpdateConfigInstructionDataArgs["zkMaskServerKeyVersion"];
  zkMaskCircuitVersion: UpdateConfigInstructionDataArgs["zkMaskCircuitVersion"];
  skipArciumInitCpi: UpdateConfigInstructionDataArgs["skipArciumInitCpi"];
};

export function getUpdateConfigInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountBoard extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS,
>(
  input: UpdateConfigInput<TAccountAdmin, TAccountConfig, TAccountBoard>,
  config?: { programAddress?: TProgramAddress },
): UpdateConfigInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountConfig,
  TAccountBoard
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: true },
    board: { value: input.board ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("board", accounts.board),
    ],
    data: getUpdateConfigInstructionDataEncoder().encode(
      args as UpdateConfigInstructionDataArgs,
    ),
    programAddress,
  } as UpdateConfigInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountBoard
  >);
}

export type ParsedUpdateConfigInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    admin: TAccountMetas[0];
    config: TAccountMetas[1];
    /** Stores the currently enabled round, if any, and the next allocatable round ID. */
    board: TAccountMetas[2];
  };
  data: UpdateConfigInstructionData;
};

export function parseUpdateConfigInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedUpdateConfigInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 3,
      },
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      config: getNextAccount(),
      board: getNextAccount(),
    },
    data: getUpdateConfigInstructionDataDecoder().decode(instruction.data),
  };
}
