/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
  SolanaError,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import {
  getAccountMetaFactory,
  getAddressFromResolvedInstructionAccount,
  type ResolvedInstructionAccount,
} from "@solana/program-client-core";
import { findConfigPda, findTreasuryPda, findZincMetadataPda } from "../pdas";
import { ZINC_PROGRAM_ADDRESS } from "../programs";
import {
  getZincMintMetadataArgsDecoder,
  getZincMintMetadataArgsEncoder,
  type ZincMintMetadataArgs,
  type ZincMintMetadataArgsArgs,
} from "../types";

export const UPDATE_ZINC_MINT_METADATA_DISCRIMINATOR: ReadonlyUint8Array =
  new Uint8Array([129, 29, 107, 197, 70, 193, 189, 186]);

export function getUpdateZincMintMetadataDiscriminatorBytes(): ReadonlyUint8Array {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    UPDATE_ZINC_MINT_METADATA_DISCRIMINATOR
  );
}

export type UpdateZincMintMetadataInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountAdmin extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountTreasury extends string | AccountMeta<string> = string,
  TAccountZincMint extends string | AccountMeta<string> = string,
  TAccountZincMetadata extends string | AccountMeta<string> = string,
  TAccountMetadataProgram extends
    | string
    | AccountMeta<string> = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s",
  TRemainingAccounts extends readonly AccountMeta<string>[] = []
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountAdmin extends string
        ? WritableSignerAccount<TAccountAdmin> &
            AccountSignerMeta<TAccountAdmin>
        : TAccountAdmin,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountTreasury extends string
        ? ReadonlyAccount<TAccountTreasury>
        : TAccountTreasury,
      TAccountZincMint extends string
        ? ReadonlyAccount<TAccountZincMint>
        : TAccountZincMint,
      TAccountZincMetadata extends string
        ? WritableAccount<TAccountZincMetadata>
        : TAccountZincMetadata,
      TAccountMetadataProgram extends string
        ? ReadonlyAccount<TAccountMetadataProgram>
        : TAccountMetadataProgram,
      ...TRemainingAccounts
    ]
  >;

export type UpdateZincMintMetadataInstructionData = {
  discriminator: ReadonlyUint8Array;
  args: ZincMintMetadataArgs;
};

export type UpdateZincMintMetadataInstructionDataArgs = {
  args: ZincMintMetadataArgsArgs;
};

export function getUpdateZincMintMetadataInstructionDataEncoder(): Encoder<UpdateZincMintMetadataInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["args", getZincMintMetadataArgsEncoder()],
    ]),
    (value) => ({
      ...value,
      discriminator: UPDATE_ZINC_MINT_METADATA_DISCRIMINATOR,
    })
  );
}

export function getUpdateZincMintMetadataInstructionDataDecoder(): Decoder<UpdateZincMintMetadataInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["args", getZincMintMetadataArgsDecoder()],
  ]);
}

export function getUpdateZincMintMetadataInstructionDataCodec(): Codec<
  UpdateZincMintMetadataInstructionDataArgs,
  UpdateZincMintMetadataInstructionData
> {
  return combineCodec(
    getUpdateZincMintMetadataInstructionDataEncoder(),
    getUpdateZincMintMetadataInstructionDataDecoder()
  );
}

export type UpdateZincMintMetadataAsyncInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountZincMetadata extends string = string,
  TAccountMetadataProgram extends string = string
> = {
  /** Admin authorized to update protocol ZINC mint metadata. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config that stores the protocol admin address. */
  config?: Address<TAccountConfig>;
  /** Treasury PDA that owns the ZINC mint metadata update authority. */
  treasury?: Address<TAccountTreasury>;
  /** Protocol ZINC mint whose metadata is being updated. */
  zincMint: Address<TAccountZincMint>;
  /** Metaplex metadata account attached to the protocol ZINC mint. */
  zincMetadata?: Address<TAccountZincMetadata>;
  /** Metaplex Token Metadata Program used to update ZINC mint metadata. */
  metadataProgram?: Address<TAccountMetadataProgram>;
  args: UpdateZincMintMetadataInstructionDataArgs["args"];
};

export async function getUpdateZincMintMetadataInstructionAsync<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountZincMetadata extends string,
  TAccountMetadataProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: UpdateZincMintMetadataAsyncInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountZincMint,
    TAccountZincMetadata,
    TAccountMetadataProgram
  >,
  config?: { programAddress?: TProgramAddress }
): Promise<
  UpdateZincMintMetadataInstruction<
    TProgramAddress,
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountZincMint,
    TAccountZincMetadata,
    TAccountMetadataProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: false },
    zincMint: { value: input.zincMint ?? null, isWritable: false },
    zincMetadata: { value: input.zincMetadata ?? null, isWritable: true },
    metadataProgram: {
      value: input.metadataProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await findConfigPda();
  }
  if (!accounts.treasury.value) {
    accounts.treasury.value = await findTreasuryPda();
  }
  if (!accounts.metadataProgram.value) {
    accounts.metadataProgram.value =
      "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" as Address<"metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s">;
  }
  if (!accounts.zincMetadata.value) {
    accounts.zincMetadata.value = await findZincMetadataPda({
      metadataProgram: getAddressFromResolvedInstructionAccount(
        "metadataProgram",
        accounts.metadataProgram.value
      ),
      zincMint: getAddressFromResolvedInstructionAccount(
        "zincMint",
        accounts.zincMint.value
      ),
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("zincMetadata", accounts.zincMetadata),
      getAccountMeta("metadataProgram", accounts.metadataProgram),
    ],
    data: getUpdateZincMintMetadataInstructionDataEncoder().encode(
      args as UpdateZincMintMetadataInstructionDataArgs
    ),
    programAddress,
  } as UpdateZincMintMetadataInstruction<TProgramAddress, TAccountAdmin, TAccountConfig, TAccountTreasury, TAccountZincMint, TAccountZincMetadata, TAccountMetadataProgram>);
}

export type UpdateZincMintMetadataInput<
  TAccountAdmin extends string = string,
  TAccountConfig extends string = string,
  TAccountTreasury extends string = string,
  TAccountZincMint extends string = string,
  TAccountZincMetadata extends string = string,
  TAccountMetadataProgram extends string = string
> = {
  /** Admin authorized to update protocol ZINC mint metadata. */
  admin: TransactionSigner<TAccountAdmin>;
  /** Global config that stores the protocol admin address. */
  config: Address<TAccountConfig>;
  /** Treasury PDA that owns the ZINC mint metadata update authority. */
  treasury: Address<TAccountTreasury>;
  /** Protocol ZINC mint whose metadata is being updated. */
  zincMint: Address<TAccountZincMint>;
  /** Metaplex metadata account attached to the protocol ZINC mint. */
  zincMetadata: Address<TAccountZincMetadata>;
  /** Metaplex Token Metadata Program used to update ZINC mint metadata. */
  metadataProgram?: Address<TAccountMetadataProgram>;
  args: UpdateZincMintMetadataInstructionDataArgs["args"];
};

export function getUpdateZincMintMetadataInstruction<
  TAccountAdmin extends string,
  TAccountConfig extends string,
  TAccountTreasury extends string,
  TAccountZincMint extends string,
  TAccountZincMetadata extends string,
  TAccountMetadataProgram extends string,
  TProgramAddress extends Address = typeof ZINC_PROGRAM_ADDRESS
>(
  input: UpdateZincMintMetadataInput<
    TAccountAdmin,
    TAccountConfig,
    TAccountTreasury,
    TAccountZincMint,
    TAccountZincMetadata,
    TAccountMetadataProgram
  >,
  config?: { programAddress?: TProgramAddress }
): UpdateZincMintMetadataInstruction<
  TProgramAddress,
  TAccountAdmin,
  TAccountConfig,
  TAccountTreasury,
  TAccountZincMint,
  TAccountZincMetadata,
  TAccountMetadataProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? ZINC_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    admin: { value: input.admin ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    treasury: { value: input.treasury ?? null, isWritable: false },
    zincMint: { value: input.zincMint ?? null, isWritable: false },
    zincMetadata: { value: input.zincMetadata ?? null, isWritable: true },
    metadataProgram: {
      value: input.metadataProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedInstructionAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.metadataProgram.value) {
    accounts.metadataProgram.value =
      "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" as Address<"metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta("admin", accounts.admin),
      getAccountMeta("config", accounts.config),
      getAccountMeta("treasury", accounts.treasury),
      getAccountMeta("zincMint", accounts.zincMint),
      getAccountMeta("zincMetadata", accounts.zincMetadata),
      getAccountMeta("metadataProgram", accounts.metadataProgram),
    ],
    data: getUpdateZincMintMetadataInstructionDataEncoder().encode(
      args as UpdateZincMintMetadataInstructionDataArgs
    ),
    programAddress,
  } as UpdateZincMintMetadataInstruction<TProgramAddress, TAccountAdmin, TAccountConfig, TAccountTreasury, TAccountZincMint, TAccountZincMetadata, TAccountMetadataProgram>);
}

export type ParsedUpdateZincMintMetadataInstruction<
  TProgram extends string = typeof ZINC_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[]
> = {
  programAddress: Address<TProgram>;
  accounts: {
    /** Admin authorized to update protocol ZINC mint metadata. */
    admin: TAccountMetas[0];
    /** Global config that stores the protocol admin address. */
    config: TAccountMetas[1];
    /** Treasury PDA that owns the ZINC mint metadata update authority. */
    treasury: TAccountMetas[2];
    /** Protocol ZINC mint whose metadata is being updated. */
    zincMint: TAccountMetas[3];
    /** Metaplex metadata account attached to the protocol ZINC mint. */
    zincMetadata: TAccountMetas[4];
    /** Metaplex Token Metadata Program used to update ZINC mint metadata. */
    metadataProgram: TAccountMetas[5];
  };
  data: UpdateZincMintMetadataInstructionData;
};

export function parseUpdateZincMintMetadataInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[]
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>
): ParsedUpdateZincMintMetadataInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    throw new SolanaError(
      SOLANA_ERROR__PROGRAM_CLIENTS__INSUFFICIENT_ACCOUNT_METAS,
      {
        actualAccountMetas: instruction.accounts.length,
        expectedAccountMetas: 6,
      }
    );
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      admin: getNextAccount(),
      config: getNextAccount(),
      treasury: getNextAccount(),
      zincMint: getNextAccount(),
      zincMetadata: getNextAccount(),
      metadataProgram: getNextAccount(),
    },
    data: getUpdateZincMintMetadataInstructionDataDecoder().decode(
      instruction.data
    ),
  };
}
